// Code generated by pulumi-language-go DO NOT EDIT.
// *** WARNING: Do not edit by hand unless you're certain you know what you are doing! ***

package cape

import (
	"context"
	"reflect"

	"errors"
	"github.com/pulumi/cape/sdk/go/cape/internal"
	"github.com/pulumi/pulumi/sdk/v3/go/pulumi"
)

type Provider struct {
	pulumi.ProviderResourceState

	// Provider prefix URL for Activity Log
	ActivityLogProviderPrefix pulumi.StringOutput `pulumi:"activityLogProviderPrefix"`
	// AuthToken is the bearer token that is attached to API calls.
	AuthToken pulumi.StringPtrOutput `pulumi:"authToken"`
	// Provider prefix URL for Authorization
	AuthorizationProviderPrefix pulumi.StringOutput `pulumi:"authorizationProviderPrefix"`
	// BaseURL defines the server url for API communication.
	BaseURL pulumi.StringOutput `pulumi:"baseURL"`
	// Provider prefix URL for Compute
	ComputeProviderPrefix pulumi.StringOutput `pulumi:"computeProviderPrefix"`
	// Provider prefix URL for Kubernetes
	KubernetesProviderPrefix pulumi.StringOutput `pulumi:"kubernetesProviderPrefix"`
	// Provider prefix URL for Load Balancer
	LoadBalancerProviderPrefix pulumi.StringOutput `pulumi:"loadBalancerProviderPrefix"`
	// Provider prefix URL for NAT Gateway
	NATGatewayProviderPrefix pulumi.StringOutput `pulumi:"nATGatewayProviderPrefix"`
	// Provider prefix URL for Network
	NetworkProviderPrefix pulumi.StringOutput `pulumi:"networkProviderPrefix"`
	// Provider prefix URL for Object Storage
	ObjectStorageProviderPrefix pulumi.StringOutput `pulumi:"objectStorageProviderPrefix"`
	// Provider prefix URL for Regions
	RegionsProviderPrefix pulumi.StringOutput `pulumi:"regionsProviderPrefix"`
	// Provider prefix URL for Storage
	StorageProviderPrefix pulumi.StringOutput `pulumi:"storageProviderPrefix"`
	// Tenant defines the default tenant used for all API calls. May be overwritten in specific calls.
	Tenant pulumi.StringOutput `pulumi:"tenant"`
	// Workspace defines a default workspace for all API calls. Can be omitted and given to all objects, or specifically overwritten for calls.
	Workspace pulumi.StringPtrOutput `pulumi:"workspace"`
	// Provider prefix URL for Workspace
	WorkspaceProviderPrefix pulumi.StringOutput `pulumi:"workspaceProviderPrefix"`
}

// NewProvider registers a new resource with the given unique name, arguments, and options.
func NewProvider(ctx *pulumi.Context,
	name string, args *ProviderArgs, opts ...pulumi.ResourceOption) (*Provider, error) {
	if args == nil {
		return nil, errors.New("missing one or more required arguments")
	}

	if args.BaseURL == nil {
		return nil, errors.New("invalid value for required argument 'BaseURL'")
	}
	if args.Tenant == nil {
		return nil, errors.New("invalid value for required argument 'Tenant'")
	}
	if args.ActivityLogProviderPrefix == nil {
		args.ActivityLogProviderPrefix = pulumi.StringPtr("/providers/seca.activity-log")
	}
	if args.AuthorizationProviderPrefix == nil {
		args.AuthorizationProviderPrefix = pulumi.StringPtr("/providers/seca.authorization")
	}
	if args.ComputeProviderPrefix == nil {
		args.ComputeProviderPrefix = pulumi.StringPtr("/providers/seca.compute")
	}
	if args.KubernetesProviderPrefix == nil {
		args.KubernetesProviderPrefix = pulumi.StringPtr("/providers/seca.kubernetes")
	}
	if args.LoadBalancerProviderPrefix == nil {
		args.LoadBalancerProviderPrefix = pulumi.StringPtr("/providers/seca.load-balancer")
	}
	if args.NATGatewayProviderPrefix == nil {
		args.NATGatewayProviderPrefix = pulumi.StringPtr("/providers/seca.nat-gateway")
	}
	if args.NetworkProviderPrefix == nil {
		args.NetworkProviderPrefix = pulumi.StringPtr("/providers/seca.network")
	}
	if args.ObjectStorageProviderPrefix == nil {
		args.ObjectStorageProviderPrefix = pulumi.StringPtr("/providers/seca.object-storage")
	}
	if args.RegionsProviderPrefix == nil {
		args.RegionsProviderPrefix = pulumi.StringPtr("/providers/seca.region")
	}
	if args.StorageProviderPrefix == nil {
		args.StorageProviderPrefix = pulumi.StringPtr("/providers/seca.storage")
	}
	if args.WorkspaceProviderPrefix == nil {
		args.WorkspaceProviderPrefix = pulumi.StringPtr("/providers/seca.workspace")
	}
	if args.AuthToken != nil {
		args.AuthToken = pulumi.ToSecret(args.AuthToken).(pulumi.StringPtrInput)
	}
	secrets := pulumi.AdditionalSecretOutputs([]string{
		"authToken",
	})
	opts = append(opts, secrets)
	opts = internal.PkgResourceDefaultOpts(opts)
	var resource Provider
	err := ctx.RegisterResource("pulumi:providers:cape", name, args, &resource, opts...)
	if err != nil {
		return nil, err
	}
	return &resource, nil
}

type providerArgs struct {
	// Provider prefix URL for Activity Log
	ActivityLogProviderPrefix *string `pulumi:"activityLogProviderPrefix"`
	// AuthToken is the bearer token that is attached to API calls.
	AuthToken *string `pulumi:"authToken"`
	// Provider prefix URL for Authorization
	AuthorizationProviderPrefix *string `pulumi:"authorizationProviderPrefix"`
	// BaseURL defines the server url for API communication.
	BaseURL string `pulumi:"baseURL"`
	// Provider prefix URL for Compute
	ComputeProviderPrefix *string `pulumi:"computeProviderPrefix"`
	// Provider prefix URL for Kubernetes
	KubernetesProviderPrefix *string `pulumi:"kubernetesProviderPrefix"`
	// Provider prefix URL for Load Balancer
	LoadBalancerProviderPrefix *string `pulumi:"loadBalancerProviderPrefix"`
	// Provider prefix URL for NAT Gateway
	NATGatewayProviderPrefix *string `pulumi:"nATGatewayProviderPrefix"`
	// Provider prefix URL for Network
	NetworkProviderPrefix *string `pulumi:"networkProviderPrefix"`
	// Provider prefix URL for Object Storage
	ObjectStorageProviderPrefix *string `pulumi:"objectStorageProviderPrefix"`
	// Provider prefix URL for Regions
	RegionsProviderPrefix *string `pulumi:"regionsProviderPrefix"`
	// Provider prefix URL for Storage
	StorageProviderPrefix *string `pulumi:"storageProviderPrefix"`
	// Tenant defines the default tenant used for all API calls. May be overwritten in specific calls.
	Tenant string `pulumi:"tenant"`
	// Workspace defines a default workspace for all API calls. Can be omitted and given to all objects, or specifically overwritten for calls.
	Workspace *string `pulumi:"workspace"`
	// Provider prefix URL for Workspace
	WorkspaceProviderPrefix *string `pulumi:"workspaceProviderPrefix"`
}

// The set of arguments for constructing a Provider resource.
type ProviderArgs struct {
	// Provider prefix URL for Activity Log
	ActivityLogProviderPrefix pulumi.StringPtrInput
	// AuthToken is the bearer token that is attached to API calls.
	AuthToken pulumi.StringPtrInput
	// Provider prefix URL for Authorization
	AuthorizationProviderPrefix pulumi.StringPtrInput
	// BaseURL defines the server url for API communication.
	BaseURL pulumi.StringInput
	// Provider prefix URL for Compute
	ComputeProviderPrefix pulumi.StringPtrInput
	// Provider prefix URL for Kubernetes
	KubernetesProviderPrefix pulumi.StringPtrInput
	// Provider prefix URL for Load Balancer
	LoadBalancerProviderPrefix pulumi.StringPtrInput
	// Provider prefix URL for NAT Gateway
	NATGatewayProviderPrefix pulumi.StringPtrInput
	// Provider prefix URL for Network
	NetworkProviderPrefix pulumi.StringPtrInput
	// Provider prefix URL for Object Storage
	ObjectStorageProviderPrefix pulumi.StringPtrInput
	// Provider prefix URL for Regions
	RegionsProviderPrefix pulumi.StringPtrInput
	// Provider prefix URL for Storage
	StorageProviderPrefix pulumi.StringPtrInput
	// Tenant defines the default tenant used for all API calls. May be overwritten in specific calls.
	Tenant pulumi.StringInput
	// Workspace defines a default workspace for all API calls. Can be omitted and given to all objects, or specifically overwritten for calls.
	Workspace pulumi.StringPtrInput
	// Provider prefix URL for Workspace
	WorkspaceProviderPrefix pulumi.StringPtrInput
}

func (ProviderArgs) ElementType() reflect.Type {
	return reflect.TypeOf((*providerArgs)(nil)).Elem()
}

type ProviderInput interface {
	pulumi.Input

	ToProviderOutput() ProviderOutput
	ToProviderOutputWithContext(ctx context.Context) ProviderOutput
}

func (*Provider) ElementType() reflect.Type {
	return reflect.TypeOf((**Provider)(nil)).Elem()
}

func (i *Provider) ToProviderOutput() ProviderOutput {
	return i.ToProviderOutputWithContext(context.Background())
}

func (i *Provider) ToProviderOutputWithContext(ctx context.Context) ProviderOutput {
	return pulumi.ToOutputWithContext(ctx, i).(ProviderOutput)
}

type ProviderOutput struct{ *pulumi.OutputState }

func (ProviderOutput) ElementType() reflect.Type {
	return reflect.TypeOf((**Provider)(nil)).Elem()
}

func (o ProviderOutput) ToProviderOutput() ProviderOutput {
	return o
}

func (o ProviderOutput) ToProviderOutputWithContext(ctx context.Context) ProviderOutput {
	return o
}

// Provider prefix URL for Activity Log
func (o ProviderOutput) ActivityLogProviderPrefix() pulumi.StringOutput {
	return o.ApplyT(func(v *Provider) pulumi.StringOutput { return v.ActivityLogProviderPrefix }).(pulumi.StringOutput)
}

// AuthToken is the bearer token that is attached to API calls.
func (o ProviderOutput) AuthToken() pulumi.StringPtrOutput {
	return o.ApplyT(func(v *Provider) pulumi.StringPtrOutput { return v.AuthToken }).(pulumi.StringPtrOutput)
}

// Provider prefix URL for Authorization
func (o ProviderOutput) AuthorizationProviderPrefix() pulumi.StringOutput {
	return o.ApplyT(func(v *Provider) pulumi.StringOutput { return v.AuthorizationProviderPrefix }).(pulumi.StringOutput)
}

// BaseURL defines the server url for API communication.
func (o ProviderOutput) BaseURL() pulumi.StringOutput {
	return o.ApplyT(func(v *Provider) pulumi.StringOutput { return v.BaseURL }).(pulumi.StringOutput)
}

// Provider prefix URL for Compute
func (o ProviderOutput) ComputeProviderPrefix() pulumi.StringOutput {
	return o.ApplyT(func(v *Provider) pulumi.StringOutput { return v.ComputeProviderPrefix }).(pulumi.StringOutput)
}

// Provider prefix URL for Kubernetes
func (o ProviderOutput) KubernetesProviderPrefix() pulumi.StringOutput {
	return o.ApplyT(func(v *Provider) pulumi.StringOutput { return v.KubernetesProviderPrefix }).(pulumi.StringOutput)
}

// Provider prefix URL for Load Balancer
func (o ProviderOutput) LoadBalancerProviderPrefix() pulumi.StringOutput {
	return o.ApplyT(func(v *Provider) pulumi.StringOutput { return v.LoadBalancerProviderPrefix }).(pulumi.StringOutput)
}

// Provider prefix URL for NAT Gateway
func (o ProviderOutput) NATGatewayProviderPrefix() pulumi.StringOutput {
	return o.ApplyT(func(v *Provider) pulumi.StringOutput { return v.NATGatewayProviderPrefix }).(pulumi.StringOutput)
}

// Provider prefix URL for Network
func (o ProviderOutput) NetworkProviderPrefix() pulumi.StringOutput {
	return o.ApplyT(func(v *Provider) pulumi.StringOutput { return v.NetworkProviderPrefix }).(pulumi.StringOutput)
}

// Provider prefix URL for Object Storage
func (o ProviderOutput) ObjectStorageProviderPrefix() pulumi.StringOutput {
	return o.ApplyT(func(v *Provider) pulumi.StringOutput { return v.ObjectStorageProviderPrefix }).(pulumi.StringOutput)
}

// Provider prefix URL for Regions
func (o ProviderOutput) RegionsProviderPrefix() pulumi.StringOutput {
	return o.ApplyT(func(v *Provider) pulumi.StringOutput { return v.RegionsProviderPrefix }).(pulumi.StringOutput)
}

// Provider prefix URL for Storage
func (o ProviderOutput) StorageProviderPrefix() pulumi.StringOutput {
	return o.ApplyT(func(v *Provider) pulumi.StringOutput { return v.StorageProviderPrefix }).(pulumi.StringOutput)
}

// Tenant defines the default tenant used for all API calls. May be overwritten in specific calls.
func (o ProviderOutput) Tenant() pulumi.StringOutput {
	return o.ApplyT(func(v *Provider) pulumi.StringOutput { return v.Tenant }).(pulumi.StringOutput)
}

// Workspace defines a default workspace for all API calls. Can be omitted and given to all objects, or specifically overwritten for calls.
func (o ProviderOutput) Workspace() pulumi.StringPtrOutput {
	return o.ApplyT(func(v *Provider) pulumi.StringPtrOutput { return v.Workspace }).(pulumi.StringPtrOutput)
}

// Provider prefix URL for Workspace
func (o ProviderOutput) WorkspaceProviderPrefix() pulumi.StringOutput {
	return o.ApplyT(func(v *Provider) pulumi.StringOutput { return v.WorkspaceProviderPrefix }).(pulumi.StringOutput)
}

func init() {
	pulumi.RegisterInputType(reflect.TypeOf((*ProviderInput)(nil)).Elem(), &Provider{})
	pulumi.RegisterOutputType(ProviderOutput{})
}
