// *** WARNING: this file was generated by pulumi-language-java. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

package com.pulumi.cape.compute;

import com.pulumi.cape.Utilities;
import com.pulumi.cape.compute.InstanceArgs;
import com.pulumi.cape.schemas.outputs.InstanceSpec;
import com.pulumi.cape.schemas.outputs.InstanceStatus;
import com.pulumi.cape.schemas.outputs.RegionalWorkspaceResourceMetadata;
import com.pulumi.core.Output;
import com.pulumi.core.annotations.Export;
import com.pulumi.core.annotations.ResourceType;
import com.pulumi.core.internal.Codegen;
import java.lang.String;
import java.util.Map;
import java.util.Optional;
import javax.annotation.Nullable;

/**
 * Instance resource representing a virtual machine in the cloud provider&#39;s infrastructure. This resource is used to manage the lifecycle of the instance, including its creation, updates, and deletion.
 * 
 */
@ResourceType(type="cape:compute:Instance")
public class Instance extends com.pulumi.resources.CustomResource {
    /**
     * User-defined key/value pairs that are mutable and can be used to add annotations. The number of annotations is eventually limited by the CSP.
     * 
     */
    @Export(name="annotations", refs={Map.class,String.class}, tree="[0,1,1]")
    private Output</* @Nullable */ Map<String,String>> annotations;

    /**
     * @return User-defined key/value pairs that are mutable and can be used to add annotations. The number of annotations is eventually limited by the CSP.
     * 
     */
    public Output<Optional<Map<String,String>>> annotations() {
        return Codegen.optional(this.annotations);
    }
    /**
     * User-defined key/value pairs that are mutable and can be used to add extensions. Extensions are subject to validation by the CSP, and any value that is not accepted will be rejected during admission.
     * 
     */
    @Export(name="extensions", refs={Map.class,String.class}, tree="[0,1,1]")
    private Output</* @Nullable */ Map<String,String>> extensions;

    /**
     * @return User-defined key/value pairs that are mutable and can be used to add extensions. Extensions are subject to validation by the CSP, and any value that is not accepted will be rejected during admission.
     * 
     */
    public Output<Optional<Map<String,String>>> extensions() {
        return Codegen.optional(this.extensions);
    }
    /**
     * User-defined key/value pairs that are mutable and can be used to organize and categorize resources. They can be used to filter resources. The number of labels is eventually limited by the CSP.
     * 
     */
    @Export(name="labels", refs={Map.class,String.class}, tree="[0,1,1]")
    private Output</* @Nullable */ Map<String,String>> labels;

    /**
     * @return User-defined key/value pairs that are mutable and can be used to organize and categorize resources. They can be used to filter resources. The number of labels is eventually limited by the CSP.
     * 
     */
    public Output<Optional<Map<String,String>>> labels() {
        return Codegen.optional(this.labels);
    }
    /**
     * Metadata for regional resources with name, permission, modification, type, tenant and workspace and region information.
     * 
     */
    @Export(name="metadata", refs={RegionalWorkspaceResourceMetadata.class}, tree="[0]")
    private Output<RegionalWorkspaceResourceMetadata> metadata;

    /**
     * @return Metadata for regional resources with name, permission, modification, type, tenant and workspace and region information.
     * 
     */
    public Output<RegionalWorkspaceResourceMetadata> metadata() {
        return this.metadata;
    }
    /**
     * Specification of the instance, including its SKU, network configuration, and storage options.
     * 
     */
    @Export(name="spec", refs={InstanceSpec.class}, tree="[0]")
    private Output<InstanceSpec> spec;

    /**
     * @return Specification of the instance, including its SKU, network configuration, and storage options.
     * 
     */
    public Output<InstanceSpec> spec() {
        return this.spec;
    }
    /**
     * Current status of the instance.
     * 
     */
    @Export(name="status", refs={InstanceStatus.class}, tree="[0]")
    private Output<InstanceStatus> status;

    /**
     * @return Current status of the instance.
     * 
     */
    public Output<InstanceStatus> status() {
        return this.status;
    }
    /**
     * The tenant for the resource. If omitted, the provider default is used.
     * 
     */
    @Export(name="tenant", refs={String.class}, tree="[0]")
    private Output</* @Nullable */ String> tenant;

    /**
     * @return The tenant for the resource. If omitted, the provider default is used.
     * 
     */
    public Output<Optional<String>> tenant() {
        return Codegen.optional(this.tenant);
    }
    /**
     * The workspace for the resource. If omitted, the provider default is used. Must be configured by either means.
     * 
     */
    @Export(name="workspace", refs={String.class}, tree="[0]")
    private Output</* @Nullable */ String> workspace;

    /**
     * @return The workspace for the resource. If omitted, the provider default is used. Must be configured by either means.
     * 
     */
    public Output<Optional<String>> workspace() {
        return Codegen.optional(this.workspace);
    }

    /**
     *
     * @param name The _unique_ name of the resulting resource.
     */
    public Instance(java.lang.String name) {
        this(name, InstanceArgs.Empty);
    }
    /**
     *
     * @param name The _unique_ name of the resulting resource.
     * @param args The arguments to use to populate this resource's properties.
     */
    public Instance(java.lang.String name, InstanceArgs args) {
        this(name, args, null);
    }
    /**
     *
     * @param name The _unique_ name of the resulting resource.
     * @param args The arguments to use to populate this resource's properties.
     * @param options A bag of options that control this resource's behavior.
     */
    public Instance(java.lang.String name, InstanceArgs args, @Nullable com.pulumi.resources.CustomResourceOptions options) {
        super("cape:compute:Instance", name, makeArgs(args, options), makeResourceOptions(options, Codegen.empty()), false);
    }

    private Instance(java.lang.String name, Output<java.lang.String> id, @Nullable com.pulumi.resources.CustomResourceOptions options) {
        super("cape:compute:Instance", name, null, makeResourceOptions(options, id), false);
    }

    private static InstanceArgs makeArgs(InstanceArgs args, @Nullable com.pulumi.resources.CustomResourceOptions options) {
        if (options != null && options.getUrn().isPresent()) {
            return null;
        }
        return args == null ? InstanceArgs.Empty : args;
    }

    private static com.pulumi.resources.CustomResourceOptions makeResourceOptions(@Nullable com.pulumi.resources.CustomResourceOptions options, @Nullable Output<java.lang.String> id) {
        var defaultOptions = com.pulumi.resources.CustomResourceOptions.builder()
            .version(Utilities.getVersion())
            .build();
        return com.pulumi.resources.CustomResourceOptions.merge(defaultOptions, options, id);
    }

    /**
     * Get an existing Host resource's state with the given name, ID, and optional extra
     * properties used to qualify the lookup.
     *
     * @param name The _unique_ name of the resulting resource.
     * @param id The _unique_ provider ID of the resource to lookup.
     * @param options Optional settings to control the behavior of the CustomResource.
     */
    public static Instance get(java.lang.String name, Output<java.lang.String> id, @Nullable com.pulumi.resources.CustomResourceOptions options) {
        return new Instance(name, id, options);
    }
}
