// *** WARNING: this file was generated by pulumi-language-java. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

package com.pulumi.cape.schemas.inputs;

import com.pulumi.core.Output;
import com.pulumi.core.annotations.Import;
import java.lang.String;
import java.util.Objects;
import java.util.Optional;
import javax.annotation.Nullable;


/**
 * Combined IPv4 and IPv6 CIDR block for a subnet. Depending on the network configuration, either the IPv4 or IPv6 range can be omitted. So the following combinations are possible: * IPv4 only * IPv6 only * IPv4 and IPv6 (Dual Stack)
 * 
 */
public final class CidrArgs extends com.pulumi.resources.ResourceArgs {

    public static final CidrArgs Empty = new CidrArgs();

    /**
     * IPv4 CIDR block for the subnet.
     * 
     */
    @Import(name="ipv4")
    private @Nullable Output<String> ipv4;

    /**
     * @return IPv4 CIDR block for the subnet.
     * 
     */
    public Optional<Output<String>> ipv4() {
        return Optional.ofNullable(this.ipv4);
    }

    /**
     * IPv6 CIDR block for the subnet.
     * 
     */
    @Import(name="ipv6")
    private @Nullable Output<String> ipv6;

    /**
     * @return IPv6 CIDR block for the subnet.
     * 
     */
    public Optional<Output<String>> ipv6() {
        return Optional.ofNullable(this.ipv6);
    }

    private CidrArgs() {}

    private CidrArgs(CidrArgs $) {
        this.ipv4 = $.ipv4;
        this.ipv6 = $.ipv6;
    }

    public static Builder builder() {
        return new Builder();
    }
    public static Builder builder(CidrArgs defaults) {
        return new Builder(defaults);
    }

    public static final class Builder {
        private CidrArgs $;

        public Builder() {
            $ = new CidrArgs();
        }

        public Builder(CidrArgs defaults) {
            $ = new CidrArgs(Objects.requireNonNull(defaults));
        }

        /**
         * @param ipv4 IPv4 CIDR block for the subnet.
         * 
         * @return builder
         * 
         */
        public Builder ipv4(@Nullable Output<String> ipv4) {
            $.ipv4 = ipv4;
            return this;
        }

        /**
         * @param ipv4 IPv4 CIDR block for the subnet.
         * 
         * @return builder
         * 
         */
        public Builder ipv4(String ipv4) {
            return ipv4(Output.of(ipv4));
        }

        /**
         * @param ipv6 IPv6 CIDR block for the subnet.
         * 
         * @return builder
         * 
         */
        public Builder ipv6(@Nullable Output<String> ipv6) {
            $.ipv6 = ipv6;
            return this;
        }

        /**
         * @param ipv6 IPv6 CIDR block for the subnet.
         * 
         * @return builder
         * 
         */
        public Builder ipv6(String ipv6) {
            return ipv6(Output.of(ipv6));
        }

        public CidrArgs build() {
            return $;
        }
    }

}
