// *** WARNING: this file was generated by pulumi-language-java. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

package com.pulumi.cape.schemas.inputs;

import com.pulumi.core.Output;
import com.pulumi.core.annotations.Import;
import com.pulumi.exceptions.MissingRequiredPropertyException;
import java.lang.String;
import java.util.Objects;


/**
 * Represents a taint applied to the nodes in the node pool. Taints are used to control which pods can be scheduled on the nodes. A taint consists of a key, value, and effect.
 * 
 */
public final class KubernetesNodeTaintArgs extends com.pulumi.resources.ResourceArgs {

    public static final KubernetesNodeTaintArgs Empty = new KubernetesNodeTaintArgs();

    /**
     * The effect of the taint. The effect determines how the taint is applied to the nodes in the node pool. For details on the effects, see the (kubernetes documentation on taints and tolerations)[https://kubernetes.io/docs/concepts/scheduling-eviction/taint-and-toleration/].
     * 
     */
    @Import(name="effect", required=true)
    private Output<String> effect;

    /**
     * @return The effect of the taint. The effect determines how the taint is applied to the nodes in the node pool. For details on the effects, see the (kubernetes documentation on taints and tolerations)[https://kubernetes.io/docs/concepts/scheduling-eviction/taint-and-toleration/].
     * 
     */
    public Output<String> effect() {
        return this.effect;
    }

    /**
     * The key of the taint. The key is used to identify the taint and is used in conjunction with the value and effect.
     * 
     */
    @Import(name="key", required=true)
    private Output<String> key;

    /**
     * @return The key of the taint. The key is used to identify the taint and is used in conjunction with the value and effect.
     * 
     */
    public Output<String> key() {
        return this.key;
    }

    /**
     * The value of the taint. The value is used to identify the taint and is used in conjunction with the key and effect.
     * 
     */
    @Import(name="value", required=true)
    private Output<String> value;

    /**
     * @return The value of the taint. The value is used to identify the taint and is used in conjunction with the key and effect.
     * 
     */
    public Output<String> value() {
        return this.value;
    }

    private KubernetesNodeTaintArgs() {}

    private KubernetesNodeTaintArgs(KubernetesNodeTaintArgs $) {
        this.effect = $.effect;
        this.key = $.key;
        this.value = $.value;
    }

    public static Builder builder() {
        return new Builder();
    }
    public static Builder builder(KubernetesNodeTaintArgs defaults) {
        return new Builder(defaults);
    }

    public static final class Builder {
        private KubernetesNodeTaintArgs $;

        public Builder() {
            $ = new KubernetesNodeTaintArgs();
        }

        public Builder(KubernetesNodeTaintArgs defaults) {
            $ = new KubernetesNodeTaintArgs(Objects.requireNonNull(defaults));
        }

        /**
         * @param effect The effect of the taint. The effect determines how the taint is applied to the nodes in the node pool. For details on the effects, see the (kubernetes documentation on taints and tolerations)[https://kubernetes.io/docs/concepts/scheduling-eviction/taint-and-toleration/].
         * 
         * @return builder
         * 
         */
        public Builder effect(Output<String> effect) {
            $.effect = effect;
            return this;
        }

        /**
         * @param effect The effect of the taint. The effect determines how the taint is applied to the nodes in the node pool. For details on the effects, see the (kubernetes documentation on taints and tolerations)[https://kubernetes.io/docs/concepts/scheduling-eviction/taint-and-toleration/].
         * 
         * @return builder
         * 
         */
        public Builder effect(String effect) {
            return effect(Output.of(effect));
        }

        /**
         * @param key The key of the taint. The key is used to identify the taint and is used in conjunction with the value and effect.
         * 
         * @return builder
         * 
         */
        public Builder key(Output<String> key) {
            $.key = key;
            return this;
        }

        /**
         * @param key The key of the taint. The key is used to identify the taint and is used in conjunction with the value and effect.
         * 
         * @return builder
         * 
         */
        public Builder key(String key) {
            return key(Output.of(key));
        }

        /**
         * @param value The value of the taint. The value is used to identify the taint and is used in conjunction with the key and effect.
         * 
         * @return builder
         * 
         */
        public Builder value(Output<String> value) {
            $.value = value;
            return this;
        }

        /**
         * @param value The value of the taint. The value is used to identify the taint and is used in conjunction with the key and effect.
         * 
         * @return builder
         * 
         */
        public Builder value(String value) {
            return value(Output.of(value));
        }

        public KubernetesNodeTaintArgs build() {
            if ($.effect == null) {
                throw new MissingRequiredPropertyException("KubernetesNodeTaintArgs", "effect");
            }
            if ($.key == null) {
                throw new MissingRequiredPropertyException("KubernetesNodeTaintArgs", "key");
            }
            if ($.value == null) {
                throw new MissingRequiredPropertyException("KubernetesNodeTaintArgs", "value");
            }
            return $;
        }
    }

}
