// *** WARNING: this file was generated by pulumi-language-java. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

package com.pulumi.cape.schemas.inputs;

import com.pulumi.cape.schemas.inputs.KubernetesNodeRootVolumeArgs;
import com.pulumi.cape.schemas.inputs.ReferenceArgs;
import com.pulumi.core.Output;
import com.pulumi.core.annotations.Import;
import com.pulumi.exceptions.MissingRequiredPropertyException;
import java.lang.String;
import java.util.Objects;
import java.util.Optional;
import javax.annotation.Nullable;


/**
 * Template for creating nodes in the node pool. The template includes the instance SKU, subnet, and zone in which the nodes will be created. The SKU must be one of the available compute SKUs in the region.
 * 
 */
public final class KubernetesNodeTemplateArgs extends com.pulumi.resources.ResourceArgs {

    public static final KubernetesNodeTemplateArgs Empty = new KubernetesNodeTemplateArgs();

    /**
     * Root volume for the node. The root volume is used to store the operating system and other software required to run the node. The SKU must be one of the available block storage SKUs in the region.
     * 
     */
    @Import(name="rootVolume", required=true)
    private Output<KubernetesNodeRootVolumeArgs> rootVolume;

    /**
     * @return Root volume for the node. The root volume is used to store the operating system and other software required to run the node. The SKU must be one of the available block storage SKUs in the region.
     * 
     */
    public Output<KubernetesNodeRootVolumeArgs> rootVolume() {
        return this.rootVolume;
    }

    /**
     * Reference to the security group associated with the node instances.
     * 
     */
    @Import(name="securityGroupRef")
    private @Nullable Output<ReferenceArgs> securityGroupRef;

    /**
     * @return Reference to the security group associated with the node instances.
     * 
     */
    public Optional<Output<ReferenceArgs>> securityGroupRef() {
        return Optional.ofNullable(this.securityGroupRef);
    }

    /**
     * Reference to the SKU of the node instances. The SKU is immutable after the node pool is created. To change the SKU, the node pool must be deleted and recreated with the new SKU reference.
     * 
     */
    @Import(name="skuRef", required=true)
    private Output<ReferenceArgs> skuRef;

    /**
     * @return Reference to the SKU of the node instances. The SKU is immutable after the node pool is created. To change the SKU, the node pool must be deleted and recreated with the new SKU reference.
     * 
     */
    public Output<ReferenceArgs> skuRef() {
        return this.skuRef;
    }

    /**
     * Reference to the NIC attached to the node instances.
     * 
     */
    @Import(name="subnetRef", required=true)
    private Output<ReferenceArgs> subnetRef;

    /**
     * @return Reference to the NIC attached to the node instances.
     * 
     */
    public Output<ReferenceArgs> subnetRef() {
        return this.subnetRef;
    }

    /**
     * The zone in which the node instances will be created. The zone is immutable after the node pool is created. To change the zone, the node pool must be deleted and recreated with the new zone.
     * 
     */
    @Import(name="zone", required=true)
    private Output<String> zone;

    /**
     * @return The zone in which the node instances will be created. The zone is immutable after the node pool is created. To change the zone, the node pool must be deleted and recreated with the new zone.
     * 
     */
    public Output<String> zone() {
        return this.zone;
    }

    private KubernetesNodeTemplateArgs() {}

    private KubernetesNodeTemplateArgs(KubernetesNodeTemplateArgs $) {
        this.rootVolume = $.rootVolume;
        this.securityGroupRef = $.securityGroupRef;
        this.skuRef = $.skuRef;
        this.subnetRef = $.subnetRef;
        this.zone = $.zone;
    }

    public static Builder builder() {
        return new Builder();
    }
    public static Builder builder(KubernetesNodeTemplateArgs defaults) {
        return new Builder(defaults);
    }

    public static final class Builder {
        private KubernetesNodeTemplateArgs $;

        public Builder() {
            $ = new KubernetesNodeTemplateArgs();
        }

        public Builder(KubernetesNodeTemplateArgs defaults) {
            $ = new KubernetesNodeTemplateArgs(Objects.requireNonNull(defaults));
        }

        /**
         * @param rootVolume Root volume for the node. The root volume is used to store the operating system and other software required to run the node. The SKU must be one of the available block storage SKUs in the region.
         * 
         * @return builder
         * 
         */
        public Builder rootVolume(Output<KubernetesNodeRootVolumeArgs> rootVolume) {
            $.rootVolume = rootVolume;
            return this;
        }

        /**
         * @param rootVolume Root volume for the node. The root volume is used to store the operating system and other software required to run the node. The SKU must be one of the available block storage SKUs in the region.
         * 
         * @return builder
         * 
         */
        public Builder rootVolume(KubernetesNodeRootVolumeArgs rootVolume) {
            return rootVolume(Output.of(rootVolume));
        }

        /**
         * @param securityGroupRef Reference to the security group associated with the node instances.
         * 
         * @return builder
         * 
         */
        public Builder securityGroupRef(@Nullable Output<ReferenceArgs> securityGroupRef) {
            $.securityGroupRef = securityGroupRef;
            return this;
        }

        /**
         * @param securityGroupRef Reference to the security group associated with the node instances.
         * 
         * @return builder
         * 
         */
        public Builder securityGroupRef(ReferenceArgs securityGroupRef) {
            return securityGroupRef(Output.of(securityGroupRef));
        }

        /**
         * @param skuRef Reference to the SKU of the node instances. The SKU is immutable after the node pool is created. To change the SKU, the node pool must be deleted and recreated with the new SKU reference.
         * 
         * @return builder
         * 
         */
        public Builder skuRef(Output<ReferenceArgs> skuRef) {
            $.skuRef = skuRef;
            return this;
        }

        /**
         * @param skuRef Reference to the SKU of the node instances. The SKU is immutable after the node pool is created. To change the SKU, the node pool must be deleted and recreated with the new SKU reference.
         * 
         * @return builder
         * 
         */
        public Builder skuRef(ReferenceArgs skuRef) {
            return skuRef(Output.of(skuRef));
        }

        /**
         * @param subnetRef Reference to the NIC attached to the node instances.
         * 
         * @return builder
         * 
         */
        public Builder subnetRef(Output<ReferenceArgs> subnetRef) {
            $.subnetRef = subnetRef;
            return this;
        }

        /**
         * @param subnetRef Reference to the NIC attached to the node instances.
         * 
         * @return builder
         * 
         */
        public Builder subnetRef(ReferenceArgs subnetRef) {
            return subnetRef(Output.of(subnetRef));
        }

        /**
         * @param zone The zone in which the node instances will be created. The zone is immutable after the node pool is created. To change the zone, the node pool must be deleted and recreated with the new zone.
         * 
         * @return builder
         * 
         */
        public Builder zone(Output<String> zone) {
            $.zone = zone;
            return this;
        }

        /**
         * @param zone The zone in which the node instances will be created. The zone is immutable after the node pool is created. To change the zone, the node pool must be deleted and recreated with the new zone.
         * 
         * @return builder
         * 
         */
        public Builder zone(String zone) {
            return zone(Output.of(zone));
        }

        public KubernetesNodeTemplateArgs build() {
            if ($.rootVolume == null) {
                throw new MissingRequiredPropertyException("KubernetesNodeTemplateArgs", "rootVolume");
            }
            if ($.skuRef == null) {
                throw new MissingRequiredPropertyException("KubernetesNodeTemplateArgs", "skuRef");
            }
            if ($.subnetRef == null) {
                throw new MissingRequiredPropertyException("KubernetesNodeTemplateArgs", "subnetRef");
            }
            if ($.zone == null) {
                throw new MissingRequiredPropertyException("KubernetesNodeTemplateArgs", "zone");
            }
            return $;
        }
    }

}
