// *** WARNING: this file was generated by pulumi-language-java. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

package com.pulumi.cape.schemas.inputs;

import com.pulumi.cape.schemas.inputs.LoadBalancerHealthCheckArgs;
import com.pulumi.cape.schemas.inputs.ReferenceArgs;
import com.pulumi.core.Output;
import com.pulumi.core.annotations.Import;
import com.pulumi.core.internal.Codegen;
import com.pulumi.exceptions.MissingRequiredPropertyException;
import java.lang.Integer;
import java.lang.String;
import java.util.List;
import java.util.Objects;
import java.util.Optional;
import javax.annotation.Nullable;


/**
 * The target of the LoadBalancer. It can be a set of instances nics. The port can be different from the frontend port, if omitted it will be the same. If no health check is specified, the LoadBalancer will not check the health of the backend instances.
 * 
 */
public final class LoadBalancerTargetArgs extends com.pulumi.resources.ResourceArgs {

    public static final LoadBalancerTargetArgs Empty = new LoadBalancerTargetArgs();

    /**
     * LoadBalancer algorithm to take a backend instance
     * 
     */
    @Import(name="algorithm")
    private @Nullable Output<String> algorithm;

    /**
     * @return LoadBalancer algorithm to take a backend instance
     * 
     */
    public Optional<Output<String>> algorithm() {
        return Optional.ofNullable(this.algorithm);
    }

    /**
     * Optional port health check. It probes the port with protocol.
     * 
     */
    @Import(name="healthCheck")
    private @Nullable Output<LoadBalancerHealthCheckArgs> healthCheck;

    /**
     * @return Optional port health check. It probes the port with protocol.
     * 
     */
    public Optional<Output<LoadBalancerHealthCheckArgs>> healthCheck() {
        return Optional.ofNullable(this.healthCheck);
    }

    /**
     * Nic reference to the members as part of the LoadBalancerTarget
     * 
     */
    @Import(name="members", required=true)
    private Output<List<ReferenceArgs>> members;

    /**
     * @return Nic reference to the members as part of the LoadBalancerTarget
     * 
     */
    public Output<List<ReferenceArgs>> members() {
        return this.members;
    }

    /**
     * Backend port to which the load balancer will be forwarding the traffic to
     * 
     */
    @Import(name="port")
    private @Nullable Output<Integer> port;

    /**
     * @return Backend port to which the load balancer will be forwarding the traffic to
     * 
     */
    public Optional<Output<Integer>> port() {
        return Optional.ofNullable(this.port);
    }

    /**
     * Specifies the proxy protocol version. The proxy protocol is used to pass client connection information to the backend instances. If not specified, the default is `none`.
     * 
     */
    @Import(name="proxyProtocol")
    private @Nullable Output<String> proxyProtocol;

    /**
     * @return Specifies the proxy protocol version. The proxy protocol is used to pass client connection information to the backend instances. If not specified, the default is `none`.
     * 
     */
    public Optional<Output<String>> proxyProtocol() {
        return Optional.ofNullable(this.proxyProtocol);
    }

    private LoadBalancerTargetArgs() {}

    private LoadBalancerTargetArgs(LoadBalancerTargetArgs $) {
        this.algorithm = $.algorithm;
        this.healthCheck = $.healthCheck;
        this.members = $.members;
        this.port = $.port;
        this.proxyProtocol = $.proxyProtocol;
    }

    public static Builder builder() {
        return new Builder();
    }
    public static Builder builder(LoadBalancerTargetArgs defaults) {
        return new Builder(defaults);
    }

    public static final class Builder {
        private LoadBalancerTargetArgs $;

        public Builder() {
            $ = new LoadBalancerTargetArgs();
        }

        public Builder(LoadBalancerTargetArgs defaults) {
            $ = new LoadBalancerTargetArgs(Objects.requireNonNull(defaults));
        }

        /**
         * @param algorithm LoadBalancer algorithm to take a backend instance
         * 
         * @return builder
         * 
         */
        public Builder algorithm(@Nullable Output<String> algorithm) {
            $.algorithm = algorithm;
            return this;
        }

        /**
         * @param algorithm LoadBalancer algorithm to take a backend instance
         * 
         * @return builder
         * 
         */
        public Builder algorithm(String algorithm) {
            return algorithm(Output.of(algorithm));
        }

        /**
         * @param healthCheck Optional port health check. It probes the port with protocol.
         * 
         * @return builder
         * 
         */
        public Builder healthCheck(@Nullable Output<LoadBalancerHealthCheckArgs> healthCheck) {
            $.healthCheck = healthCheck;
            return this;
        }

        /**
         * @param healthCheck Optional port health check. It probes the port with protocol.
         * 
         * @return builder
         * 
         */
        public Builder healthCheck(LoadBalancerHealthCheckArgs healthCheck) {
            return healthCheck(Output.of(healthCheck));
        }

        /**
         * @param members Nic reference to the members as part of the LoadBalancerTarget
         * 
         * @return builder
         * 
         */
        public Builder members(Output<List<ReferenceArgs>> members) {
            $.members = members;
            return this;
        }

        /**
         * @param members Nic reference to the members as part of the LoadBalancerTarget
         * 
         * @return builder
         * 
         */
        public Builder members(List<ReferenceArgs> members) {
            return members(Output.of(members));
        }

        /**
         * @param members Nic reference to the members as part of the LoadBalancerTarget
         * 
         * @return builder
         * 
         */
        public Builder members(ReferenceArgs... members) {
            return members(List.of(members));
        }

        /**
         * @param port Backend port to which the load balancer will be forwarding the traffic to
         * 
         * @return builder
         * 
         */
        public Builder port(@Nullable Output<Integer> port) {
            $.port = port;
            return this;
        }

        /**
         * @param port Backend port to which the load balancer will be forwarding the traffic to
         * 
         * @return builder
         * 
         */
        public Builder port(Integer port) {
            return port(Output.of(port));
        }

        /**
         * @param proxyProtocol Specifies the proxy protocol version. The proxy protocol is used to pass client connection information to the backend instances. If not specified, the default is `none`.
         * 
         * @return builder
         * 
         */
        public Builder proxyProtocol(@Nullable Output<String> proxyProtocol) {
            $.proxyProtocol = proxyProtocol;
            return this;
        }

        /**
         * @param proxyProtocol Specifies the proxy protocol version. The proxy protocol is used to pass client connection information to the backend instances. If not specified, the default is `none`.
         * 
         * @return builder
         * 
         */
        public Builder proxyProtocol(String proxyProtocol) {
            return proxyProtocol(Output.of(proxyProtocol));
        }

        public LoadBalancerTargetArgs build() {
            $.algorithm = Codegen.stringProp("algorithm").output().arg($.algorithm).def("round-robin").getNullable();
            if ($.members == null) {
                throw new MissingRequiredPropertyException("LoadBalancerTargetArgs", "members");
            }
            $.proxyProtocol = Codegen.stringProp("proxyProtocol").output().arg($.proxyProtocol).def("none").getNullable();
            return $;
        }
    }

}
