// *** WARNING: this file was generated by pulumi-language-nodejs. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from "@pulumi/pulumi";
import * as inputs from "../types/input";
import * as outputs from "../types/output";
import * as utilities from "../utilities";

/**
 * An object storage account resource, which includes metadata, specification, and status.
 */
export class ObjectStorageAccount extends pulumi.CustomResource {
    /**
     * Get an existing ObjectStorageAccount resource's state with the given name, ID, and optional extra
     * properties used to qualify the lookup.
     *
     * @param name The _unique_ name of the resulting resource.
     * @param id The _unique_ provider ID of the resource to lookup.
     * @param opts Optional settings to control the behavior of the CustomResource.
     */
    public static get(name: string, id: pulumi.Input<pulumi.ID>, opts?: pulumi.CustomResourceOptions): ObjectStorageAccount {
        return new ObjectStorageAccount(name, undefined as any, { ...opts, id: id });
    }

    /** @internal */
    public static readonly __pulumiType = 'cape:objectstorage:ObjectStorageAccount';

    /**
     * Returns true if the given object is an instance of ObjectStorageAccount.  This is designed to work even
     * when multiple copies of the Pulumi SDK have been loaded into the same process.
     */
    public static isInstance(obj: any): obj is ObjectStorageAccount {
        if (obj === undefined || obj === null) {
            return false;
        }
        return obj['__pulumiType'] === ObjectStorageAccount.__pulumiType;
    }

    /**
     * User-defined key/value pairs that are mutable and can be used to add annotations. The number of annotations is eventually limited by the CSP.
     */
    declare public readonly annotations: pulumi.Output<{[key: string]: string} | undefined>;
    /**
     * User-defined key/value pairs that are mutable and can be used to add extensions. Extensions are subject to validation by the CSP, and any value that is not accepted will be rejected during admission.
     */
    declare public readonly extensions: pulumi.Output<{[key: string]: string} | undefined>;
    /**
     * User-defined key/value pairs that are mutable and can be used to organize and categorize resources. They can be used to filter resources. The number of labels is eventually limited by the CSP.
     */
    declare public readonly labels: pulumi.Output<{[key: string]: string} | undefined>;
    /**
     * Metadata for global resources with name, permission, modification, type, and tenant information.
     */
    declare public /*out*/ readonly metadata: pulumi.Output<outputs.schemas.GlobalTenantResourceMetadata>;
    /**
     * The specification of an object storage account, including the region and zone.
     */
    declare public readonly spec: pulumi.Output<{[key: string]: any}>;
    /**
     * The status of an object storage account, including the access key, secret key, and canonical user ID.
     */
    declare public /*out*/ readonly status: pulumi.Output<outputs.schemas.ObjectStorageAccountStatus>;
    /**
     * The tenant for the resource. If omitted, the provider default is used.
     */
    declare public readonly tenant: pulumi.Output<string | undefined>;

    /**
     * Create a ObjectStorageAccount resource with the given unique name, arguments, and options.
     *
     * @param name The _unique_ name of the resource.
     * @param args The arguments to use to populate this resource's properties.
     * @param opts A bag of options that control this resource's behavior.
     */
    constructor(name: string, args: ObjectStorageAccountArgs, opts?: pulumi.CustomResourceOptions) {
        let resourceInputs: pulumi.Inputs = {};
        opts = opts || {};
        if (!opts.id) {
            if (args?.spec === undefined && !opts.urn) {
                throw new Error("Missing required property 'spec'");
            }
            resourceInputs["annotations"] = args?.annotations;
            resourceInputs["extensions"] = args?.extensions;
            resourceInputs["labels"] = args?.labels;
            resourceInputs["spec"] = args?.spec;
            resourceInputs["tenant"] = args?.tenant;
            resourceInputs["metadata"] = undefined /*out*/;
            resourceInputs["status"] = undefined /*out*/;
        } else {
            resourceInputs["annotations"] = undefined /*out*/;
            resourceInputs["extensions"] = undefined /*out*/;
            resourceInputs["labels"] = undefined /*out*/;
            resourceInputs["metadata"] = undefined /*out*/;
            resourceInputs["spec"] = undefined /*out*/;
            resourceInputs["status"] = undefined /*out*/;
            resourceInputs["tenant"] = undefined /*out*/;
        }
        opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts);
        super(ObjectStorageAccount.__pulumiType, name, resourceInputs, opts);
    }
}

/**
 * The set of arguments for constructing a ObjectStorageAccount resource.
 */
export interface ObjectStorageAccountArgs {
    /**
     * User-defined key/value pairs that are mutable and can be used to add annotations. The number of annotations is eventually limited by the CSP.
     */
    annotations?: pulumi.Input<{[key: string]: pulumi.Input<string>} | undefined>;
    /**
     * User-defined key/value pairs that are mutable and can be used to add extensions. Extensions are subject to validation by the CSP, and any value that is not accepted will be rejected during admission.
     */
    extensions?: pulumi.Input<{[key: string]: pulumi.Input<string>} | undefined>;
    /**
     * User-defined key/value pairs that are mutable and can be used to organize and categorize resources. They can be used to filter resources. The number of labels is eventually limited by the CSP.
     */
    labels?: pulumi.Input<{[key: string]: pulumi.Input<string>} | undefined>;
    /**
     * The specification of an object storage account, including the region and zone.
     */
    spec: pulumi.Input<{[key: string]: any}>;
    /**
     * The tenant for the resource. If omitted, the provider default is used.
     */
    tenant?: pulumi.Input<string | undefined>;
}
