# coding=utf-8
# *** WARNING: this file was generated by pulumi-language-python. ***
# *** Do not edit by hand unless you're certain you know what you are doing! ***

import builtins as _builtins
import warnings
import sys
import pulumi
import pulumi.runtime
from typing import Any, Mapping, Optional, Sequence, Union, overload
if sys.version_info >= (3, 11):
    from typing import NotRequired, TypedDict, TypeAlias
else:
    from typing_extensions import NotRequired, TypedDict, TypeAlias
from .. import _utilities
from .. import schemas as _schemas

__all__ = ['NetworkArgs', 'Network']

@pulumi.input_type
class NetworkArgs:
    def __init__(__self__, *,
                 spec: pulumi.Input['_schemas.NetworkSpecArgs'],
                 annotations: pulumi.Input[Optional[Mapping[str, pulumi.Input[_builtins.str]]]] = None,
                 extensions: pulumi.Input[Optional[Mapping[str, pulumi.Input[_builtins.str]]]] = None,
                 labels: pulumi.Input[Optional[Mapping[str, pulumi.Input[_builtins.str]]]] = None,
                 tenant: pulumi.Input[Optional[_builtins.str]] = None,
                 workspace: pulumi.Input[Optional[_builtins.str]] = None):
        """
        The set of arguments for constructing a Network resource.

        :param pulumi.Input['_schemas.NetworkSpecArgs'] spec: A Network represents a virtual network that can be used to isolate resources. Key network concepts: * Defines a range of IP addresses for compute resources (e.g. instances) * Enables network segmentation and isolation * Provides common performance configuration across the network using a SKU The `cidr` is the base CIDR block for the network. Additional CIDR blocks can be added to the network using the `additionalCidrs` field. The `additionalCidrs` can be changed after the network is created in case they are not used. The main CIDR block cannot be changed after the network is created. All cidrs must be non-overlapping. The cidrs have to be part of the RFC 1918 address space in case of IPv4 and or RFC 4193. In case the system should automatically assign IP addresses to the network cidrs only the network prefix is required. E.g. to request a /16 IPv4 CIDR block the CIDR block would be `0.0.0.0/16` and for a /56 IPv6 CIDR block the CIDR block would be `::/56`. Most CSP will not allow to use a different IPv6 prefix length than /56. Route tables associated with this network automatically include local routes for all network CIDRs (including `additionalCidrs`). These network-local routes are present by default and cannot be removed.
        :param pulumi.Input[Mapping[str, pulumi.Input[_builtins.str]]] annotations: User-defined key/value pairs that are mutable and can be used to add annotations. The number of annotations is eventually limited by the CSP.
        :param pulumi.Input[Mapping[str, pulumi.Input[_builtins.str]]] extensions: User-defined key/value pairs that are mutable and can be used to add extensions. Extensions are subject to validation by the CSP, and any value that is not accepted will be rejected during admission.
        :param pulumi.Input[Mapping[str, pulumi.Input[_builtins.str]]] labels: User-defined key/value pairs that are mutable and can be used to organize and categorize resources. They can be used to filter resources. The number of labels is eventually limited by the CSP.
        :param pulumi.Input[_builtins.str] tenant: The tenant for the resource. If omitted, the provider default is used.
        :param pulumi.Input[_builtins.str] workspace: The workspace for the resource. If omitted, the provider default is used. Must be configured by either means.
        """
        pulumi.set(__self__, "spec", spec)
        if annotations is not None:
            pulumi.set(__self__, "annotations", annotations)
        if extensions is not None:
            pulumi.set(__self__, "extensions", extensions)
        if labels is not None:
            pulumi.set(__self__, "labels", labels)
        if tenant is not None:
            pulumi.set(__self__, "tenant", tenant)
        if workspace is not None:
            pulumi.set(__self__, "workspace", workspace)

    @_builtins.property
    @pulumi.getter
    def spec(self) -> pulumi.Input['_schemas.NetworkSpecArgs']:
        """
        A Network represents a virtual network that can be used to isolate resources. Key network concepts: * Defines a range of IP addresses for compute resources (e.g. instances) * Enables network segmentation and isolation * Provides common performance configuration across the network using a SKU The `cidr` is the base CIDR block for the network. Additional CIDR blocks can be added to the network using the `additionalCidrs` field. The `additionalCidrs` can be changed after the network is created in case they are not used. The main CIDR block cannot be changed after the network is created. All cidrs must be non-overlapping. The cidrs have to be part of the RFC 1918 address space in case of IPv4 and or RFC 4193. In case the system should automatically assign IP addresses to the network cidrs only the network prefix is required. E.g. to request a /16 IPv4 CIDR block the CIDR block would be `0.0.0.0/16` and for a /56 IPv6 CIDR block the CIDR block would be `::/56`. Most CSP will not allow to use a different IPv6 prefix length than /56. Route tables associated with this network automatically include local routes for all network CIDRs (including `additionalCidrs`). These network-local routes are present by default and cannot be removed.
        """
        return pulumi.get(self, "spec")

    @spec.setter
    def spec(self, value: pulumi.Input['_schemas.NetworkSpecArgs']):
        pulumi.set(self, "spec", value)

    @_builtins.property
    @pulumi.getter
    def annotations(self) -> pulumi.Input[Optional[Mapping[str, pulumi.Input[_builtins.str]]]]:
        """
        User-defined key/value pairs that are mutable and can be used to add annotations. The number of annotations is eventually limited by the CSP.
        """
        return pulumi.get(self, "annotations")

    @annotations.setter
    def annotations(self, value: pulumi.Input[Optional[Mapping[str, pulumi.Input[_builtins.str]]]]):
        pulumi.set(self, "annotations", value)

    @_builtins.property
    @pulumi.getter
    def extensions(self) -> pulumi.Input[Optional[Mapping[str, pulumi.Input[_builtins.str]]]]:
        """
        User-defined key/value pairs that are mutable and can be used to add extensions. Extensions are subject to validation by the CSP, and any value that is not accepted will be rejected during admission.
        """
        return pulumi.get(self, "extensions")

    @extensions.setter
    def extensions(self, value: pulumi.Input[Optional[Mapping[str, pulumi.Input[_builtins.str]]]]):
        pulumi.set(self, "extensions", value)

    @_builtins.property
    @pulumi.getter
    def labels(self) -> pulumi.Input[Optional[Mapping[str, pulumi.Input[_builtins.str]]]]:
        """
        User-defined key/value pairs that are mutable and can be used to organize and categorize resources. They can be used to filter resources. The number of labels is eventually limited by the CSP.
        """
        return pulumi.get(self, "labels")

    @labels.setter
    def labels(self, value: pulumi.Input[Optional[Mapping[str, pulumi.Input[_builtins.str]]]]):
        pulumi.set(self, "labels", value)

    @_builtins.property
    @pulumi.getter
    def tenant(self) -> pulumi.Input[Optional[_builtins.str]]:
        """
        The tenant for the resource. If omitted, the provider default is used.
        """
        return pulumi.get(self, "tenant")

    @tenant.setter
    def tenant(self, value: pulumi.Input[Optional[_builtins.str]]):
        pulumi.set(self, "tenant", value)

    @_builtins.property
    @pulumi.getter
    def workspace(self) -> pulumi.Input[Optional[_builtins.str]]:
        """
        The workspace for the resource. If omitted, the provider default is used. Must be configured by either means.
        """
        return pulumi.get(self, "workspace")

    @workspace.setter
    def workspace(self, value: pulumi.Input[Optional[_builtins.str]]):
        pulumi.set(self, "workspace", value)


@pulumi.type_token("cape:network:Network")
class Network(pulumi.CustomResource):
    @overload
    def __init__(__self__,
                 resource_name: str,
                 opts: Optional[pulumi.ResourceOptions] = None,
                 annotations: pulumi.Input[Optional[Mapping[str, pulumi.Input[_builtins.str]]]] = None,
                 extensions: pulumi.Input[Optional[Mapping[str, pulumi.Input[_builtins.str]]]] = None,
                 labels: pulumi.Input[Optional[Mapping[str, pulumi.Input[_builtins.str]]]] = None,
                 spec: pulumi.Input[Optional[Union['_schemas.NetworkSpecArgs', '_schemas.NetworkSpecArgsDict', '_schemas.outputs.NetworkSpec']]] = None,
                 tenant: pulumi.Input[Optional[_builtins.str]] = None,
                 workspace: pulumi.Input[Optional[_builtins.str]] = None,
                 __props__=None):
        """
        A Network represents a virtual network that can be used to isolate resources. Key network concepts: * Defines a range of IP addresses for compute resources (e.g. instances) * Enables network segmentation and isolation * Provides common performance configuration across the network using a SKU

        :param str resource_name: The name of the resource.
        :param pulumi.ResourceOptions opts: Options for the resource.
        :param pulumi.Input[Mapping[str, pulumi.Input[_builtins.str]]] annotations: User-defined key/value pairs that are mutable and can be used to add annotations. The number of annotations is eventually limited by the CSP.
        :param pulumi.Input[Mapping[str, pulumi.Input[_builtins.str]]] extensions: User-defined key/value pairs that are mutable and can be used to add extensions. Extensions are subject to validation by the CSP, and any value that is not accepted will be rejected during admission.
        :param pulumi.Input[Mapping[str, pulumi.Input[_builtins.str]]] labels: User-defined key/value pairs that are mutable and can be used to organize and categorize resources. They can be used to filter resources. The number of labels is eventually limited by the CSP.
        :param pulumi.Input[Union['_schemas.NetworkSpecArgs', '_schemas.NetworkSpecArgsDict', '_schemas.outputs.NetworkSpec']] spec: A Network represents a virtual network that can be used to isolate resources. Key network concepts: * Defines a range of IP addresses for compute resources (e.g. instances) * Enables network segmentation and isolation * Provides common performance configuration across the network using a SKU The `cidr` is the base CIDR block for the network. Additional CIDR blocks can be added to the network using the `additionalCidrs` field. The `additionalCidrs` can be changed after the network is created in case they are not used. The main CIDR block cannot be changed after the network is created. All cidrs must be non-overlapping. The cidrs have to be part of the RFC 1918 address space in case of IPv4 and or RFC 4193. In case the system should automatically assign IP addresses to the network cidrs only the network prefix is required. E.g. to request a /16 IPv4 CIDR block the CIDR block would be `0.0.0.0/16` and for a /56 IPv6 CIDR block the CIDR block would be `::/56`. Most CSP will not allow to use a different IPv6 prefix length than /56. Route tables associated with this network automatically include local routes for all network CIDRs (including `additionalCidrs`). These network-local routes are present by default and cannot be removed.
        :param pulumi.Input[_builtins.str] tenant: The tenant for the resource. If omitted, the provider default is used.
        :param pulumi.Input[_builtins.str] workspace: The workspace for the resource. If omitted, the provider default is used. Must be configured by either means.
        """
        ...
    @overload
    def __init__(__self__,
                 resource_name: str,
                 args: NetworkArgs,
                 opts: Optional[pulumi.ResourceOptions] = None):
        """
        A Network represents a virtual network that can be used to isolate resources. Key network concepts: * Defines a range of IP addresses for compute resources (e.g. instances) * Enables network segmentation and isolation * Provides common performance configuration across the network using a SKU

        :param str resource_name: The name of the resource.
        :param NetworkArgs args: The arguments to use to populate this resource's properties.
        :param pulumi.ResourceOptions opts: Options for the resource.
        """
        ...
    def __init__(__self__, resource_name: str, *args, **kwargs):
        resource_args, opts = _utilities.get_resource_args_opts(NetworkArgs, pulumi.ResourceOptions, *args, **kwargs)
        if resource_args is not None:
            __self__._internal_init(resource_name, opts, **resource_args.__dict__)
        else:
            __self__._internal_init(resource_name, *args, **kwargs)

    def _internal_init(__self__,
                 resource_name: str,
                 opts: Optional[pulumi.ResourceOptions] = None,
                 annotations: pulumi.Input[Optional[Mapping[str, pulumi.Input[_builtins.str]]]] = None,
                 extensions: pulumi.Input[Optional[Mapping[str, pulumi.Input[_builtins.str]]]] = None,
                 labels: pulumi.Input[Optional[Mapping[str, pulumi.Input[_builtins.str]]]] = None,
                 spec: pulumi.Input[Optional[Union['_schemas.NetworkSpecArgs', '_schemas.NetworkSpecArgsDict', '_schemas.outputs.NetworkSpec']]] = None,
                 tenant: pulumi.Input[Optional[_builtins.str]] = None,
                 workspace: pulumi.Input[Optional[_builtins.str]] = None,
                 __props__=None):
        opts = pulumi.ResourceOptions.merge(_utilities.get_resource_opts_defaults(), opts)
        if not isinstance(opts, pulumi.ResourceOptions):
            raise TypeError('Expected resource options to be a ResourceOptions instance')
        if opts.id is None:
            if __props__ is not None:
                raise TypeError('__props__ is only valid when passed in combination with a valid opts.id to get an existing resource')
            __props__ = NetworkArgs.__new__(NetworkArgs)

            __props__.__dict__["annotations"] = annotations
            __props__.__dict__["extensions"] = extensions
            __props__.__dict__["labels"] = labels
            if spec is None and not opts.urn:
                raise TypeError("Missing required property 'spec'")
            __props__.__dict__["spec"] = spec
            __props__.__dict__["tenant"] = tenant
            __props__.__dict__["workspace"] = workspace
            __props__.__dict__["metadata"] = None
            __props__.__dict__["status"] = None
        super(Network, __self__).__init__(
            'cape:network:Network',
            resource_name,
            __props__,
            opts)

    @staticmethod
    def get(resource_name: str,
            id: pulumi.Input[str],
            opts: Optional[pulumi.ResourceOptions] = None) -> 'Network':
        """
        Get an existing Network resource's state with the given name, id, and optional extra
        properties used to qualify the lookup.

        :param str resource_name: The unique name of the resulting resource.
        :param pulumi.Input[str] id: The unique provider ID of the resource to lookup.
        :param pulumi.ResourceOptions opts: Options for the resource.
        """
        opts = pulumi.ResourceOptions.merge(opts, pulumi.ResourceOptions(id=id))

        __props__ = NetworkArgs.__new__(NetworkArgs)

        __props__.__dict__["annotations"] = None
        __props__.__dict__["extensions"] = None
        __props__.__dict__["labels"] = None
        __props__.__dict__["metadata"] = None
        __props__.__dict__["spec"] = None
        __props__.__dict__["status"] = None
        __props__.__dict__["tenant"] = None
        __props__.__dict__["workspace"] = None
        return Network(resource_name, opts=opts, __props__=__props__)

    @_builtins.property
    @pulumi.getter
    def annotations(self) -> pulumi.Output[Optional[Mapping[str, _builtins.str]]]:
        """
        User-defined key/value pairs that are mutable and can be used to add annotations. The number of annotations is eventually limited by the CSP.
        """
        return pulumi.get(self, "annotations")

    @_builtins.property
    @pulumi.getter
    def extensions(self) -> pulumi.Output[Optional[Mapping[str, _builtins.str]]]:
        """
        User-defined key/value pairs that are mutable and can be used to add extensions. Extensions are subject to validation by the CSP, and any value that is not accepted will be rejected during admission.
        """
        return pulumi.get(self, "extensions")

    @_builtins.property
    @pulumi.getter
    def labels(self) -> pulumi.Output[Optional[Mapping[str, _builtins.str]]]:
        """
        User-defined key/value pairs that are mutable and can be used to organize and categorize resources. They can be used to filter resources. The number of labels is eventually limited by the CSP.
        """
        return pulumi.get(self, "labels")

    @_builtins.property
    @pulumi.getter
    def metadata(self) -> pulumi.Output['_schemas.outputs.RegionalWorkspaceResourceMetadata']:
        """
        Metadata for regional resources with name, permission, modification, type, tenant and workspace and region information.
        """
        return pulumi.get(self, "metadata")

    @_builtins.property
    @pulumi.getter
    def spec(self) -> pulumi.Output['_schemas.outputs.NetworkSpec']:
        """
        A Network represents a virtual network that can be used to isolate resources. Key network concepts: * Defines a range of IP addresses for compute resources (e.g. instances) * Enables network segmentation and isolation * Provides common performance configuration across the network using a SKU The `cidr` is the base CIDR block for the network. Additional CIDR blocks can be added to the network using the `additionalCidrs` field. The `additionalCidrs` can be changed after the network is created in case they are not used. The main CIDR block cannot be changed after the network is created. All cidrs must be non-overlapping. The cidrs have to be part of the RFC 1918 address space in case of IPv4 and or RFC 4193. In case the system should automatically assign IP addresses to the network cidrs only the network prefix is required. E.g. to request a /16 IPv4 CIDR block the CIDR block would be `0.0.0.0/16` and for a /56 IPv6 CIDR block the CIDR block would be `::/56`. Most CSP will not allow to use a different IPv6 prefix length than /56. Route tables associated with this network automatically include local routes for all network CIDRs (including `additionalCidrs`). These network-local routes are present by default and cannot be removed.
        """
        return pulumi.get(self, "spec")

    @_builtins.property
    @pulumi.getter
    def status(self) -> pulumi.Output['_schemas.outputs.NetworkStatus']:
        """
        The status of the network. The status is read-only and will be set by the system. The status contains information about the current state of the network and its CIDR blocks. It will report the status of the CIDR blocks and the network as a whole including automatically assigned IP networks.
        """
        return pulumi.get(self, "status")

    @_builtins.property
    @pulumi.getter
    def tenant(self) -> pulumi.Output[Optional[_builtins.str]]:
        """
        The tenant for the resource. If omitted, the provider default is used.
        """
        return pulumi.get(self, "tenant")

    @_builtins.property
    @pulumi.getter
    def workspace(self) -> pulumi.Output[Optional[_builtins.str]]:
        """
        The workspace for the resource. If omitted, the provider default is used. Must be configured by either means.
        """
        return pulumi.get(self, "workspace")

