// *** WARNING: this file was generated by pulumi-language-java. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

package com.pulumi.cape.schemas.outputs;

import com.pulumi.cape.schemas.outputs.ReferenceObject;
import com.pulumi.cape.schemas.outputs.StatusCondition;
import com.pulumi.core.annotations.CustomType;
import com.pulumi.exceptions.MissingRequiredPropertyException;
import java.lang.Integer;
import java.lang.String;
import java.util.List;
import java.util.Objects;
import java.util.Optional;
import javax.annotation.Nullable;

@CustomType
public final class BlockStorageStatus {
    /**
     * @return Reference to the instance the block storage is attached to.
     * 
     */
    private @Nullable ReferenceObject attachedTo;
    private List<StatusCondition> conditions;
    /**
     * @return Size of the block storage in GB.
     * 
     */
    private Integer sizeGB;
    /**
     * @return Current phase of the resource: - pending: not available, waiting for other resources - creating: not available, creation started - active: available for data layer usage - updating: available for data layer usage - deleting: maybe still available for data layer user, can fail any moment - error: failed to fulfill the request; would be related to provider issue or customer related input.
     * 
     */
    private @Nullable String state;

    private BlockStorageStatus() {}
    /**
     * @return Reference to the instance the block storage is attached to.
     * 
     */
    public Optional<ReferenceObject> attachedTo() {
        return Optional.ofNullable(this.attachedTo);
    }
    public List<StatusCondition> conditions() {
        return this.conditions;
    }
    /**
     * @return Size of the block storage in GB.
     * 
     */
    public Integer sizeGB() {
        return this.sizeGB;
    }
    /**
     * @return Current phase of the resource: - pending: not available, waiting for other resources - creating: not available, creation started - active: available for data layer usage - updating: available for data layer usage - deleting: maybe still available for data layer user, can fail any moment - error: failed to fulfill the request; would be related to provider issue or customer related input.
     * 
     */
    public Optional<String> state() {
        return Optional.ofNullable(this.state);
    }

    public static Builder builder() {
        return new Builder();
    }

    public static Builder builder(BlockStorageStatus defaults) {
        return new Builder(defaults);
    }
    @CustomType.Builder
    public static final class Builder {
        private @Nullable ReferenceObject attachedTo;
        private List<StatusCondition> conditions;
        private Integer sizeGB;
        private @Nullable String state;
        public Builder() {}
        public Builder(BlockStorageStatus defaults) {
    	      Objects.requireNonNull(defaults);
    	      this.attachedTo = defaults.attachedTo;
    	      this.conditions = defaults.conditions;
    	      this.sizeGB = defaults.sizeGB;
    	      this.state = defaults.state;
        }

        @CustomType.Setter
        public Builder attachedTo(@Nullable ReferenceObject attachedTo) {

            this.attachedTo = attachedTo;
            return this;
        }
        @CustomType.Setter
        public Builder conditions(List<StatusCondition> conditions) {
            if (conditions == null) {
              throw new MissingRequiredPropertyException("BlockStorageStatus", "conditions");
            }
            this.conditions = conditions;
            return this;
        }
        public Builder conditions(StatusCondition... conditions) {
            return conditions(List.of(conditions));
        }
        @CustomType.Setter
        public Builder sizeGB(Integer sizeGB) {
            if (sizeGB == null) {
              throw new MissingRequiredPropertyException("BlockStorageStatus", "sizeGB");
            }
            this.sizeGB = sizeGB;
            return this;
        }
        @CustomType.Setter
        public Builder state(@Nullable String state) {

            this.state = state;
            return this;
        }
        public BlockStorageStatus build() {
            final var _resultValue = new BlockStorageStatus();
            _resultValue.attachedTo = attachedTo;
            _resultValue.conditions = conditions;
            _resultValue.sizeGB = sizeGB;
            _resultValue.state = state;
            return _resultValue;
        }
    }
}
