// *** WARNING: this file was generated by pulumi-language-java. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

package com.pulumi.cape.schemas.outputs;

import com.pulumi.core.annotations.CustomType;
import com.pulumi.exceptions.MissingRequiredPropertyException;
import java.lang.Integer;
import java.util.Objects;

@CustomType
public final class IcmpConfig {
    /**
     * @return ICMP code
     * 
     */
    private Integer code;
    /**
     * @return ICMP type
     * 
     */
    private Integer type;

    private IcmpConfig() {}
    /**
     * @return ICMP code
     * 
     */
    public Integer code() {
        return this.code;
    }
    /**
     * @return ICMP type
     * 
     */
    public Integer type() {
        return this.type;
    }

    public static Builder builder() {
        return new Builder();
    }

    public static Builder builder(IcmpConfig defaults) {
        return new Builder(defaults);
    }
    @CustomType.Builder
    public static final class Builder {
        private Integer code;
        private Integer type;
        public Builder() {}
        public Builder(IcmpConfig defaults) {
    	      Objects.requireNonNull(defaults);
    	      this.code = defaults.code;
    	      this.type = defaults.type;
        }

        @CustomType.Setter
        public Builder code(Integer code) {
            if (code == null) {
              throw new MissingRequiredPropertyException("IcmpConfig", "code");
            }
            this.code = code;
            return this;
        }
        @CustomType.Setter
        public Builder type(Integer type) {
            if (type == null) {
              throw new MissingRequiredPropertyException("IcmpConfig", "type");
            }
            this.type = type;
            return this;
        }
        public IcmpConfig build() {
            final var _resultValue = new IcmpConfig();
            _resultValue.code = code;
            _resultValue.type = type;
            return _resultValue;
        }
    }
}
