// *** WARNING: this file was generated by pulumi-language-java. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

package com.pulumi.cape.schemas.outputs;

import com.pulumi.core.annotations.CustomType;
import com.pulumi.exceptions.MissingRequiredPropertyException;
import java.lang.String;
import java.util.Objects;

@CustomType
public final class KubernetesNodeTaint {
    /**
     * @return The effect of the taint. The effect determines how the taint is applied to the nodes in the node pool. For details on the effects, see the (kubernetes documentation on taints and tolerations)[https://kubernetes.io/docs/concepts/scheduling-eviction/taint-and-toleration/].
     * 
     */
    private String effect;
    /**
     * @return The key of the taint. The key is used to identify the taint and is used in conjunction with the value and effect.
     * 
     */
    private String key;
    /**
     * @return The value of the taint. The value is used to identify the taint and is used in conjunction with the key and effect.
     * 
     */
    private String value;

    private KubernetesNodeTaint() {}
    /**
     * @return The effect of the taint. The effect determines how the taint is applied to the nodes in the node pool. For details on the effects, see the (kubernetes documentation on taints and tolerations)[https://kubernetes.io/docs/concepts/scheduling-eviction/taint-and-toleration/].
     * 
     */
    public String effect() {
        return this.effect;
    }
    /**
     * @return The key of the taint. The key is used to identify the taint and is used in conjunction with the value and effect.
     * 
     */
    public String key() {
        return this.key;
    }
    /**
     * @return The value of the taint. The value is used to identify the taint and is used in conjunction with the key and effect.
     * 
     */
    public String value() {
        return this.value;
    }

    public static Builder builder() {
        return new Builder();
    }

    public static Builder builder(KubernetesNodeTaint defaults) {
        return new Builder(defaults);
    }
    @CustomType.Builder
    public static final class Builder {
        private String effect;
        private String key;
        private String value;
        public Builder() {}
        public Builder(KubernetesNodeTaint defaults) {
    	      Objects.requireNonNull(defaults);
    	      this.effect = defaults.effect;
    	      this.key = defaults.key;
    	      this.value = defaults.value;
        }

        @CustomType.Setter
        public Builder effect(String effect) {
            if (effect == null) {
              throw new MissingRequiredPropertyException("KubernetesNodeTaint", "effect");
            }
            this.effect = effect;
            return this;
        }
        @CustomType.Setter
        public Builder key(String key) {
            if (key == null) {
              throw new MissingRequiredPropertyException("KubernetesNodeTaint", "key");
            }
            this.key = key;
            return this;
        }
        @CustomType.Setter
        public Builder value(String value) {
            if (value == null) {
              throw new MissingRequiredPropertyException("KubernetesNodeTaint", "value");
            }
            this.value = value;
            return this;
        }
        public KubernetesNodeTaint build() {
            final var _resultValue = new KubernetesNodeTaint();
            _resultValue.effect = effect;
            _resultValue.key = key;
            _resultValue.value = value;
            return _resultValue;
        }
    }
}
