// *** WARNING: this file was generated by pulumi-language-java. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

package com.pulumi.cape.schemas.outputs;

import com.pulumi.cape.schemas.outputs.Cidr;
import com.pulumi.cape.schemas.outputs.Reference;
import com.pulumi.core.annotations.CustomType;
import com.pulumi.exceptions.MissingRequiredPropertyException;
import java.util.List;
import java.util.Objects;
import javax.annotation.Nullable;

@CustomType
public final class NetworkSpec {
    private @Nullable List<Cidr> additionalCidrs;
    /**
     * @return Combined IPv4 and IPv6 CIDR block for a subnet. Depending on the network configuration, either the IPv4 or IPv6 range can be omitted. So the following combinations are possible: * IPv4 only * IPv6 only * IPv4 and IPv6 (Dual Stack)
     * 
     */
    private Cidr cidr;
    /**
     * @return Reference to the SKU used by default for all NIC in this Network. Can be overridden by the NIC. The SKU is immutable after the network is created. To change the SKU, the network must be deleted and recreated with the new SKU reference.
     * 
     */
    private Reference skuRef;

    private NetworkSpec() {}
    public List<Cidr> additionalCidrs() {
        return this.additionalCidrs == null ? List.of() : this.additionalCidrs;
    }
    /**
     * @return Combined IPv4 and IPv6 CIDR block for a subnet. Depending on the network configuration, either the IPv4 or IPv6 range can be omitted. So the following combinations are possible: * IPv4 only * IPv6 only * IPv4 and IPv6 (Dual Stack)
     * 
     */
    public Cidr cidr() {
        return this.cidr;
    }
    /**
     * @return Reference to the SKU used by default for all NIC in this Network. Can be overridden by the NIC. The SKU is immutable after the network is created. To change the SKU, the network must be deleted and recreated with the new SKU reference.
     * 
     */
    public Reference skuRef() {
        return this.skuRef;
    }

    public static Builder builder() {
        return new Builder();
    }

    public static Builder builder(NetworkSpec defaults) {
        return new Builder(defaults);
    }
    @CustomType.Builder
    public static final class Builder {
        private @Nullable List<Cidr> additionalCidrs;
        private Cidr cidr;
        private Reference skuRef;
        public Builder() {}
        public Builder(NetworkSpec defaults) {
    	      Objects.requireNonNull(defaults);
    	      this.additionalCidrs = defaults.additionalCidrs;
    	      this.cidr = defaults.cidr;
    	      this.skuRef = defaults.skuRef;
        }

        @CustomType.Setter
        public Builder additionalCidrs(@Nullable List<Cidr> additionalCidrs) {

            this.additionalCidrs = additionalCidrs;
            return this;
        }
        public Builder additionalCidrs(Cidr... additionalCidrs) {
            return additionalCidrs(List.of(additionalCidrs));
        }
        @CustomType.Setter
        public Builder cidr(Cidr cidr) {
            if (cidr == null) {
              throw new MissingRequiredPropertyException("NetworkSpec", "cidr");
            }
            this.cidr = cidr;
            return this;
        }
        @CustomType.Setter
        public Builder skuRef(Reference skuRef) {
            if (skuRef == null) {
              throw new MissingRequiredPropertyException("NetworkSpec", "skuRef");
            }
            this.skuRef = skuRef;
            return this;
        }
        public NetworkSpec build() {
            final var _resultValue = new NetworkSpec();
            _resultValue.additionalCidrs = additionalCidrs;
            _resultValue.cidr = cidr;
            _resultValue.skuRef = skuRef;
            return _resultValue;
        }
    }
}
