// *** WARNING: this file was generated by pulumi-language-java. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

package com.pulumi.cape.schemas.outputs;

import com.pulumi.cape.schemas.outputs.StatusCondition;
import com.pulumi.core.annotations.CustomType;
import com.pulumi.exceptions.MissingRequiredPropertyException;
import java.lang.String;
import java.util.List;
import java.util.Objects;
import java.util.Optional;
import javax.annotation.Nullable;

@CustomType
public final class ObjectStorageAccountStatus {
    /**
     * @return Access key for the object storage account
     * 
     */
    private @Nullable String accessKey;
    /**
     * @return Canonical user ID for the object storage account
     * 
     */
    private @Nullable String canonicalUserId;
    /**
     * @return History of state transitions, ordered newest-first, complementing the current snapshot in `state`.
     * 
     */
    private List<StatusCondition> conditions;
    /**
     * @return Secret key for the object storage account
     * 
     */
    private @Nullable String secretKey;
    private @Nullable String state;

    private ObjectStorageAccountStatus() {}
    /**
     * @return Access key for the object storage account
     * 
     */
    public Optional<String> accessKey() {
        return Optional.ofNullable(this.accessKey);
    }
    /**
     * @return Canonical user ID for the object storage account
     * 
     */
    public Optional<String> canonicalUserId() {
        return Optional.ofNullable(this.canonicalUserId);
    }
    /**
     * @return History of state transitions, ordered newest-first, complementing the current snapshot in `state`.
     * 
     */
    public List<StatusCondition> conditions() {
        return this.conditions;
    }
    /**
     * @return Secret key for the object storage account
     * 
     */
    public Optional<String> secretKey() {
        return Optional.ofNullable(this.secretKey);
    }
    public Optional<String> state() {
        return Optional.ofNullable(this.state);
    }

    public static Builder builder() {
        return new Builder();
    }

    public static Builder builder(ObjectStorageAccountStatus defaults) {
        return new Builder(defaults);
    }
    @CustomType.Builder
    public static final class Builder {
        private @Nullable String accessKey;
        private @Nullable String canonicalUserId;
        private List<StatusCondition> conditions;
        private @Nullable String secretKey;
        private @Nullable String state;
        public Builder() {}
        public Builder(ObjectStorageAccountStatus defaults) {
    	      Objects.requireNonNull(defaults);
    	      this.accessKey = defaults.accessKey;
    	      this.canonicalUserId = defaults.canonicalUserId;
    	      this.conditions = defaults.conditions;
    	      this.secretKey = defaults.secretKey;
    	      this.state = defaults.state;
        }

        @CustomType.Setter
        public Builder accessKey(@Nullable String accessKey) {

            this.accessKey = accessKey;
            return this;
        }
        @CustomType.Setter
        public Builder canonicalUserId(@Nullable String canonicalUserId) {

            this.canonicalUserId = canonicalUserId;
            return this;
        }
        @CustomType.Setter
        public Builder conditions(List<StatusCondition> conditions) {
            if (conditions == null) {
              throw new MissingRequiredPropertyException("ObjectStorageAccountStatus", "conditions");
            }
            this.conditions = conditions;
            return this;
        }
        public Builder conditions(StatusCondition... conditions) {
            return conditions(List.of(conditions));
        }
        @CustomType.Setter
        public Builder secretKey(@Nullable String secretKey) {

            this.secretKey = secretKey;
            return this;
        }
        @CustomType.Setter
        public Builder state(@Nullable String state) {

            this.state = state;
            return this;
        }
        public ObjectStorageAccountStatus build() {
            final var _resultValue = new ObjectStorageAccountStatus();
            _resultValue.accessKey = accessKey;
            _resultValue.canonicalUserId = canonicalUserId;
            _resultValue.conditions = conditions;
            _resultValue.secretKey = secretKey;
            _resultValue.state = state;
            return _resultValue;
        }
    }
}
