// *** WARNING: this file was generated by pulumi-language-nodejs. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from "@pulumi/pulumi";
import * as inputs from "../types/input";
import * as outputs from "../types/output";

import * as utilities from "../utilities";

export namespace schemas {
    /**
     * References the SKU used for this block. If a reference to the source image is used as the base for creating this block storage.
     */
    export interface BlockStorageSpecArgs {
        /**
         * Size of the block storage in GB.
         */
        sizeGB: pulumi.Input<number>;
        /**
         * Reference to the SKU of the block storage.
         */
        skuRef: pulumi.Input<inputs.schemas.ReferenceArgs>;
        /**
         * Reference to the source image used as the base for creating the block storage.
         */
        sourceImageRef?: pulumi.Input<inputs.schemas.ReferenceArgs>;
    }

    /**
     * Specification of the instance, including its SKU, network configuration, and storage options.
     */
    export interface InstanceSpecArgs {
        /**
         * Additional NICs attached to this instance
         */
        additionalNicRefs?: pulumi.Input<pulumi.Input<inputs.schemas.ReferenceArgs>[]>;
        /**
         * Anti-affinity group to which this instance belongs. Instances in the same anti-affinity group are placed on different physical hosts. The number of maximum instances in an anti-affinity group is provider-specific.
         */
        antiAffinityGroup?: pulumi.Input<string>;
        /**
         * Reference to the block storage used to store the boot volume of the instance.
         */
        bootVolume: pulumi.Input<inputs.schemas.VolumeReferenceArgs>;
        dataVolumes?: pulumi.Input<pulumi.Input<inputs.schemas.VolumeReferenceArgs>[]>;
        /**
         * Reference to the primary NIC attached to this instance.
         */
        primaryNicRef?: pulumi.Input<inputs.schemas.ReferenceArgs>;
        /**
         * Reference to the security group associated with this instance.
         */
        securityGroupRef?: pulumi.Input<inputs.schemas.ReferenceArgs>;
        /**
         * Reference to the SKU of the instance.
         */
        skuRef: pulumi.Input<inputs.schemas.ReferenceArgs>;
        /**
         * Provider-specific references to SSH keys used in cloud-init vendorData. These references are used to inject SSH public keys during instance initialization through cloud-init's vendor data configuration.
         */
        sshKeys?: pulumi.Input<pulumi.Input<string>[]>;
        /**
         * Cloud-init user data for instance initialization Example cloud-init user configuration with SSH key:
         */
        userData?: pulumi.Input<string>;
        /**
         * Reference to a specific zone within a region
         */
        zone: pulumi.Input<string>;
    }
    /**
     * instanceSpecArgsProvideDefaults sets the appropriate defaults for InstanceSpecArgs
     */
    export function instanceSpecArgsProvideDefaults(val: InstanceSpecArgs): InstanceSpecArgs {
        return {
            ...val,
            bootVolume: pulumi.output(val.bootVolume).apply(inputs.schemas.volumeReferenceArgsProvideDefaults),
        };
    }

    /**
     * A reference to a resource using an object. The object contains the same information as the ReferenceURN, but is represented as a structured object. The advantage of this representation is that it can be used to reference resources in different workspaces or regions without the need to specify the full URN.
     */
    export interface ReferenceArgs {
        /**
         * Provider of the resource. If not set, the provider is inferred from the context.
         */
        provider?: pulumi.Input<string>;
        /**
         * Region of the resource. If not set, the region is inferred from the context.
         */
        region?: pulumi.Input<string>;
        /**
         * Name and type of the resource. Must be in the format `<type>/<name>`. The type is the resource type, and the name is the resource name.
         */
        resource: pulumi.Input<string>;
        /**
         * Tenant of the resource. If not set, the tenant is inferred from the context.
         */
        tenant?: pulumi.Input<string>;
        /**
         * Workspace of the resource. If not set, the workspace is inferred from the context.
         */
        workspace?: pulumi.Input<string>;
    }

    /**
     * Represents a connection between a Block Storage and an a user of the block storage.
     */
    export interface VolumeReferenceArgs {
        /**
         * Reference to the block storage used to store the volume.
         */
        deviceRef: pulumi.Input<inputs.schemas.ReferenceArgs>;
        /**
         * The connection type depends on the type of device and type of block storage.
         */
        type?: pulumi.Input<string>;
    }
    /**
     * volumeReferenceArgsProvideDefaults sets the appropriate defaults for VolumeReferenceArgs
     */
    export function volumeReferenceArgsProvideDefaults(val: VolumeReferenceArgs): VolumeReferenceArgs {
        return {
            ...val,
            type: (val.type) ?? "virtio",
        };
    }

}
