// Code generated by pulumi-language-go DO NOT EDIT.
// *** WARNING: Do not edit by hand unless you're certain you know what you are doing! ***

package network

import (
	"context"
	"reflect"

	"errors"
	"github.com/pulumi/cape/sdk/go/cape/internal"
	"github.com/pulumi/cape/sdk/go/cape/schemas"
	"github.com/pulumi/pulumi/sdk/v3/go/pulumi"
)

// The SecurityGroupRule resource defines a reusable network access rule. It can be referenced by multiple Security Groups to enforce consistent policies.
type SecurityGroupRule struct {
	pulumi.CustomResourceState

	// User-defined key/value pairs that are mutable and can be used to add annotations. The number of annotations is eventually limited by the CSP.
	Annotations pulumi.StringMapOutput `pulumi:"annotations"`
	// User-defined key/value pairs that are mutable and can be used to add extensions. Extensions are subject to validation by the CSP, and any value that is not accepted will be rejected during admission.
	Extensions pulumi.StringMapOutput `pulumi:"extensions"`
	// User-defined key/value pairs that are mutable and can be used to organize and categorize resources. They can be used to filter resources. The number of labels is eventually limited by the CSP.
	Labels pulumi.StringMapOutput `pulumi:"labels"`
	// Metadata for regional resources with name, permission, modification, type, tenant and workspace and region information.
	Metadata schemas.RegionalWorkspaceResourceMetadataOutput `pulumi:"metadata"`
	// Specification of a security group rule defining network access permissions. If no version is specified, any IP version will be allowed. If no protocol is specified, any network protocol will be allowed.
	Spec schemas.SecurityGroupRuleSpecOutput `pulumi:"spec"`
	// Current status of the resource
	Status schemas.SecurityGroupRuleStatusOutput `pulumi:"status"`
	// The tenant for the resource. If omitted, the provider default is used.
	Tenant pulumi.StringPtrOutput `pulumi:"tenant"`
	// The workspace for the resource. If omitted, the provider default is used. Must be configured by either means.
	Workspace pulumi.StringPtrOutput `pulumi:"workspace"`
}

// NewSecurityGroupRule registers a new resource with the given unique name, arguments, and options.
func NewSecurityGroupRule(ctx *pulumi.Context,
	name string, args *SecurityGroupRuleArgs, opts ...pulumi.ResourceOption) (*SecurityGroupRule, error) {
	if args == nil {
		return nil, errors.New("missing one or more required arguments")
	}

	if args.Spec == nil {
		return nil, errors.New("invalid value for required argument 'Spec'")
	}
	opts = internal.PkgResourceDefaultOpts(opts)
	var resource SecurityGroupRule
	err := ctx.RegisterResource("cape:network:SecurityGroupRule", name, args, &resource, opts...)
	if err != nil {
		return nil, err
	}
	return &resource, nil
}

// GetSecurityGroupRule gets an existing SecurityGroupRule resource's state with the given name, ID, and optional
// state properties that are used to uniquely qualify the lookup (nil if not required).
func GetSecurityGroupRule(ctx *pulumi.Context,
	name string, id pulumi.IDInput, state *SecurityGroupRuleState, opts ...pulumi.ResourceOption) (*SecurityGroupRule, error) {
	var resource SecurityGroupRule
	err := ctx.ReadResource("cape:network:SecurityGroupRule", name, id, state, &resource, opts...)
	if err != nil {
		return nil, err
	}
	return &resource, nil
}

// Input properties used for looking up and filtering SecurityGroupRule resources.
type securityGroupRuleState struct {
}

type SecurityGroupRuleState struct {
}

func (SecurityGroupRuleState) ElementType() reflect.Type {
	return reflect.TypeOf((*securityGroupRuleState)(nil)).Elem()
}

type securityGroupRuleArgs struct {
	// User-defined key/value pairs that are mutable and can be used to add annotations. The number of annotations is eventually limited by the CSP.
	Annotations map[string]string `pulumi:"annotations"`
	// User-defined key/value pairs that are mutable and can be used to add extensions. Extensions are subject to validation by the CSP, and any value that is not accepted will be rejected during admission.
	Extensions map[string]string `pulumi:"extensions"`
	// User-defined key/value pairs that are mutable and can be used to organize and categorize resources. They can be used to filter resources. The number of labels is eventually limited by the CSP.
	Labels map[string]string `pulumi:"labels"`
	// Specification of a security group rule defining network access permissions. If no version is specified, any IP version will be allowed. If no protocol is specified, any network protocol will be allowed.
	Spec schemas.SecurityGroupRuleSpec `pulumi:"spec"`
	// The tenant for the resource. If omitted, the provider default is used.
	Tenant *string `pulumi:"tenant"`
	// The workspace for the resource. If omitted, the provider default is used. Must be configured by either means.
	Workspace *string `pulumi:"workspace"`
}

// The set of arguments for constructing a SecurityGroupRule resource.
type SecurityGroupRuleArgs struct {
	// User-defined key/value pairs that are mutable and can be used to add annotations. The number of annotations is eventually limited by the CSP.
	Annotations pulumi.StringMapInput
	// User-defined key/value pairs that are mutable and can be used to add extensions. Extensions are subject to validation by the CSP, and any value that is not accepted will be rejected during admission.
	Extensions pulumi.StringMapInput
	// User-defined key/value pairs that are mutable and can be used to organize and categorize resources. They can be used to filter resources. The number of labels is eventually limited by the CSP.
	Labels pulumi.StringMapInput
	// Specification of a security group rule defining network access permissions. If no version is specified, any IP version will be allowed. If no protocol is specified, any network protocol will be allowed.
	Spec schemas.SecurityGroupRuleSpecInput
	// The tenant for the resource. If omitted, the provider default is used.
	Tenant pulumi.StringPtrInput
	// The workspace for the resource. If omitted, the provider default is used. Must be configured by either means.
	Workspace pulumi.StringPtrInput
}

func (SecurityGroupRuleArgs) ElementType() reflect.Type {
	return reflect.TypeOf((*securityGroupRuleArgs)(nil)).Elem()
}

type SecurityGroupRuleInput interface {
	pulumi.Input

	ToSecurityGroupRuleOutput() SecurityGroupRuleOutput
	ToSecurityGroupRuleOutputWithContext(ctx context.Context) SecurityGroupRuleOutput
}

func (*SecurityGroupRule) ElementType() reflect.Type {
	return reflect.TypeOf((**SecurityGroupRule)(nil)).Elem()
}

func (i *SecurityGroupRule) ToSecurityGroupRuleOutput() SecurityGroupRuleOutput {
	return i.ToSecurityGroupRuleOutputWithContext(context.Background())
}

func (i *SecurityGroupRule) ToSecurityGroupRuleOutputWithContext(ctx context.Context) SecurityGroupRuleOutput {
	return pulumi.ToOutputWithContext(ctx, i).(SecurityGroupRuleOutput)
}

// SecurityGroupRuleArrayInput is an input type that accepts SecurityGroupRuleArray and SecurityGroupRuleArrayOutput values.
// You can construct a concrete instance of `SecurityGroupRuleArrayInput` via:
//
//	SecurityGroupRuleArray{ SecurityGroupRuleArgs{...} }
type SecurityGroupRuleArrayInput interface {
	pulumi.Input

	ToSecurityGroupRuleArrayOutput() SecurityGroupRuleArrayOutput
	ToSecurityGroupRuleArrayOutputWithContext(context.Context) SecurityGroupRuleArrayOutput
}

type SecurityGroupRuleArray []SecurityGroupRuleInput

func (SecurityGroupRuleArray) ElementType() reflect.Type {
	return reflect.TypeOf((*[]*SecurityGroupRule)(nil)).Elem()
}

func (i SecurityGroupRuleArray) ToSecurityGroupRuleArrayOutput() SecurityGroupRuleArrayOutput {
	return i.ToSecurityGroupRuleArrayOutputWithContext(context.Background())
}

func (i SecurityGroupRuleArray) ToSecurityGroupRuleArrayOutputWithContext(ctx context.Context) SecurityGroupRuleArrayOutput {
	return pulumi.ToOutputWithContext(ctx, i).(SecurityGroupRuleArrayOutput)
}

// SecurityGroupRuleMapInput is an input type that accepts SecurityGroupRuleMap and SecurityGroupRuleMapOutput values.
// You can construct a concrete instance of `SecurityGroupRuleMapInput` via:
//
//	SecurityGroupRuleMap{ "key": SecurityGroupRuleArgs{...} }
type SecurityGroupRuleMapInput interface {
	pulumi.Input

	ToSecurityGroupRuleMapOutput() SecurityGroupRuleMapOutput
	ToSecurityGroupRuleMapOutputWithContext(context.Context) SecurityGroupRuleMapOutput
}

type SecurityGroupRuleMap map[string]SecurityGroupRuleInput

func (SecurityGroupRuleMap) ElementType() reflect.Type {
	return reflect.TypeOf((*map[string]*SecurityGroupRule)(nil)).Elem()
}

func (i SecurityGroupRuleMap) ToSecurityGroupRuleMapOutput() SecurityGroupRuleMapOutput {
	return i.ToSecurityGroupRuleMapOutputWithContext(context.Background())
}

func (i SecurityGroupRuleMap) ToSecurityGroupRuleMapOutputWithContext(ctx context.Context) SecurityGroupRuleMapOutput {
	return pulumi.ToOutputWithContext(ctx, i).(SecurityGroupRuleMapOutput)
}

type SecurityGroupRuleOutput struct{ *pulumi.OutputState }

func (SecurityGroupRuleOutput) ElementType() reflect.Type {
	return reflect.TypeOf((**SecurityGroupRule)(nil)).Elem()
}

func (o SecurityGroupRuleOutput) ToSecurityGroupRuleOutput() SecurityGroupRuleOutput {
	return o
}

func (o SecurityGroupRuleOutput) ToSecurityGroupRuleOutputWithContext(ctx context.Context) SecurityGroupRuleOutput {
	return o
}

// User-defined key/value pairs that are mutable and can be used to add annotations. The number of annotations is eventually limited by the CSP.
func (o SecurityGroupRuleOutput) Annotations() pulumi.StringMapOutput {
	return o.ApplyT(func(v *SecurityGroupRule) pulumi.StringMapOutput { return v.Annotations }).(pulumi.StringMapOutput)
}

// User-defined key/value pairs that are mutable and can be used to add extensions. Extensions are subject to validation by the CSP, and any value that is not accepted will be rejected during admission.
func (o SecurityGroupRuleOutput) Extensions() pulumi.StringMapOutput {
	return o.ApplyT(func(v *SecurityGroupRule) pulumi.StringMapOutput { return v.Extensions }).(pulumi.StringMapOutput)
}

// User-defined key/value pairs that are mutable and can be used to organize and categorize resources. They can be used to filter resources. The number of labels is eventually limited by the CSP.
func (o SecurityGroupRuleOutput) Labels() pulumi.StringMapOutput {
	return o.ApplyT(func(v *SecurityGroupRule) pulumi.StringMapOutput { return v.Labels }).(pulumi.StringMapOutput)
}

// Metadata for regional resources with name, permission, modification, type, tenant and workspace and region information.
func (o SecurityGroupRuleOutput) Metadata() schemas.RegionalWorkspaceResourceMetadataOutput {
	return o.ApplyT(func(v *SecurityGroupRule) schemas.RegionalWorkspaceResourceMetadataOutput { return v.Metadata }).(schemas.RegionalWorkspaceResourceMetadataOutput)
}

// Specification of a security group rule defining network access permissions. If no version is specified, any IP version will be allowed. If no protocol is specified, any network protocol will be allowed.
func (o SecurityGroupRuleOutput) Spec() schemas.SecurityGroupRuleSpecOutput {
	return o.ApplyT(func(v *SecurityGroupRule) schemas.SecurityGroupRuleSpecOutput { return v.Spec }).(schemas.SecurityGroupRuleSpecOutput)
}

// Current status of the resource
func (o SecurityGroupRuleOutput) Status() schemas.SecurityGroupRuleStatusOutput {
	return o.ApplyT(func(v *SecurityGroupRule) schemas.SecurityGroupRuleStatusOutput { return v.Status }).(schemas.SecurityGroupRuleStatusOutput)
}

// The tenant for the resource. If omitted, the provider default is used.
func (o SecurityGroupRuleOutput) Tenant() pulumi.StringPtrOutput {
	return o.ApplyT(func(v *SecurityGroupRule) pulumi.StringPtrOutput { return v.Tenant }).(pulumi.StringPtrOutput)
}

// The workspace for the resource. If omitted, the provider default is used. Must be configured by either means.
func (o SecurityGroupRuleOutput) Workspace() pulumi.StringPtrOutput {
	return o.ApplyT(func(v *SecurityGroupRule) pulumi.StringPtrOutput { return v.Workspace }).(pulumi.StringPtrOutput)
}

type SecurityGroupRuleArrayOutput struct{ *pulumi.OutputState }

func (SecurityGroupRuleArrayOutput) ElementType() reflect.Type {
	return reflect.TypeOf((*[]*SecurityGroupRule)(nil)).Elem()
}

func (o SecurityGroupRuleArrayOutput) ToSecurityGroupRuleArrayOutput() SecurityGroupRuleArrayOutput {
	return o
}

func (o SecurityGroupRuleArrayOutput) ToSecurityGroupRuleArrayOutputWithContext(ctx context.Context) SecurityGroupRuleArrayOutput {
	return o
}

func (o SecurityGroupRuleArrayOutput) Index(i pulumi.IntInput) SecurityGroupRuleOutput {
	return pulumi.All(o, i).ApplyT(func(vs []interface{}) *SecurityGroupRule {
		return vs[0].([]*SecurityGroupRule)[vs[1].(int)]
	}).(SecurityGroupRuleOutput)
}

type SecurityGroupRuleMapOutput struct{ *pulumi.OutputState }

func (SecurityGroupRuleMapOutput) ElementType() reflect.Type {
	return reflect.TypeOf((*map[string]*SecurityGroupRule)(nil)).Elem()
}

func (o SecurityGroupRuleMapOutput) ToSecurityGroupRuleMapOutput() SecurityGroupRuleMapOutput {
	return o
}

func (o SecurityGroupRuleMapOutput) ToSecurityGroupRuleMapOutputWithContext(ctx context.Context) SecurityGroupRuleMapOutput {
	return o
}

func (o SecurityGroupRuleMapOutput) MapIndex(k pulumi.StringInput) SecurityGroupRuleOutput {
	return pulumi.All(o, k).ApplyT(func(vs []interface{}) *SecurityGroupRule {
		return vs[0].(map[string]*SecurityGroupRule)[vs[1].(string)]
	}).(SecurityGroupRuleOutput)
}

func init() {
	pulumi.RegisterInputType(reflect.TypeOf((*SecurityGroupRuleInput)(nil)).Elem(), &SecurityGroupRule{})
	pulumi.RegisterInputType(reflect.TypeOf((*SecurityGroupRuleArrayInput)(nil)).Elem(), SecurityGroupRuleArray{})
	pulumi.RegisterInputType(reflect.TypeOf((*SecurityGroupRuleMapInput)(nil)).Elem(), SecurityGroupRuleMap{})
	pulumi.RegisterOutputType(SecurityGroupRuleOutput{})
	pulumi.RegisterOutputType(SecurityGroupRuleArrayOutput{})
	pulumi.RegisterOutputType(SecurityGroupRuleMapOutput{})
}
