// *** WARNING: this file was generated by pulumi-language-dotnet. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.Cape.Schemas.Outputs
{

    /// <summary>
    /// The status of the block storage.
    /// </summary>
    [OutputType]
    public sealed class BlockStorageStatus
    {
        /// <summary>
        /// Reference to the instance the block storage is attached to.
        /// </summary>
        public readonly Outputs.ReferenceObject? AttachedTo;
        public readonly ImmutableArray<Outputs.StatusCondition> Conditions;
        /// <summary>
        /// Size of the block storage in GB.
        /// </summary>
        public readonly int SizeGB;
        /// <summary>
        /// Current phase of the resource: - pending: not available, waiting for other resources - creating: not available, creation started - active: available for data layer usage - updating: available for data layer usage - deleting: maybe still available for data layer user, can fail any moment - error: failed to fulfill the request; would be related to provider issue or customer related input.
        /// </summary>
        public readonly string? State;

        [OutputConstructor]
        private BlockStorageStatus(
            Outputs.ReferenceObject? attachedTo,

            ImmutableArray<Outputs.StatusCondition> conditions,

            int sizeGB,

            string? state)
        {
            AttachedTo = attachedTo;
            Conditions = conditions;
            SizeGB = sizeGB;
            State = state;
        }
    }
}
