// *** WARNING: this file was generated by pulumi-language-dotnet. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.Cape.Schemas.Outputs
{

    /// <summary>
    /// The internet gateway will allocate a public IPv4 address. The NAT Gateway instance will be created in the specified zone using the specified public IP address and network interface. This implies the NAT Gateway instance will inherit the availability of the zone and not scale beyond the capability of a compute instance. The NIC needs to be in the same zone as the NAT Gateway instance. If the NIC has a public IP address, the NAT Gateway instance will report this as an error.
    /// </summary>
    [OutputType]
    public sealed class InternetNatGatewayInstanceSpec
    {
        /// <summary>
        /// Reference to the NIC attached to the internet NAT gateway.
        /// </summary>
        public readonly Outputs.Reference NicRef;
        /// <summary>
        /// Reference to the public IP allocated to this internet NAT gateway.
        /// </summary>
        public readonly Outputs.Reference PublicIpRef;
        /// <summary>
        /// Reference to the security group associated with the NAT gateway.
        /// </summary>
        public readonly Outputs.Reference? SecurityGroupRef;
        public readonly string Zone;

        [OutputConstructor]
        private InternetNatGatewayInstanceSpec(
            Outputs.Reference nicRef,

            Outputs.Reference publicIpRef,

            Outputs.Reference? securityGroupRef,

            string zone)
        {
            NicRef = nicRef;
            PublicIpRef = publicIpRef;
            SecurityGroupRef = securityGroupRef;
            Zone = zone;
        }
    }
}
