// *** WARNING: this file was generated by pulumi-language-dotnet. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.Cape.Schemas.Outputs
{

    /// <summary>
    /// Template for creating nodes in the node pool. The template includes the instance SKU, subnet, and zone in which the nodes will be created. The SKU must be one of the available compute SKUs in the region.
    /// </summary>
    [OutputType]
    public sealed class KubernetesNodeTemplate
    {
        /// <summary>
        /// Root volume for the node. The root volume is used to store the operating system and other software required to run the node. The SKU must be one of the available block storage SKUs in the region.
        /// </summary>
        public readonly Outputs.KubernetesNodeRootVolume RootVolume;
        /// <summary>
        /// Reference to the security group associated with the node instances.
        /// </summary>
        public readonly Outputs.Reference? SecurityGroupRef;
        /// <summary>
        /// Reference to the SKU of the node instances. The SKU is immutable after the node pool is created. To change the SKU, the node pool must be deleted and recreated with the new SKU reference.
        /// </summary>
        public readonly Outputs.Reference SkuRef;
        /// <summary>
        /// Reference to the NIC attached to the node instances.
        /// </summary>
        public readonly Outputs.Reference SubnetRef;
        /// <summary>
        /// The zone in which the node instances will be created. The zone is immutable after the node pool is created. To change the zone, the node pool must be deleted and recreated with the new zone.
        /// </summary>
        public readonly string Zone;

        [OutputConstructor]
        private KubernetesNodeTemplate(
            Outputs.KubernetesNodeRootVolume rootVolume,

            Outputs.Reference? securityGroupRef,

            Outputs.Reference skuRef,

            Outputs.Reference subnetRef,

            string zone)
        {
            RootVolume = rootVolume;
            SecurityGroupRef = securityGroupRef;
            SkuRef = skuRef;
            SubnetRef = subnetRef;
            Zone = zone;
        }
    }
}
