// *** WARNING: this file was generated by pulumi-language-dotnet. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.Cape.Schemas.Outputs
{

    /// <summary>
    /// Represents the frontend configuration of the LoadBalancer. Each frontend can have multiple targets, but the combination of port and protocol must be unique to ensure proper routing.
    /// </summary>
    [OutputType]
    public sealed class NetworkLoadBalancerFrontend
    {
        /// <summary>
        /// Frontend port to which the load balancer will be listening on
        /// </summary>
        public readonly int Port;
        /// <summary>
        /// Frontend Protocol to which the load balancer will be listening on
        /// </summary>
        public readonly string Protocol;
        /// <summary>
        /// The target of the LoadBalancer. It can be a set of instances nics. The port can be different from the frontend port, if omitted it will be the same. If no health check is specified, the LoadBalancer will not check the health of the backend instances.
        /// </summary>
        public readonly Outputs.LoadBalancerTarget Target;

        [OutputConstructor]
        private NetworkLoadBalancerFrontend(
            int port,

            string protocol,

            Outputs.LoadBalancerTarget target)
        {
            Port = port;
            Protocol = protocol;
            Target = target;
        }
    }
}
