// *** WARNING: this file was generated by pulumi-language-dotnet. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.Cape.Schemas.Outputs
{

    /// <summary>
    /// A provider of cloud services
    /// </summary>
    [OutputType]
    public sealed class Provider
    {
        public readonly string Name;
        public readonly string Url;
        public readonly string Version;

        [OutputConstructor]
        private Provider(
            string name,

            string url,

            string version)
        {
            Name = name;
            Url = url;
            Version = version;
        }
    }
}
