// *** WARNING: this file was generated by pulumi-language-dotnet. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.Cape.Schemas.Outputs
{

    /// <summary>
    /// Specification of the public IP.
    /// </summary>
    [OutputType]
    public sealed class PublicIpSpec
    {
        /// <summary>
        /// The public IP address in case of BYOIP.
        /// </summary>
        public readonly string? Address;
        /// <summary>
        /// IP version of the address
        /// </summary>
        public readonly string Version;

        [OutputConstructor]
        private PublicIpSpec(
            string? address,

            string version)
        {
            Address = address;
            Version = version;
        }
    }
}
