// *** WARNING: this file was generated by pulumi-language-dotnet. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.Cape.Schemas.Outputs
{

    /// <summary>
    /// Metadata for regional resources with name, permission, modification, type, tenant and region information.
    /// </summary>
    [OutputType]
    public sealed class RegionalResourceMetadata
    {
        /// <summary>
        /// API version of the resource
        /// </summary>
        public readonly string ApiVersion;
        /// <summary>
        /// Indicates the time when the resource was created. The field is set by the provider and should not be modified by the user.
        /// </summary>
        public readonly string CreatedAt;
        /// <summary>
        /// If set, indicates the time when the resource was marked for deletion. Resources with this field set are considered pending deletion.
        /// </summary>
        public readonly string? DeletedAt;
        /// <summary>
        /// Type of the resource
        /// </summary>
        public readonly string Kind;
        /// <summary>
        /// Indicates the time when the resource was created or last modified. Field is used for "If-Unmodified-Since" logic for concurrency control. The provider guarantees that a modification on a single resource can happen only once every millisecond.
        /// </summary>
        public readonly string LastModifiedAt;
        /// <summary>
        /// Resource identifier in dash-case (kebab-case) format. Must start and end with an alphanumeric character. Can contain lowercase letters, numbers, and hyphens. Multiple segments can be joined with dots. Each segment follows the same rules.
        /// </summary>
        public readonly string Name;
        public readonly string Provider;
        /// <summary>
        /// A unique resource name used to reference this resource in other resources. The reference is represented as the full URN (Uniform Resource Name) name of the resource. ### Automatic Prefix Inference In most cases, the prefix of the URN can be automatically derived in the given context. To simplify usage, only the resource type and name might be specified as a reference using the `&lt;type&gt;/&lt;name&gt;` notation. The suffix can be made more specific by adding additional segments separated by slashes. The prefix is automatically inferred from the context. For example, if the resource is a block storage in the same workspace the reference can be specified as `block-storages/my-block-storage`. If the resource is a block storage in a different workspace, the reference can be specified as `workspaces/ws-1/block-storages/my-block-storage`. For automatic prefix inference, the following rules apply: - the version is inferred from the current resource version - the workspace is inferred from the current workspace - the region is inferred from the current region - the provider is inferred from the type and context of the usage The prefix inference is resolved on admission into the full URN format, which makes it mostly suitable for human use.
        /// </summary>
        public readonly string Ref;
        /// <summary>
        /// Reference to the region where the resource is located
        /// </summary>
        public readonly string Region;
        public readonly string Resource;
        /// <summary>
        /// Incremented on every modification of the resource. Used for optimistic concurrency control.
        /// </summary>
        public readonly int ResourceVersion;
        /// <summary>
        /// Tenant identifier
        /// </summary>
        public readonly string Tenant;
        public readonly string Verb;

        [OutputConstructor]
        private RegionalResourceMetadata(
            string apiVersion,

            string createdAt,

            string? deletedAt,

            string kind,

            string lastModifiedAt,

            string name,

            string provider,

            string @ref,

            string region,

            string resource,

            int resourceVersion,

            string tenant,

            string verb)
        {
            ApiVersion = apiVersion;
            CreatedAt = createdAt;
            DeletedAt = deletedAt;
            Kind = kind;
            LastModifiedAt = lastModifiedAt;
            Name = name;
            Provider = provider;
            Ref = @ref;
            Region = region;
            Resource = resource;
            ResourceVersion = resourceVersion;
            Tenant = tenant;
            Verb = verb;
        }
    }
}
