// *** WARNING: this file was generated by pulumi-language-dotnet. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.Cape.Schemas.Outputs
{

    /// <summary>
    /// Role specification defined as a list of permissions. Roles are used to define access control policies for a user account using a role assignment.
    /// </summary>
    [OutputType]
    public sealed class RoleSpec
    {
        /// <summary>
        /// List of permissions granted by this role
        /// </summary>
        public readonly ImmutableArray<Outputs.Permission> Permissions;

        [OutputConstructor]
        private RoleSpec(ImmutableArray<Outputs.Permission> permissions)
        {
            Permissions = permissions;
        }
    }
}
