// *** WARNING: this file was generated by pulumi-language-dotnet. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.Cape.Schemas.Outputs
{

    /// <summary>
    /// The RouteTableSpec defines the routes that are associated with the route table.
    /// </summary>
    [OutputType]
    public sealed class RouteTableSpec
    {
        public readonly ImmutableArray<Outputs.RouteSpec> Routes;

        [OutputConstructor]
        private RouteTableSpec(ImmutableArray<Outputs.RouteSpec> routes)
        {
            Routes = routes;
        }
    }
}
