// *** WARNING: this file was generated by pulumi-language-dotnet. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.Cape.Schemas.Outputs
{

    /// <summary>
    /// Metadata for SKU resources with name, permission, type, tenant and region information.
    /// </summary>
    [OutputType]
    public sealed class SkuResourceMetadata
    {
        /// <summary>
        /// API version of the resource
        /// </summary>
        public readonly string ApiVersion;
        /// <summary>
        /// Type of the resource
        /// </summary>
        public readonly string Kind;
        /// <summary>
        /// Resource identifier in dash-case (kebab-case) format. Must start and end with an alphanumeric character. Can contain lowercase letters, numbers, and hyphens. Multiple segments can be joined with dots. Each segment follows the same rules.
        /// </summary>
        public readonly string Name;
        public readonly string Provider;
        /// <summary>
        /// A unique resource name used to reference this resource in other resources. The reference is represented as the full URN (Uniform Resource Name) name of the resource. ### Automatic Prefix Inference In most cases, the prefix of the URN can be automatically derived in the given context. To simplify usage, only the resource type and name might be specified as a reference using the `&lt;type&gt;/&lt;name&gt;` notation. The suffix can be made more specific by adding additional segments separated by slashes. The prefix is automatically inferred from the context. For example, if the resource is a block storage in the same workspace the reference can be specified as `block-storages/my-block-storage`. If the resource is a block storage in a different workspace, the reference can be specified as `workspaces/ws-1/block-storages/my-block-storage`. For automatic prefix inference, the following rules apply: - the version is inferred from the current resource version - the workspace is inferred from the current workspace - the region is inferred from the current region - the provider is inferred from the type and context of the usage The prefix inference is resolved on admission into the full URN format, which makes it mostly suitable for human use.
        /// </summary>
        public readonly string Ref;
        /// <summary>
        /// Reference to the region where the resource is located
        /// </summary>
        public readonly string Region;
        public readonly string Resource;
        /// <summary>
        /// Tenant identifier
        /// </summary>
        public readonly string Tenant;
        public readonly string Verb;

        [OutputConstructor]
        private SkuResourceMetadata(
            string apiVersion,

            string kind,

            string name,

            string provider,

            string @ref,

            string region,

            string resource,

            string tenant,

            string verb)
        {
            ApiVersion = apiVersion;
            Kind = kind;
            Name = name;
            Provider = provider;
            Ref = @ref;
            Region = region;
            Resource = resource;
            Tenant = tenant;
            Verb = verb;
        }
    }
}
