// *** WARNING: this file was generated by pulumi-language-dotnet. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.Cape.Storage
{
    public static class GetSkus
    {
        public static Task<GetSkusResult> InvokeAsync(GetSkusArgs? args = null, InvokeOptions? options = null)
            => global::Pulumi.Deployment.Instance.InvokeAsync<GetSkusResult>("cape:storage:getSkus", args ?? new GetSkusArgs(), options.WithDefaults());

        public static Output<GetSkusResult> Invoke(GetSkusInvokeArgs? args = null, InvokeOptions? options = null)
            => global::Pulumi.Deployment.Instance.Invoke<GetSkusResult>("cape:storage:getSkus", args ?? new GetSkusInvokeArgs(), options.WithDefaults());

        public static Output<GetSkusResult> Invoke(GetSkusInvokeArgs args, InvokeOutputOptions options)
            => global::Pulumi.Deployment.Instance.Invoke<GetSkusResult>("cape:storage:getSkus", args ?? new GetSkusInvokeArgs(), options.WithDefaults());
    }


    public sealed class GetSkusArgs : global::Pulumi.InvokeArgs
    {
        [Input("labels")]
        public string? Labels { get; set; }

        [Input("limit")]
        public int? Limit { get; set; }

        [Input("skipToken")]
        public string? SkipToken { get; set; }

        [Input("tenant")]
        public string? Tenant { get; set; }

        public GetSkusArgs()
        {
        }
        public static new GetSkusArgs Empty => new GetSkusArgs();
    }

    public sealed class GetSkusInvokeArgs : global::Pulumi.InvokeArgs
    {
        [Input("labels")]
        public Input<string>? Labels { get; set; }

        [Input("limit")]
        public Input<int>? Limit { get; set; }

        [Input("skipToken")]
        public Input<string>? SkipToken { get; set; }

        [Input("tenant")]
        public Input<string>? Tenant { get; set; }

        public GetSkusInvokeArgs()
        {
        }
        public static new GetSkusInvokeArgs Empty => new GetSkusInvokeArgs();
    }


    [OutputType]
    public sealed class GetSkusResult
    {
        public readonly ImmutableArray<Pulumi.Cape.Schemas.Outputs.StorageSku> Items;
        public readonly Pulumi.Cape.Schemas.Outputs.ResponseMetadata Metadata;

        [OutputConstructor]
        private GetSkusResult(
            ImmutableArray<Pulumi.Cape.Schemas.Outputs.StorageSku> items,

            Pulumi.Cape.Schemas.Outputs.ResponseMetadata metadata)
        {
            Items = items;
            Metadata = metadata;
        }
    }
}
