// *** WARNING: this file was generated by pulumi-language-nodejs. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from "@pulumi/pulumi";
import * as utilities from "../utilities";

// Export members:
export { InternetNatGatewayInstanceArgs } from "./internetNatGatewayInstance";
export type InternetNatGatewayInstance = import("./internetNatGatewayInstance").InternetNatGatewayInstance;
export const InternetNatGatewayInstance: typeof import("./internetNatGatewayInstance").InternetNatGatewayInstance = null as any;
utilities.lazyLoad(exports, ["InternetNatGatewayInstance"], () => require("./internetNatGatewayInstance"));


const _module = {
    version: utilities.getVersion(),
    construct: (name: string, type: string, urn: string): pulumi.Resource => {
        switch (type) {
            case "cape:natgateway:InternetNatGatewayInstance":
                return new InternetNatGatewayInstance(name, <any>undefined, { urn })
            default:
                throw new Error(`unknown resource type ${type}`);
        }
    },
};
pulumi.runtime.registerResourceModule("cape", "natgateway", _module)
