// *** WARNING: this file was generated by pulumi-language-dotnet. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.Cape.Schemas.Inputs
{

    /// <summary>
    /// References the SKU used for this block. If a reference to the source image is used as the base for creating this block storage.
    /// </summary>
    public sealed class BlockStorageSpecArgs : global::Pulumi.ResourceArgs
    {
        /// <summary>
        /// Size of the block storage in GB.
        /// </summary>
        [Input("sizeGB", required: true)]
        public Input<int> SizeGB { get; set; } = null!;

        /// <summary>
        /// Reference to the SKU of the block storage.
        /// </summary>
        [Input("skuRef", required: true)]
        public Input<Inputs.ReferenceArgs> SkuRef { get; set; } = null!;

        /// <summary>
        /// Reference to the source image used as the base for creating the block storage.
        /// </summary>
        [Input("sourceImageRef")]
        public Input<Inputs.ReferenceArgs>? SourceImageRef { get; set; }

        public BlockStorageSpecArgs()
        {
        }
        public static new BlockStorageSpecArgs Empty => new BlockStorageSpecArgs();
    }
}
