// *** WARNING: this file was generated by pulumi-language-dotnet. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.Cape.Schemas.Inputs
{

    /// <summary>
    /// Combined IPv4 and IPv6 CIDR block for a subnet. Depending on the network configuration, either the IPv4 or IPv6 range can be omitted. So the following combinations are possible: * IPv4 only * IPv6 only * IPv4 and IPv6 (Dual Stack)
    /// </summary>
    public sealed class CidrArgs : global::Pulumi.ResourceArgs
    {
        /// <summary>
        /// IPv4 CIDR block for the subnet.
        /// </summary>
        [Input("ipv4")]
        public Input<string>? Ipv4 { get; set; }

        /// <summary>
        /// IPv6 CIDR block for the subnet.
        /// </summary>
        [Input("ipv6")]
        public Input<string>? Ipv6 { get; set; }

        public CidrArgs()
        {
        }
        public static new CidrArgs Empty => new CidrArgs();
    }
}
