// *** WARNING: this file was generated by pulumi-language-dotnet. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.Cape.Schemas.Inputs
{

    /// <summary>
    /// Specification of the instance, including its SKU, network configuration, and storage options.
    /// </summary>
    public sealed class InstanceSpecArgs : global::Pulumi.ResourceArgs
    {
        [Input("additionalNicRefs")]
        private InputList<Inputs.ReferenceArgs>? _additionalNicRefs;

        /// <summary>
        /// Additional NICs attached to this instance
        /// </summary>
        public InputList<Inputs.ReferenceArgs> AdditionalNicRefs
        {
            get => _additionalNicRefs ?? (_additionalNicRefs = new InputList<Inputs.ReferenceArgs>());
            set => _additionalNicRefs = value;
        }

        /// <summary>
        /// Anti-affinity group to which this instance belongs. Instances in the same anti-affinity group are placed on different physical hosts. The number of maximum instances in an anti-affinity group is provider-specific.
        /// </summary>
        [Input("antiAffinityGroup")]
        public Input<string>? AntiAffinityGroup { get; set; }

        /// <summary>
        /// Reference to the block storage used to store the boot volume of the instance.
        /// </summary>
        [Input("bootVolume", required: true)]
        public Input<Inputs.VolumeReferenceArgs> BootVolume { get; set; } = null!;

        [Input("dataVolumes")]
        private InputList<Inputs.VolumeReferenceArgs>? _dataVolumes;
        public InputList<Inputs.VolumeReferenceArgs> DataVolumes
        {
            get => _dataVolumes ?? (_dataVolumes = new InputList<Inputs.VolumeReferenceArgs>());
            set => _dataVolumes = value;
        }

        /// <summary>
        /// Reference to the primary NIC attached to this instance.
        /// </summary>
        [Input("primaryNicRef")]
        public Input<Inputs.ReferenceArgs>? PrimaryNicRef { get; set; }

        /// <summary>
        /// Reference to the security group associated with this instance.
        /// </summary>
        [Input("securityGroupRef")]
        public Input<Inputs.ReferenceArgs>? SecurityGroupRef { get; set; }

        /// <summary>
        /// Reference to the SKU of the instance.
        /// </summary>
        [Input("skuRef", required: true)]
        public Input<Inputs.ReferenceArgs> SkuRef { get; set; } = null!;

        [Input("sshKeys")]
        private InputList<string>? _sshKeys;

        /// <summary>
        /// Provider-specific references to SSH keys used in cloud-init vendorData. These references are used to inject SSH public keys during instance initialization through cloud-init's vendor data configuration.
        /// </summary>
        public InputList<string> SshKeys
        {
            get => _sshKeys ?? (_sshKeys = new InputList<string>());
            set => _sshKeys = value;
        }

        /// <summary>
        /// Cloud-init user data for instance initialization Example cloud-init user configuration with SSH key:
        /// </summary>
        [Input("userData")]
        public Input<string>? UserData { get; set; }

        /// <summary>
        /// Reference to a specific zone within a region
        /// </summary>
        [Input("zone", required: true)]
        public Input<string> Zone { get; set; } = null!;

        public InstanceSpecArgs()
        {
        }
        public static new InstanceSpecArgs Empty => new InstanceSpecArgs();
    }
}
