// *** WARNING: this file was generated by pulumi-language-dotnet. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.Cape.Schemas.Inputs
{

    /// <summary>
    /// Specification of the kubernetes node pool, including its configuration and network settings. Since the node pool is, all nodes in the pool have a IP address and are accessible from the internet.
    /// </summary>
    public sealed class KubernetesNodePoolSpecArgs : global::Pulumi.ResourceArgs
    {
        /// <summary>
        /// The number of instances in the node pool. This field is required to specify the number of nodes in the node pool.
        /// </summary>
        [Input("instances", required: true)]
        public Input<int> Instances { get; set; } = null!;

        /// <summary>
        /// Template for creating nodes in the node pool. The template includes the instance SKU, subnet, and zone in which the nodes will be created. The SKU must be one of the available compute SKUs in the region.
        /// </summary>
        [Input("nodeTemplate", required: true)]
        public Input<Inputs.KubernetesNodeTemplateArgs> NodeTemplate { get; set; } = null!;

        [Input("taints")]
        private InputList<Inputs.KubernetesNodeTaintArgs>? _taints;

        /// <summary>
        /// List of taints to apply to the nodes in the node pool. Taints are used to mark nodes as unsuitable for certain workloads, allowing for more fine-grained control over scheduling.
        /// </summary>
        public InputList<Inputs.KubernetesNodeTaintArgs> Taints
        {
            get => _taints ?? (_taints = new InputList<Inputs.KubernetesNodeTaintArgs>());
            set => _taints = value;
        }

        public KubernetesNodePoolSpecArgs()
        {
        }
        public static new KubernetesNodePoolSpecArgs Empty => new KubernetesNodePoolSpecArgs();
    }
}
