// *** WARNING: this file was generated by pulumi-language-dotnet. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.Cape.Schemas.Inputs
{

    /// <summary>
    /// Represents a taint applied to the nodes in the node pool. Taints are used to control which pods can be scheduled on the nodes. A taint consists of a key, value, and effect.
    /// </summary>
    public sealed class KubernetesNodeTaintArgs : global::Pulumi.ResourceArgs
    {
        /// <summary>
        /// The effect of the taint. The effect determines how the taint is applied to the nodes in the node pool. For details on the effects, see the (kubernetes documentation on taints and tolerations)[https://kubernetes.io/docs/concepts/scheduling-eviction/taint-and-toleration/].
        /// </summary>
        [Input("effect", required: true)]
        public Input<string> Effect { get; set; } = null!;

        /// <summary>
        /// The key of the taint. The key is used to identify the taint and is used in conjunction with the value and effect.
        /// </summary>
        [Input("key", required: true)]
        public Input<string> Key { get; set; } = null!;

        /// <summary>
        /// The value of the taint. The value is used to identify the taint and is used in conjunction with the key and effect.
        /// </summary>
        [Input("value", required: true)]
        public Input<string> Value { get; set; } = null!;

        public KubernetesNodeTaintArgs()
        {
        }
        public static new KubernetesNodeTaintArgs Empty => new KubernetesNodeTaintArgs();
    }
}
