// *** WARNING: this file was generated by pulumi-language-dotnet. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.Cape.Schemas.Inputs
{

    /// <summary>
    /// Defines the specification for a Network Load Balancer. A Load Balancer can have multiple frontends, where each frontend may target multiple backend instances. Frontend ports and protocols must be unique to ensure proper routing. The NIC associated with the proxy determines whether the Load Balancer is internal or external.
    /// </summary>
    public sealed class NetworkLoadBalancerSpecArgs : global::Pulumi.ResourceArgs
    {
        /// <summary>
        /// Backend port to which the load balancer will be forwarding the traffic to
        /// </summary>
        [Input("backendPort")]
        public Input<int>? BackendPort { get; set; }

        /// <summary>
        /// Frontend port to which the load balancer will be listening on
        /// </summary>
        [Input("frontendPort")]
        public Input<int>? FrontendPort { get; set; }

        [Input("frontends", required: true)]
        private InputList<Inputs.NetworkLoadBalancerFrontendArgs>? _frontends;
        public InputList<Inputs.NetworkLoadBalancerFrontendArgs> Frontends
        {
            get => _frontends ?? (_frontends = new InputList<Inputs.NetworkLoadBalancerFrontendArgs>());
            set => _frontends = value;
        }

        /// <summary>
        /// Reference to the NIC attached to the load balancer.
        /// </summary>
        [Input("nicRef", required: true)]
        public Input<Inputs.ReferenceArgs> NicRef { get; set; } = null!;

        /// <summary>
        /// Reference to the security group associated with this instance.
        /// </summary>
        [Input("securityGroupRef")]
        public Input<Inputs.ReferenceArgs>? SecurityGroupRef { get; set; }

        public NetworkLoadBalancerSpecArgs()
        {
        }
        public static new NetworkLoadBalancerSpecArgs Empty => new NetworkLoadBalancerSpecArgs();
    }
}
