// *** WARNING: this file was generated by pulumi-language-dotnet. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.Cape.Schemas.Inputs
{

    /// <summary>
    /// Specification of the public IP.
    /// </summary>
    public sealed class PublicIpSpecArgs : global::Pulumi.ResourceArgs
    {
        /// <summary>
        /// The public IP address in case of BYOIP.
        /// </summary>
        [Input("address")]
        public Input<string>? Address { get; set; }

        /// <summary>
        /// IP version of the address
        /// </summary>
        [Input("version", required: true)]
        public Input<string> Version { get; set; } = null!;

        public PublicIpSpecArgs()
        {
        }
        public static new PublicIpSpecArgs Empty => new PublicIpSpecArgs();
    }
}
