// *** WARNING: this file was generated by pulumi-language-dotnet. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.Cape.Schemas.Inputs
{

    /// <summary>
    /// Role assignment for a user account. The role is assigned to the user account in the context of the specified scopes.
    /// </summary>
    public sealed class RoleAssignmentSpecArgs : global::Pulumi.ResourceArgs
    {
        [Input("roles", required: true)]
        private InputList<string>? _roles;

        /// <summary>
        /// List of assigned role names
        /// </summary>
        public InputList<string> Roles
        {
            get => _roles ?? (_roles = new InputList<string>());
            set => _roles = value;
        }

        [Input("scopes", required: true)]
        private InputList<Inputs.RoleAssignmentScopeArgs>? _scopes;

        /// <summary>
        /// List of scopes (e.g., tenant, workspace) for the role assignment
        /// </summary>
        public InputList<Inputs.RoleAssignmentScopeArgs> Scopes
        {
            get => _scopes ?? (_scopes = new InputList<Inputs.RoleAssignmentScopeArgs>());
            set => _scopes = value;
        }

        [Input("subs", required: true)]
        private InputList<string>? _subs;

        /// <summary>
        /// List of subject IDs (from JWT) to whom the roles are assigned, A wildcard `*` can be used to represent all users of the tenant scopes
        /// </summary>
        public InputList<string> Subs
        {
            get => _subs ?? (_subs = new InputList<string>());
            set => _subs = value;
        }

        public RoleAssignmentSpecArgs()
        {
        }
        public static new RoleAssignmentSpecArgs Empty => new RoleAssignmentSpecArgs();
    }
}
