// *** WARNING: this file was generated by pulumi-language-dotnet. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.Cape.Schemas.Inputs
{

    /// <summary>
    /// Represents a connection between a Block Storage and an a user of the block storage.
    /// </summary>
    public sealed class VolumeReferenceArgs : global::Pulumi.ResourceArgs
    {
        /// <summary>
        /// Reference to the block storage used to store the volume.
        /// </summary>
        [Input("deviceRef", required: true)]
        public Input<Inputs.ReferenceArgs> DeviceRef { get; set; } = null!;

        /// <summary>
        /// The connection type depends on the type of device and type of block storage.
        /// </summary>
        [Input("type")]
        public Input<string>? Type { get; set; }

        public VolumeReferenceArgs()
        {
            Type = "virtio";
        }
        public static new VolumeReferenceArgs Empty => new VolumeReferenceArgs();
    }
}
