// *** WARNING: this file was generated by pulumi-language-java. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

package com.pulumi.cape.natgateway;

import com.pulumi.cape.Utilities;
import com.pulumi.cape.natgateway.InternetNatGatewayInstanceArgs;
import com.pulumi.cape.schemas.outputs.InternetNatGatewayInstanceSpec;
import com.pulumi.cape.schemas.outputs.InternetNatGatewayInstanceStatus;
import com.pulumi.cape.schemas.outputs.RegionalWorkspaceResourceMetadata;
import com.pulumi.core.Output;
import com.pulumi.core.annotations.Export;
import com.pulumi.core.annotations.ResourceType;
import com.pulumi.core.internal.Codegen;
import java.lang.String;
import java.util.Map;
import java.util.Optional;
import javax.annotation.Nullable;

/**
 * An InternetNatGatewayInstance is a resource that provides internet access to a subnet by mangling the source IP address of outgoing packets. This allows instances in the subnet to access the internet while keeping their private IP addresses hidden. The InternetNatGatewayInstance is used in conjunction with a RouteTable to enable internet connectivity.
 * 
 */
@ResourceType(type="cape:natgateway:InternetNatGatewayInstance")
public class InternetNatGatewayInstance extends com.pulumi.resources.CustomResource {
    /**
     * User-defined key/value pairs that are mutable and can be used to add annotations. The number of annotations is eventually limited by the CSP.
     * 
     */
    @Export(name="annotations", refs={Map.class,String.class}, tree="[0,1,1]")
    private Output</* @Nullable */ Map<String,String>> annotations;

    /**
     * @return User-defined key/value pairs that are mutable and can be used to add annotations. The number of annotations is eventually limited by the CSP.
     * 
     */
    public Output<Optional<Map<String,String>>> annotations() {
        return Codegen.optional(this.annotations);
    }
    /**
     * User-defined key/value pairs that are mutable and can be used to add extensions. Extensions are subject to validation by the CSP, and any value that is not accepted will be rejected during admission.
     * 
     */
    @Export(name="extensions", refs={Map.class,String.class}, tree="[0,1,1]")
    private Output</* @Nullable */ Map<String,String>> extensions;

    /**
     * @return User-defined key/value pairs that are mutable and can be used to add extensions. Extensions are subject to validation by the CSP, and any value that is not accepted will be rejected during admission.
     * 
     */
    public Output<Optional<Map<String,String>>> extensions() {
        return Codegen.optional(this.extensions);
    }
    /**
     * User-defined key/value pairs that are mutable and can be used to organize and categorize resources. They can be used to filter resources. The number of labels is eventually limited by the CSP.
     * 
     */
    @Export(name="labels", refs={Map.class,String.class}, tree="[0,1,1]")
    private Output</* @Nullable */ Map<String,String>> labels;

    /**
     * @return User-defined key/value pairs that are mutable and can be used to organize and categorize resources. They can be used to filter resources. The number of labels is eventually limited by the CSP.
     * 
     */
    public Output<Optional<Map<String,String>>> labels() {
        return Codegen.optional(this.labels);
    }
    /**
     * Metadata for regional resources with name, permission, modification, type, tenant and workspace and region information.
     * 
     */
    @Export(name="metadata", refs={RegionalWorkspaceResourceMetadata.class}, tree="[0]")
    private Output<RegionalWorkspaceResourceMetadata> metadata;

    /**
     * @return Metadata for regional resources with name, permission, modification, type, tenant and workspace and region information.
     * 
     */
    public Output<RegionalWorkspaceResourceMetadata> metadata() {
        return this.metadata;
    }
    /**
     * The internet gateway will allocate a public IPv4 address. The NAT Gateway instance will be created in the specified zone using the specified public IP address and network interface. This implies the NAT Gateway instance will inherit the availability of the zone and not scale beyond the capability of a compute instance. The NIC needs to be in the same zone as the NAT Gateway instance. If the NIC has a public IP address, the NAT Gateway instance will report this as an error.
     * 
     */
    @Export(name="spec", refs={InternetNatGatewayInstanceSpec.class}, tree="[0]")
    private Output<InternetNatGatewayInstanceSpec> spec;

    /**
     * @return The internet gateway will allocate a public IPv4 address. The NAT Gateway instance will be created in the specified zone using the specified public IP address and network interface. This implies the NAT Gateway instance will inherit the availability of the zone and not scale beyond the capability of a compute instance. The NIC needs to be in the same zone as the NAT Gateway instance. If the NIC has a public IP address, the NAT Gateway instance will report this as an error.
     * 
     */
    public Output<InternetNatGatewayInstanceSpec> spec() {
        return this.spec;
    }
    /**
     * Current status of the resource
     * 
     */
    @Export(name="status", refs={InternetNatGatewayInstanceStatus.class}, tree="[0]")
    private Output<InternetNatGatewayInstanceStatus> status;

    /**
     * @return Current status of the resource
     * 
     */
    public Output<InternetNatGatewayInstanceStatus> status() {
        return this.status;
    }
    /**
     * The tenant for the resource. If omitted, the provider default is used.
     * 
     */
    @Export(name="tenant", refs={String.class}, tree="[0]")
    private Output</* @Nullable */ String> tenant;

    /**
     * @return The tenant for the resource. If omitted, the provider default is used.
     * 
     */
    public Output<Optional<String>> tenant() {
        return Codegen.optional(this.tenant);
    }
    /**
     * The workspace for the resource. If omitted, the provider default is used. Must be configured by either means.
     * 
     */
    @Export(name="workspace", refs={String.class}, tree="[0]")
    private Output</* @Nullable */ String> workspace;

    /**
     * @return The workspace for the resource. If omitted, the provider default is used. Must be configured by either means.
     * 
     */
    public Output<Optional<String>> workspace() {
        return Codegen.optional(this.workspace);
    }

    /**
     *
     * @param name The _unique_ name of the resulting resource.
     */
    public InternetNatGatewayInstance(java.lang.String name) {
        this(name, InternetNatGatewayInstanceArgs.Empty);
    }
    /**
     *
     * @param name The _unique_ name of the resulting resource.
     * @param args The arguments to use to populate this resource's properties.
     */
    public InternetNatGatewayInstance(java.lang.String name, InternetNatGatewayInstanceArgs args) {
        this(name, args, null);
    }
    /**
     *
     * @param name The _unique_ name of the resulting resource.
     * @param args The arguments to use to populate this resource's properties.
     * @param options A bag of options that control this resource's behavior.
     */
    public InternetNatGatewayInstance(java.lang.String name, InternetNatGatewayInstanceArgs args, @Nullable com.pulumi.resources.CustomResourceOptions options) {
        super("cape:natgateway:InternetNatGatewayInstance", name, makeArgs(args, options), makeResourceOptions(options, Codegen.empty()), false);
    }

    private InternetNatGatewayInstance(java.lang.String name, Output<java.lang.String> id, @Nullable com.pulumi.resources.CustomResourceOptions options) {
        super("cape:natgateway:InternetNatGatewayInstance", name, null, makeResourceOptions(options, id), false);
    }

    private static InternetNatGatewayInstanceArgs makeArgs(InternetNatGatewayInstanceArgs args, @Nullable com.pulumi.resources.CustomResourceOptions options) {
        if (options != null && options.getUrn().isPresent()) {
            return null;
        }
        return args == null ? InternetNatGatewayInstanceArgs.Empty : args;
    }

    private static com.pulumi.resources.CustomResourceOptions makeResourceOptions(@Nullable com.pulumi.resources.CustomResourceOptions options, @Nullable Output<java.lang.String> id) {
        var defaultOptions = com.pulumi.resources.CustomResourceOptions.builder()
            .version(Utilities.getVersion())
            .build();
        return com.pulumi.resources.CustomResourceOptions.merge(defaultOptions, options, id);
    }

    /**
     * Get an existing Host resource's state with the given name, ID, and optional extra
     * properties used to qualify the lookup.
     *
     * @param name The _unique_ name of the resulting resource.
     * @param id The _unique_ provider ID of the resource to lookup.
     * @param options Optional settings to control the behavior of the CustomResource.
     */
    public static InternetNatGatewayInstance get(java.lang.String name, Output<java.lang.String> id, @Nullable com.pulumi.resources.CustomResourceOptions options) {
        return new InternetNatGatewayInstance(name, id, options);
    }
}
