// *** WARNING: this file was generated by pulumi-language-java. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

package com.pulumi.cape.network;

import com.pulumi.cape.Utilities;
import com.pulumi.cape.network.inputs.GetSkusArgs;
import com.pulumi.cape.network.inputs.GetSkusPlainArgs;
import com.pulumi.cape.network.outputs.GetSkusResult;
import com.pulumi.core.Output;
import com.pulumi.core.TypeShape;
import com.pulumi.deployment.Deployment;
import com.pulumi.deployment.InvokeOptions;
import com.pulumi.deployment.InvokeOutputOptions;
import java.util.concurrent.CompletableFuture;

public final class NetworkFunctions {
    public static Output<GetSkusResult> getSkus() {
        return getSkus(GetSkusArgs.Empty, InvokeOptions.Empty);
    }
    public static CompletableFuture<GetSkusResult> getSkusPlain() {
        return getSkusPlain(GetSkusPlainArgs.Empty, InvokeOptions.Empty);
    }
    public static Output<GetSkusResult> getSkus(GetSkusArgs args) {
        return getSkus(args, InvokeOptions.Empty);
    }
    public static CompletableFuture<GetSkusResult> getSkusPlain(GetSkusPlainArgs args) {
        return getSkusPlain(args, InvokeOptions.Empty);
    }
    public static Output<GetSkusResult> getSkus(GetSkusArgs args, InvokeOptions options) {
        return Deployment.getInstance().invoke("cape:network:getSkus", TypeShape.of(GetSkusResult.class), args, Utilities.withVersion(options));
    }
    public static Output<GetSkusResult> getSkus(GetSkusArgs args, InvokeOutputOptions options) {
        return Deployment.getInstance().invoke("cape:network:getSkus", TypeShape.of(GetSkusResult.class), args, Utilities.withVersion(options));
    }
    public static CompletableFuture<GetSkusResult> getSkusPlain(GetSkusPlainArgs args, InvokeOptions options) {
        return Deployment.getInstance().invokeAsync("cape:network:getSkus", TypeShape.of(GetSkusResult.class), args, Utilities.withVersion(options));
    }
}
