// *** WARNING: this file was generated by pulumi-language-java. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

package com.pulumi.cape.network;

import com.pulumi.cape.schemas.inputs.NetworkSpecArgs;
import com.pulumi.core.Output;
import com.pulumi.core.annotations.Import;
import com.pulumi.exceptions.MissingRequiredPropertyException;
import java.lang.String;
import java.util.Map;
import java.util.Objects;
import java.util.Optional;
import javax.annotation.Nullable;


public final class NetworkArgs extends com.pulumi.resources.ResourceArgs {

    public static final NetworkArgs Empty = new NetworkArgs();

    /**
     * User-defined key/value pairs that are mutable and can be used to add annotations. The number of annotations is eventually limited by the CSP.
     * 
     */
    @Import(name="annotations")
    private @Nullable Output<Map<String,String>> annotations;

    /**
     * @return User-defined key/value pairs that are mutable and can be used to add annotations. The number of annotations is eventually limited by the CSP.
     * 
     */
    public Optional<Output<Map<String,String>>> annotations() {
        return Optional.ofNullable(this.annotations);
    }

    /**
     * User-defined key/value pairs that are mutable and can be used to add extensions. Extensions are subject to validation by the CSP, and any value that is not accepted will be rejected during admission.
     * 
     */
    @Import(name="extensions")
    private @Nullable Output<Map<String,String>> extensions;

    /**
     * @return User-defined key/value pairs that are mutable and can be used to add extensions. Extensions are subject to validation by the CSP, and any value that is not accepted will be rejected during admission.
     * 
     */
    public Optional<Output<Map<String,String>>> extensions() {
        return Optional.ofNullable(this.extensions);
    }

    /**
     * User-defined key/value pairs that are mutable and can be used to organize and categorize resources. They can be used to filter resources. The number of labels is eventually limited by the CSP.
     * 
     */
    @Import(name="labels")
    private @Nullable Output<Map<String,String>> labels;

    /**
     * @return User-defined key/value pairs that are mutable and can be used to organize and categorize resources. They can be used to filter resources. The number of labels is eventually limited by the CSP.
     * 
     */
    public Optional<Output<Map<String,String>>> labels() {
        return Optional.ofNullable(this.labels);
    }

    /**
     * A Network represents a virtual network that can be used to isolate resources. Key network concepts: * Defines a range of IP addresses for compute resources (e.g. instances) * Enables network segmentation and isolation * Provides common performance configuration across the network using a SKU The `cidr` is the base CIDR block for the network. Additional CIDR blocks can be added to the network using the `additionalCidrs` field. The `additionalCidrs` can be changed after the network is created in case they are not used. The main CIDR block cannot be changed after the network is created. All cidrs must be non-overlapping. The cidrs have to be part of the RFC 1918 address space in case of IPv4 and or RFC 4193. In case the system should automatically assign IP addresses to the network cidrs only the network prefix is required. E.g. to request a /16 IPv4 CIDR block the CIDR block would be `0.0.0.0/16` and for a /56 IPv6 CIDR block the CIDR block would be `::/56`. Most CSP will not allow to use a different IPv6 prefix length than /56. Route tables associated with this network automatically include local routes for all network CIDRs (including `additionalCidrs`). These network-local routes are present by default and cannot be removed.
     * 
     */
    @Import(name="spec", required=true)
    private Output<NetworkSpecArgs> spec;

    /**
     * @return A Network represents a virtual network that can be used to isolate resources. Key network concepts: * Defines a range of IP addresses for compute resources (e.g. instances) * Enables network segmentation and isolation * Provides common performance configuration across the network using a SKU The `cidr` is the base CIDR block for the network. Additional CIDR blocks can be added to the network using the `additionalCidrs` field. The `additionalCidrs` can be changed after the network is created in case they are not used. The main CIDR block cannot be changed after the network is created. All cidrs must be non-overlapping. The cidrs have to be part of the RFC 1918 address space in case of IPv4 and or RFC 4193. In case the system should automatically assign IP addresses to the network cidrs only the network prefix is required. E.g. to request a /16 IPv4 CIDR block the CIDR block would be `0.0.0.0/16` and for a /56 IPv6 CIDR block the CIDR block would be `::/56`. Most CSP will not allow to use a different IPv6 prefix length than /56. Route tables associated with this network automatically include local routes for all network CIDRs (including `additionalCidrs`). These network-local routes are present by default and cannot be removed.
     * 
     */
    public Output<NetworkSpecArgs> spec() {
        return this.spec;
    }

    /**
     * The tenant for the resource. If omitted, the provider default is used.
     * 
     */
    @Import(name="tenant")
    private @Nullable Output<String> tenant;

    /**
     * @return The tenant for the resource. If omitted, the provider default is used.
     * 
     */
    public Optional<Output<String>> tenant() {
        return Optional.ofNullable(this.tenant);
    }

    /**
     * The workspace for the resource. If omitted, the provider default is used. Must be configured by either means.
     * 
     */
    @Import(name="workspace")
    private @Nullable Output<String> workspace;

    /**
     * @return The workspace for the resource. If omitted, the provider default is used. Must be configured by either means.
     * 
     */
    public Optional<Output<String>> workspace() {
        return Optional.ofNullable(this.workspace);
    }

    private NetworkArgs() {}

    private NetworkArgs(NetworkArgs $) {
        this.annotations = $.annotations;
        this.extensions = $.extensions;
        this.labels = $.labels;
        this.spec = $.spec;
        this.tenant = $.tenant;
        this.workspace = $.workspace;
    }

    public static Builder builder() {
        return new Builder();
    }
    public static Builder builder(NetworkArgs defaults) {
        return new Builder(defaults);
    }

    public static final class Builder {
        private NetworkArgs $;

        public Builder() {
            $ = new NetworkArgs();
        }

        public Builder(NetworkArgs defaults) {
            $ = new NetworkArgs(Objects.requireNonNull(defaults));
        }

        /**
         * @param annotations User-defined key/value pairs that are mutable and can be used to add annotations. The number of annotations is eventually limited by the CSP.
         * 
         * @return builder
         * 
         */
        public Builder annotations(@Nullable Output<Map<String,String>> annotations) {
            $.annotations = annotations;
            return this;
        }

        /**
         * @param annotations User-defined key/value pairs that are mutable and can be used to add annotations. The number of annotations is eventually limited by the CSP.
         * 
         * @return builder
         * 
         */
        public Builder annotations(Map<String,String> annotations) {
            return annotations(Output.of(annotations));
        }

        /**
         * @param extensions User-defined key/value pairs that are mutable and can be used to add extensions. Extensions are subject to validation by the CSP, and any value that is not accepted will be rejected during admission.
         * 
         * @return builder
         * 
         */
        public Builder extensions(@Nullable Output<Map<String,String>> extensions) {
            $.extensions = extensions;
            return this;
        }

        /**
         * @param extensions User-defined key/value pairs that are mutable and can be used to add extensions. Extensions are subject to validation by the CSP, and any value that is not accepted will be rejected during admission.
         * 
         * @return builder
         * 
         */
        public Builder extensions(Map<String,String> extensions) {
            return extensions(Output.of(extensions));
        }

        /**
         * @param labels User-defined key/value pairs that are mutable and can be used to organize and categorize resources. They can be used to filter resources. The number of labels is eventually limited by the CSP.
         * 
         * @return builder
         * 
         */
        public Builder labels(@Nullable Output<Map<String,String>> labels) {
            $.labels = labels;
            return this;
        }

        /**
         * @param labels User-defined key/value pairs that are mutable and can be used to organize and categorize resources. They can be used to filter resources. The number of labels is eventually limited by the CSP.
         * 
         * @return builder
         * 
         */
        public Builder labels(Map<String,String> labels) {
            return labels(Output.of(labels));
        }

        /**
         * @param spec A Network represents a virtual network that can be used to isolate resources. Key network concepts: * Defines a range of IP addresses for compute resources (e.g. instances) * Enables network segmentation and isolation * Provides common performance configuration across the network using a SKU The `cidr` is the base CIDR block for the network. Additional CIDR blocks can be added to the network using the `additionalCidrs` field. The `additionalCidrs` can be changed after the network is created in case they are not used. The main CIDR block cannot be changed after the network is created. All cidrs must be non-overlapping. The cidrs have to be part of the RFC 1918 address space in case of IPv4 and or RFC 4193. In case the system should automatically assign IP addresses to the network cidrs only the network prefix is required. E.g. to request a /16 IPv4 CIDR block the CIDR block would be `0.0.0.0/16` and for a /56 IPv6 CIDR block the CIDR block would be `::/56`. Most CSP will not allow to use a different IPv6 prefix length than /56. Route tables associated with this network automatically include local routes for all network CIDRs (including `additionalCidrs`). These network-local routes are present by default and cannot be removed.
         * 
         * @return builder
         * 
         */
        public Builder spec(Output<NetworkSpecArgs> spec) {
            $.spec = spec;
            return this;
        }

        /**
         * @param spec A Network represents a virtual network that can be used to isolate resources. Key network concepts: * Defines a range of IP addresses for compute resources (e.g. instances) * Enables network segmentation and isolation * Provides common performance configuration across the network using a SKU The `cidr` is the base CIDR block for the network. Additional CIDR blocks can be added to the network using the `additionalCidrs` field. The `additionalCidrs` can be changed after the network is created in case they are not used. The main CIDR block cannot be changed after the network is created. All cidrs must be non-overlapping. The cidrs have to be part of the RFC 1918 address space in case of IPv4 and or RFC 4193. In case the system should automatically assign IP addresses to the network cidrs only the network prefix is required. E.g. to request a /16 IPv4 CIDR block the CIDR block would be `0.0.0.0/16` and for a /56 IPv6 CIDR block the CIDR block would be `::/56`. Most CSP will not allow to use a different IPv6 prefix length than /56. Route tables associated with this network automatically include local routes for all network CIDRs (including `additionalCidrs`). These network-local routes are present by default and cannot be removed.
         * 
         * @return builder
         * 
         */
        public Builder spec(NetworkSpecArgs spec) {
            return spec(Output.of(spec));
        }

        /**
         * @param tenant The tenant for the resource. If omitted, the provider default is used.
         * 
         * @return builder
         * 
         */
        public Builder tenant(@Nullable Output<String> tenant) {
            $.tenant = tenant;
            return this;
        }

        /**
         * @param tenant The tenant for the resource. If omitted, the provider default is used.
         * 
         * @return builder
         * 
         */
        public Builder tenant(String tenant) {
            return tenant(Output.of(tenant));
        }

        /**
         * @param workspace The workspace for the resource. If omitted, the provider default is used. Must be configured by either means.
         * 
         * @return builder
         * 
         */
        public Builder workspace(@Nullable Output<String> workspace) {
            $.workspace = workspace;
            return this;
        }

        /**
         * @param workspace The workspace for the resource. If omitted, the provider default is used. Must be configured by either means.
         * 
         * @return builder
         * 
         */
        public Builder workspace(String workspace) {
            return workspace(Output.of(workspace));
        }

        public NetworkArgs build() {
            if ($.spec == null) {
                throw new MissingRequiredPropertyException("NetworkArgs", "spec");
            }
            return $;
        }
    }

}
