// *** WARNING: this file was generated by pulumi-language-java. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

package com.pulumi.cape.network;

import com.pulumi.cape.Utilities;
import com.pulumi.cape.network.NicArgs;
import com.pulumi.cape.schemas.outputs.NicSpec;
import com.pulumi.cape.schemas.outputs.NicStatus;
import com.pulumi.cape.schemas.outputs.RegionalWorkspaceResourceMetadata;
import com.pulumi.core.Output;
import com.pulumi.core.annotations.Export;
import com.pulumi.core.annotations.ResourceType;
import com.pulumi.core.internal.Codegen;
import java.lang.String;
import java.util.Map;
import java.util.Optional;
import javax.annotation.Nullable;

/**
 * The Network Interface Card (NIC) represents a network interface for a compute resource. It is used to connect the compute resource to a network and can have multiple IP addresses associated with it. The NIC can be associated with a public IP address and is linked to a specific subnet within a virtual network.
 * 
 */
@ResourceType(type="cape:network:Nic")
public class Nic extends com.pulumi.resources.CustomResource {
    /**
     * User-defined key/value pairs that are mutable and can be used to add annotations. The number of annotations is eventually limited by the CSP.
     * 
     */
    @Export(name="annotations", refs={Map.class,String.class}, tree="[0,1,1]")
    private Output</* @Nullable */ Map<String,String>> annotations;

    /**
     * @return User-defined key/value pairs that are mutable and can be used to add annotations. The number of annotations is eventually limited by the CSP.
     * 
     */
    public Output<Optional<Map<String,String>>> annotations() {
        return Codegen.optional(this.annotations);
    }
    /**
     * User-defined key/value pairs that are mutable and can be used to add extensions. Extensions are subject to validation by the CSP, and any value that is not accepted will be rejected during admission.
     * 
     */
    @Export(name="extensions", refs={Map.class,String.class}, tree="[0,1,1]")
    private Output</* @Nullable */ Map<String,String>> extensions;

    /**
     * @return User-defined key/value pairs that are mutable and can be used to add extensions. Extensions are subject to validation by the CSP, and any value that is not accepted will be rejected during admission.
     * 
     */
    public Output<Optional<Map<String,String>>> extensions() {
        return Codegen.optional(this.extensions);
    }
    /**
     * User-defined key/value pairs that are mutable and can be used to organize and categorize resources. They can be used to filter resources. The number of labels is eventually limited by the CSP.
     * 
     */
    @Export(name="labels", refs={Map.class,String.class}, tree="[0,1,1]")
    private Output</* @Nullable */ Map<String,String>> labels;

    /**
     * @return User-defined key/value pairs that are mutable and can be used to organize and categorize resources. They can be used to filter resources. The number of labels is eventually limited by the CSP.
     * 
     */
    public Output<Optional<Map<String,String>>> labels() {
        return Codegen.optional(this.labels);
    }
    /**
     * Metadata for regional resources with name, permission, modification, type, tenant and workspace and region information.
     * 
     */
    @Export(name="metadata", refs={RegionalWorkspaceResourceMetadata.class}, tree="[0]")
    private Output<RegionalWorkspaceResourceMetadata> metadata;

    /**
     * @return Metadata for regional resources with name, permission, modification, type, tenant and workspace and region information.
     * 
     */
    public Output<RegionalWorkspaceResourceMetadata> metadata() {
        return this.metadata;
    }
    /**
     * Specification of the Network Interface Card The referenced SKU overwrites the default. In case of different network SKU references the highest possible network SKU reference is used. The network SKU reference might be restricted by the instance size.
     * 
     */
    @Export(name="spec", refs={NicSpec.class}, tree="[0]")
    private Output<NicSpec> spec;

    /**
     * @return Specification of the Network Interface Card The referenced SKU overwrites the default. In case of different network SKU references the highest possible network SKU reference is used. The network SKU reference might be restricted by the instance size.
     * 
     */
    public Output<NicSpec> spec() {
        return this.spec;
    }
    /**
     * Status of the Network Interface Card (NIC). The status includes the current state of the NIC and the IP addresses associated with it. The status is read-only and cannot be modified directly.
     * 
     */
    @Export(name="status", refs={NicStatus.class}, tree="[0]")
    private Output<NicStatus> status;

    /**
     * @return Status of the Network Interface Card (NIC). The status includes the current state of the NIC and the IP addresses associated with it. The status is read-only and cannot be modified directly.
     * 
     */
    public Output<NicStatus> status() {
        return this.status;
    }
    /**
     * The tenant for the resource. If omitted, the provider default is used.
     * 
     */
    @Export(name="tenant", refs={String.class}, tree="[0]")
    private Output</* @Nullable */ String> tenant;

    /**
     * @return The tenant for the resource. If omitted, the provider default is used.
     * 
     */
    public Output<Optional<String>> tenant() {
        return Codegen.optional(this.tenant);
    }
    /**
     * The workspace for the resource. If omitted, the provider default is used. Must be configured by either means.
     * 
     */
    @Export(name="workspace", refs={String.class}, tree="[0]")
    private Output</* @Nullable */ String> workspace;

    /**
     * @return The workspace for the resource. If omitted, the provider default is used. Must be configured by either means.
     * 
     */
    public Output<Optional<String>> workspace() {
        return Codegen.optional(this.workspace);
    }

    /**
     *
     * @param name The _unique_ name of the resulting resource.
     */
    public Nic(java.lang.String name) {
        this(name, NicArgs.Empty);
    }
    /**
     *
     * @param name The _unique_ name of the resulting resource.
     * @param args The arguments to use to populate this resource's properties.
     */
    public Nic(java.lang.String name, NicArgs args) {
        this(name, args, null);
    }
    /**
     *
     * @param name The _unique_ name of the resulting resource.
     * @param args The arguments to use to populate this resource's properties.
     * @param options A bag of options that control this resource's behavior.
     */
    public Nic(java.lang.String name, NicArgs args, @Nullable com.pulumi.resources.CustomResourceOptions options) {
        super("cape:network:Nic", name, makeArgs(args, options), makeResourceOptions(options, Codegen.empty()), false);
    }

    private Nic(java.lang.String name, Output<java.lang.String> id, @Nullable com.pulumi.resources.CustomResourceOptions options) {
        super("cape:network:Nic", name, null, makeResourceOptions(options, id), false);
    }

    private static NicArgs makeArgs(NicArgs args, @Nullable com.pulumi.resources.CustomResourceOptions options) {
        if (options != null && options.getUrn().isPresent()) {
            return null;
        }
        return args == null ? NicArgs.Empty : args;
    }

    private static com.pulumi.resources.CustomResourceOptions makeResourceOptions(@Nullable com.pulumi.resources.CustomResourceOptions options, @Nullable Output<java.lang.String> id) {
        var defaultOptions = com.pulumi.resources.CustomResourceOptions.builder()
            .version(Utilities.getVersion())
            .build();
        return com.pulumi.resources.CustomResourceOptions.merge(defaultOptions, options, id);
    }

    /**
     * Get an existing Host resource's state with the given name, ID, and optional extra
     * properties used to qualify the lookup.
     *
     * @param name The _unique_ name of the resulting resource.
     * @param id The _unique_ provider ID of the resource to lookup.
     * @param options Optional settings to control the behavior of the CustomResource.
     */
    public static Nic get(java.lang.String name, Output<java.lang.String> id, @Nullable com.pulumi.resources.CustomResourceOptions options) {
        return new Nic(name, id, options);
    }
}
