// *** WARNING: this file was generated by pulumi-language-java. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

package com.pulumi.cape.network;

import com.pulumi.cape.Utilities;
import com.pulumi.cape.network.SubnetArgs;
import com.pulumi.cape.schemas.outputs.RegionalNetworkResourceMetadata;
import com.pulumi.cape.schemas.outputs.SubnetSpec;
import com.pulumi.cape.schemas.outputs.SubnetStatus;
import com.pulumi.core.Output;
import com.pulumi.core.annotations.Export;
import com.pulumi.core.annotations.ResourceType;
import com.pulumi.core.internal.Codegen;
import java.lang.String;
import java.util.Map;
import java.util.Optional;
import javax.annotation.Nullable;

/**
 * A Subnet is a logical subdivision of a Network&#39;s IP address space. It defines a range of IP addresses for compute instances and enables network segmentation and isolation. The Subnet resource is used to manage the configuration and status of a subnet within a network. It includes properties such as the CIDR block, zone, and route table reference.
 * 
 */
@ResourceType(type="cape:network:Subnet")
public class Subnet extends com.pulumi.resources.CustomResource {
    /**
     * User-defined key/value pairs that are mutable and can be used to add annotations. The number of annotations is eventually limited by the CSP.
     * 
     */
    @Export(name="annotations", refs={Map.class,String.class}, tree="[0,1,1]")
    private Output</* @Nullable */ Map<String,String>> annotations;

    /**
     * @return User-defined key/value pairs that are mutable and can be used to add annotations. The number of annotations is eventually limited by the CSP.
     * 
     */
    public Output<Optional<Map<String,String>>> annotations() {
        return Codegen.optional(this.annotations);
    }
    /**
     * User-defined key/value pairs that are mutable and can be used to add extensions. Extensions are subject to validation by the CSP, and any value that is not accepted will be rejected during admission.
     * 
     */
    @Export(name="extensions", refs={Map.class,String.class}, tree="[0,1,1]")
    private Output</* @Nullable */ Map<String,String>> extensions;

    /**
     * @return User-defined key/value pairs that are mutable and can be used to add extensions. Extensions are subject to validation by the CSP, and any value that is not accepted will be rejected during admission.
     * 
     */
    public Output<Optional<Map<String,String>>> extensions() {
        return Codegen.optional(this.extensions);
    }
    /**
     * User-defined key/value pairs that are mutable and can be used to organize and categorize resources. They can be used to filter resources. The number of labels is eventually limited by the CSP.
     * 
     */
    @Export(name="labels", refs={Map.class,String.class}, tree="[0,1,1]")
    private Output</* @Nullable */ Map<String,String>> labels;

    /**
     * @return User-defined key/value pairs that are mutable and can be used to organize and categorize resources. They can be used to filter resources. The number of labels is eventually limited by the CSP.
     * 
     */
    public Output<Optional<Map<String,String>>> labels() {
        return Codegen.optional(this.labels);
    }
    /**
     * Metadata for regional resources with name, permission, modification, type, tenant, workspace, network and region information.
     * 
     */
    @Export(name="metadata", refs={RegionalNetworkResourceMetadata.class}, tree="[0]")
    private Output<RegionalNetworkResourceMetadata> metadata;

    /**
     * @return Metadata for regional resources with name, permission, modification, type, tenant, workspace, network and region information.
     * 
     */
    public Output<RegionalNetworkResourceMetadata> metadata() {
        return this.metadata;
    }
    /**
     * The network this resource belongs to.
     * 
     */
    @Export(name="network", refs={String.class}, tree="[0]")
    private Output<String> network;

    /**
     * @return The network this resource belongs to.
     * 
     */
    public Output<String> network() {
        return this.network;
    }
    /**
     * Detailed specification of the subnet. Automatic address assignment is supported, similar to the network configuration. The subnet&#39;s prefix length must be smaller than the network&#39;s prefix length, ensuring proper subdivision of the address space. The first and last IP addresses in the subnet are reserved the network address and broadcast address, respectively. Most CSP will not allow to use a different IPv6 prefix length than /64.
     * 
     */
    @Export(name="spec", refs={SubnetSpec.class}, tree="[0]")
    private Output<SubnetSpec> spec;

    /**
     * @return Detailed specification of the subnet. Automatic address assignment is supported, similar to the network configuration. The subnet&#39;s prefix length must be smaller than the network&#39;s prefix length, ensuring proper subdivision of the address space. The first and last IP addresses in the subnet are reserved the network address and broadcast address, respectively. Most CSP will not allow to use a different IPv6 prefix length than /64.
     * 
     */
    public Output<SubnetSpec> spec() {
        return this.spec;
    }
    /**
     * The status of the subnet, including the current state and any associated IP addresses. The status is read-only and provides information about the subnet&#39;s configuration and health.
     * 
     */
    @Export(name="status", refs={SubnetStatus.class}, tree="[0]")
    private Output<SubnetStatus> status;

    /**
     * @return The status of the subnet, including the current state and any associated IP addresses. The status is read-only and provides information about the subnet&#39;s configuration and health.
     * 
     */
    public Output<SubnetStatus> status() {
        return this.status;
    }
    /**
     * The tenant for the resource. If omitted, the provider default is used.
     * 
     */
    @Export(name="tenant", refs={String.class}, tree="[0]")
    private Output</* @Nullable */ String> tenant;

    /**
     * @return The tenant for the resource. If omitted, the provider default is used.
     * 
     */
    public Output<Optional<String>> tenant() {
        return Codegen.optional(this.tenant);
    }
    /**
     * The workspace for the resource. If omitted, the provider default is used. Must be configured by either means.
     * 
     */
    @Export(name="workspace", refs={String.class}, tree="[0]")
    private Output</* @Nullable */ String> workspace;

    /**
     * @return The workspace for the resource. If omitted, the provider default is used. Must be configured by either means.
     * 
     */
    public Output<Optional<String>> workspace() {
        return Codegen.optional(this.workspace);
    }

    /**
     *
     * @param name The _unique_ name of the resulting resource.
     */
    public Subnet(java.lang.String name) {
        this(name, SubnetArgs.Empty);
    }
    /**
     *
     * @param name The _unique_ name of the resulting resource.
     * @param args The arguments to use to populate this resource's properties.
     */
    public Subnet(java.lang.String name, SubnetArgs args) {
        this(name, args, null);
    }
    /**
     *
     * @param name The _unique_ name of the resulting resource.
     * @param args The arguments to use to populate this resource's properties.
     * @param options A bag of options that control this resource's behavior.
     */
    public Subnet(java.lang.String name, SubnetArgs args, @Nullable com.pulumi.resources.CustomResourceOptions options) {
        super("cape:network:Subnet", name, makeArgs(args, options), makeResourceOptions(options, Codegen.empty()), false);
    }

    private Subnet(java.lang.String name, Output<java.lang.String> id, @Nullable com.pulumi.resources.CustomResourceOptions options) {
        super("cape:network:Subnet", name, null, makeResourceOptions(options, id), false);
    }

    private static SubnetArgs makeArgs(SubnetArgs args, @Nullable com.pulumi.resources.CustomResourceOptions options) {
        if (options != null && options.getUrn().isPresent()) {
            return null;
        }
        return args == null ? SubnetArgs.Empty : args;
    }

    private static com.pulumi.resources.CustomResourceOptions makeResourceOptions(@Nullable com.pulumi.resources.CustomResourceOptions options, @Nullable Output<java.lang.String> id) {
        var defaultOptions = com.pulumi.resources.CustomResourceOptions.builder()
            .version(Utilities.getVersion())
            .build();
        return com.pulumi.resources.CustomResourceOptions.merge(defaultOptions, options, id);
    }

    /**
     * Get an existing Host resource's state with the given name, ID, and optional extra
     * properties used to qualify the lookup.
     *
     * @param name The _unique_ name of the resulting resource.
     * @param id The _unique_ provider ID of the resource to lookup.
     * @param options Optional settings to control the behavior of the CustomResource.
     */
    public static Subnet get(java.lang.String name, Output<java.lang.String> id, @Nullable com.pulumi.resources.CustomResourceOptions options) {
        return new Subnet(name, id, options);
    }
}
