// *** WARNING: this file was generated by pulumi-language-java. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

package com.pulumi.cape.network;

import com.pulumi.cape.schemas.inputs.SubnetSpecArgs;
import com.pulumi.core.Output;
import com.pulumi.core.annotations.Import;
import com.pulumi.exceptions.MissingRequiredPropertyException;
import java.lang.String;
import java.util.Map;
import java.util.Objects;
import java.util.Optional;
import javax.annotation.Nullable;


public final class SubnetArgs extends com.pulumi.resources.ResourceArgs {

    public static final SubnetArgs Empty = new SubnetArgs();

    /**
     * User-defined key/value pairs that are mutable and can be used to add annotations. The number of annotations is eventually limited by the CSP.
     * 
     */
    @Import(name="annotations")
    private @Nullable Output<Map<String,String>> annotations;

    /**
     * @return User-defined key/value pairs that are mutable and can be used to add annotations. The number of annotations is eventually limited by the CSP.
     * 
     */
    public Optional<Output<Map<String,String>>> annotations() {
        return Optional.ofNullable(this.annotations);
    }

    /**
     * User-defined key/value pairs that are mutable and can be used to add extensions. Extensions are subject to validation by the CSP, and any value that is not accepted will be rejected during admission.
     * 
     */
    @Import(name="extensions")
    private @Nullable Output<Map<String,String>> extensions;

    /**
     * @return User-defined key/value pairs that are mutable and can be used to add extensions. Extensions are subject to validation by the CSP, and any value that is not accepted will be rejected during admission.
     * 
     */
    public Optional<Output<Map<String,String>>> extensions() {
        return Optional.ofNullable(this.extensions);
    }

    /**
     * User-defined key/value pairs that are mutable and can be used to organize and categorize resources. They can be used to filter resources. The number of labels is eventually limited by the CSP.
     * 
     */
    @Import(name="labels")
    private @Nullable Output<Map<String,String>> labels;

    /**
     * @return User-defined key/value pairs that are mutable and can be used to organize and categorize resources. They can be used to filter resources. The number of labels is eventually limited by the CSP.
     * 
     */
    public Optional<Output<Map<String,String>>> labels() {
        return Optional.ofNullable(this.labels);
    }

    /**
     * The network this resource belongs to.
     * 
     */
    @Import(name="network", required=true)
    private Output<String> network;

    /**
     * @return The network this resource belongs to.
     * 
     */
    public Output<String> network() {
        return this.network;
    }

    /**
     * Detailed specification of the subnet. Automatic address assignment is supported, similar to the network configuration. The subnet&#39;s prefix length must be smaller than the network&#39;s prefix length, ensuring proper subdivision of the address space. The first and last IP addresses in the subnet are reserved the network address and broadcast address, respectively. Most CSP will not allow to use a different IPv6 prefix length than /64.
     * 
     */
    @Import(name="spec", required=true)
    private Output<SubnetSpecArgs> spec;

    /**
     * @return Detailed specification of the subnet. Automatic address assignment is supported, similar to the network configuration. The subnet&#39;s prefix length must be smaller than the network&#39;s prefix length, ensuring proper subdivision of the address space. The first and last IP addresses in the subnet are reserved the network address and broadcast address, respectively. Most CSP will not allow to use a different IPv6 prefix length than /64.
     * 
     */
    public Output<SubnetSpecArgs> spec() {
        return this.spec;
    }

    /**
     * The tenant for the resource. If omitted, the provider default is used.
     * 
     */
    @Import(name="tenant")
    private @Nullable Output<String> tenant;

    /**
     * @return The tenant for the resource. If omitted, the provider default is used.
     * 
     */
    public Optional<Output<String>> tenant() {
        return Optional.ofNullable(this.tenant);
    }

    /**
     * The workspace for the resource. If omitted, the provider default is used. Must be configured by either means.
     * 
     */
    @Import(name="workspace")
    private @Nullable Output<String> workspace;

    /**
     * @return The workspace for the resource. If omitted, the provider default is used. Must be configured by either means.
     * 
     */
    public Optional<Output<String>> workspace() {
        return Optional.ofNullable(this.workspace);
    }

    private SubnetArgs() {}

    private SubnetArgs(SubnetArgs $) {
        this.annotations = $.annotations;
        this.extensions = $.extensions;
        this.labels = $.labels;
        this.network = $.network;
        this.spec = $.spec;
        this.tenant = $.tenant;
        this.workspace = $.workspace;
    }

    public static Builder builder() {
        return new Builder();
    }
    public static Builder builder(SubnetArgs defaults) {
        return new Builder(defaults);
    }

    public static final class Builder {
        private SubnetArgs $;

        public Builder() {
            $ = new SubnetArgs();
        }

        public Builder(SubnetArgs defaults) {
            $ = new SubnetArgs(Objects.requireNonNull(defaults));
        }

        /**
         * @param annotations User-defined key/value pairs that are mutable and can be used to add annotations. The number of annotations is eventually limited by the CSP.
         * 
         * @return builder
         * 
         */
        public Builder annotations(@Nullable Output<Map<String,String>> annotations) {
            $.annotations = annotations;
            return this;
        }

        /**
         * @param annotations User-defined key/value pairs that are mutable and can be used to add annotations. The number of annotations is eventually limited by the CSP.
         * 
         * @return builder
         * 
         */
        public Builder annotations(Map<String,String> annotations) {
            return annotations(Output.of(annotations));
        }

        /**
         * @param extensions User-defined key/value pairs that are mutable and can be used to add extensions. Extensions are subject to validation by the CSP, and any value that is not accepted will be rejected during admission.
         * 
         * @return builder
         * 
         */
        public Builder extensions(@Nullable Output<Map<String,String>> extensions) {
            $.extensions = extensions;
            return this;
        }

        /**
         * @param extensions User-defined key/value pairs that are mutable and can be used to add extensions. Extensions are subject to validation by the CSP, and any value that is not accepted will be rejected during admission.
         * 
         * @return builder
         * 
         */
        public Builder extensions(Map<String,String> extensions) {
            return extensions(Output.of(extensions));
        }

        /**
         * @param labels User-defined key/value pairs that are mutable and can be used to organize and categorize resources. They can be used to filter resources. The number of labels is eventually limited by the CSP.
         * 
         * @return builder
         * 
         */
        public Builder labels(@Nullable Output<Map<String,String>> labels) {
            $.labels = labels;
            return this;
        }

        /**
         * @param labels User-defined key/value pairs that are mutable and can be used to organize and categorize resources. They can be used to filter resources. The number of labels is eventually limited by the CSP.
         * 
         * @return builder
         * 
         */
        public Builder labels(Map<String,String> labels) {
            return labels(Output.of(labels));
        }

        /**
         * @param network The network this resource belongs to.
         * 
         * @return builder
         * 
         */
        public Builder network(Output<String> network) {
            $.network = network;
            return this;
        }

        /**
         * @param network The network this resource belongs to.
         * 
         * @return builder
         * 
         */
        public Builder network(String network) {
            return network(Output.of(network));
        }

        /**
         * @param spec Detailed specification of the subnet. Automatic address assignment is supported, similar to the network configuration. The subnet&#39;s prefix length must be smaller than the network&#39;s prefix length, ensuring proper subdivision of the address space. The first and last IP addresses in the subnet are reserved the network address and broadcast address, respectively. Most CSP will not allow to use a different IPv6 prefix length than /64.
         * 
         * @return builder
         * 
         */
        public Builder spec(Output<SubnetSpecArgs> spec) {
            $.spec = spec;
            return this;
        }

        /**
         * @param spec Detailed specification of the subnet. Automatic address assignment is supported, similar to the network configuration. The subnet&#39;s prefix length must be smaller than the network&#39;s prefix length, ensuring proper subdivision of the address space. The first and last IP addresses in the subnet are reserved the network address and broadcast address, respectively. Most CSP will not allow to use a different IPv6 prefix length than /64.
         * 
         * @return builder
         * 
         */
        public Builder spec(SubnetSpecArgs spec) {
            return spec(Output.of(spec));
        }

        /**
         * @param tenant The tenant for the resource. If omitted, the provider default is used.
         * 
         * @return builder
         * 
         */
        public Builder tenant(@Nullable Output<String> tenant) {
            $.tenant = tenant;
            return this;
        }

        /**
         * @param tenant The tenant for the resource. If omitted, the provider default is used.
         * 
         * @return builder
         * 
         */
        public Builder tenant(String tenant) {
            return tenant(Output.of(tenant));
        }

        /**
         * @param workspace The workspace for the resource. If omitted, the provider default is used. Must be configured by either means.
         * 
         * @return builder
         * 
         */
        public Builder workspace(@Nullable Output<String> workspace) {
            $.workspace = workspace;
            return this;
        }

        /**
         * @param workspace The workspace for the resource. If omitted, the provider default is used. Must be configured by either means.
         * 
         * @return builder
         * 
         */
        public Builder workspace(String workspace) {
            return workspace(Output.of(workspace));
        }

        public SubnetArgs build() {
            if ($.network == null) {
                throw new MissingRequiredPropertyException("SubnetArgs", "network");
            }
            if ($.spec == null) {
                throw new MissingRequiredPropertyException("SubnetArgs", "spec");
            }
            return $;
        }
    }

}
