// *** WARNING: this file was generated by pulumi-language-dotnet. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.Cape.Network
{
    /// <summary>
    /// An InternetGateway is a resource that provides internet access to a subnet. It is used in conjunction with a RouteTable to enable internet connectivity.
    /// </summary>
    [CapeResourceType("cape:network:InternetGateway")]
    public partial class InternetGateway : global::Pulumi.CustomResource
    {
        /// <summary>
        /// User-defined key/value pairs that are mutable and can be used to add annotations. The number of annotations is eventually limited by the CSP.
        /// </summary>
        [Output("annotations")]
        public Output<ImmutableDictionary<string, string>?> Annotations { get; private set; } = null!;

        /// <summary>
        /// User-defined key/value pairs that are mutable and can be used to add extensions. Extensions are subject to validation by the CSP, and any value that is not accepted will be rejected during admission.
        /// </summary>
        [Output("extensions")]
        public Output<ImmutableDictionary<string, string>?> Extensions { get; private set; } = null!;

        /// <summary>
        /// User-defined key/value pairs that are mutable and can be used to organize and categorize resources. They can be used to filter resources. The number of labels is eventually limited by the CSP.
        /// </summary>
        [Output("labels")]
        public Output<ImmutableDictionary<string, string>?> Labels { get; private set; } = null!;

        /// <summary>
        /// Metadata for regional resources with name, permission, modification, type, tenant and workspace and region information.
        /// </summary>
        [Output("metadata")]
        public Output<Pulumi.Cape.Schemas.Outputs.RegionalWorkspaceResourceMetadata> Metadata { get; private set; } = null!;

        /// <summary>
        /// The internet gateway will use the reserved IP addres. the subnet CIDR block to provide internet access to the subnet.
        /// </summary>
        [Output("spec")]
        public Output<Pulumi.Cape.Schemas.Outputs.InternetGatewaySpec> Spec { get; private set; } = null!;

        /// <summary>
        /// Current status of the resource
        /// </summary>
        [Output("status")]
        public Output<Pulumi.Cape.Schemas.Outputs.InternetGatewayStatus> Status { get; private set; } = null!;

        /// <summary>
        /// The tenant for the resource. If omitted, the provider default is used.
        /// </summary>
        [Output("tenant")]
        public Output<string?> Tenant { get; private set; } = null!;

        /// <summary>
        /// The workspace for the resource. If omitted, the provider default is used. Must be configured by either means.
        /// </summary>
        [Output("workspace")]
        public Output<string?> Workspace { get; private set; } = null!;


        /// <summary>
        /// Create a InternetGateway resource with the given unique name, arguments, and options.
        /// </summary>
        ///
        /// <param name="name">The unique name of the resource</param>
        /// <param name="args">The arguments used to populate this resource's properties</param>
        /// <param name="options">A bag of options that control this resource's behavior</param>
        public InternetGateway(string name, InternetGatewayArgs args, CustomResourceOptions? options = null)
            : base("cape:network:InternetGateway", name, args ?? new InternetGatewayArgs(), MakeResourceOptions(options, ""))
        {
        }

        private InternetGateway(string name, Input<string> id, CustomResourceOptions? options = null)
            : base("cape:network:InternetGateway", name, null, MakeResourceOptions(options, id))
        {
        }

        private static CustomResourceOptions MakeResourceOptions(CustomResourceOptions? options, Input<string>? id)
        {
            var defaultOptions = new CustomResourceOptions
            {
                Version = Utilities.Version,
            };
            var merged = CustomResourceOptions.Merge(defaultOptions, options);
            // Override the ID if one was specified for consistency with other language SDKs.
            merged.Id = id ?? merged.Id;
            return merged;
        }
        /// <summary>
        /// Get an existing InternetGateway resource's state with the given name, ID, and optional extra
        /// properties used to qualify the lookup.
        /// </summary>
        ///
        /// <param name="name">The unique name of the resulting resource.</param>
        /// <param name="id">The unique provider ID of the resource to lookup.</param>
        /// <param name="options">A bag of options that control this resource's behavior</param>
        public static InternetGateway Get(string name, Input<string> id, CustomResourceOptions? options = null)
        {
            return new InternetGateway(name, id, options);
        }
    }

    public sealed class InternetGatewayArgs : global::Pulumi.ResourceArgs
    {
        [Input("annotations")]
        private InputMap<string>? _annotations;

        /// <summary>
        /// User-defined key/value pairs that are mutable and can be used to add annotations. The number of annotations is eventually limited by the CSP.
        /// </summary>
        public InputMap<string> Annotations
        {
            get => _annotations ?? (_annotations = new InputMap<string>());
            set => _annotations = value;
        }

        [Input("extensions")]
        private InputMap<string>? _extensions;

        /// <summary>
        /// User-defined key/value pairs that are mutable and can be used to add extensions. Extensions are subject to validation by the CSP, and any value that is not accepted will be rejected during admission.
        /// </summary>
        public InputMap<string> Extensions
        {
            get => _extensions ?? (_extensions = new InputMap<string>());
            set => _extensions = value;
        }

        [Input("labels")]
        private InputMap<string>? _labels;

        /// <summary>
        /// User-defined key/value pairs that are mutable and can be used to organize and categorize resources. They can be used to filter resources. The number of labels is eventually limited by the CSP.
        /// </summary>
        public InputMap<string> Labels
        {
            get => _labels ?? (_labels = new InputMap<string>());
            set => _labels = value;
        }

        /// <summary>
        /// The internet gateway will use the reserved IP addres. the subnet CIDR block to provide internet access to the subnet.
        /// </summary>
        [Input("spec", required: true)]
        public Input<Pulumi.Cape.Schemas.Inputs.InternetGatewaySpecArgs> Spec { get; set; } = null!;

        /// <summary>
        /// The tenant for the resource. If omitted, the provider default is used.
        /// </summary>
        [Input("tenant")]
        public Input<string>? Tenant { get; set; }

        /// <summary>
        /// The workspace for the resource. If omitted, the provider default is used. Must be configured by either means.
        /// </summary>
        [Input("workspace")]
        public Input<string>? Workspace { get; set; }

        public InternetGatewayArgs()
        {
        }
        public static new InternetGatewayArgs Empty => new InternetGatewayArgs();
    }
}
