// *** WARNING: this file was generated by pulumi-language-dotnet. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.Cape.Network
{
    /// <summary>
    /// The SecurityGroupRule resource defines a reusable network access rule. It can be referenced by multiple Security Groups to enforce consistent policies.
    /// </summary>
    [CapeResourceType("cape:network:SecurityGroupRule")]
    public partial class SecurityGroupRule : global::Pulumi.CustomResource
    {
        /// <summary>
        /// User-defined key/value pairs that are mutable and can be used to add annotations. The number of annotations is eventually limited by the CSP.
        /// </summary>
        [Output("annotations")]
        public Output<ImmutableDictionary<string, string>?> Annotations { get; private set; } = null!;

        /// <summary>
        /// User-defined key/value pairs that are mutable and can be used to add extensions. Extensions are subject to validation by the CSP, and any value that is not accepted will be rejected during admission.
        /// </summary>
        [Output("extensions")]
        public Output<ImmutableDictionary<string, string>?> Extensions { get; private set; } = null!;

        /// <summary>
        /// User-defined key/value pairs that are mutable and can be used to organize and categorize resources. They can be used to filter resources. The number of labels is eventually limited by the CSP.
        /// </summary>
        [Output("labels")]
        public Output<ImmutableDictionary<string, string>?> Labels { get; private set; } = null!;

        /// <summary>
        /// Metadata for regional resources with name, permission, modification, type, tenant and workspace and region information.
        /// </summary>
        [Output("metadata")]
        public Output<Pulumi.Cape.Schemas.Outputs.RegionalWorkspaceResourceMetadata> Metadata { get; private set; } = null!;

        /// <summary>
        /// Specification of a security group rule defining network access permissions. If no version is specified, any IP version will be allowed. If no protocol is specified, any network protocol will be allowed.
        /// </summary>
        [Output("spec")]
        public Output<Pulumi.Cape.Schemas.Outputs.SecurityGroupRuleSpec> Spec { get; private set; } = null!;

        /// <summary>
        /// Current status of the resource
        /// </summary>
        [Output("status")]
        public Output<Pulumi.Cape.Schemas.Outputs.SecurityGroupRuleStatus> Status { get; private set; } = null!;

        /// <summary>
        /// The tenant for the resource. If omitted, the provider default is used.
        /// </summary>
        [Output("tenant")]
        public Output<string?> Tenant { get; private set; } = null!;

        /// <summary>
        /// The workspace for the resource. If omitted, the provider default is used. Must be configured by either means.
        /// </summary>
        [Output("workspace")]
        public Output<string?> Workspace { get; private set; } = null!;


        /// <summary>
        /// Create a SecurityGroupRule resource with the given unique name, arguments, and options.
        /// </summary>
        ///
        /// <param name="name">The unique name of the resource</param>
        /// <param name="args">The arguments used to populate this resource's properties</param>
        /// <param name="options">A bag of options that control this resource's behavior</param>
        public SecurityGroupRule(string name, SecurityGroupRuleArgs args, CustomResourceOptions? options = null)
            : base("cape:network:SecurityGroupRule", name, args ?? new SecurityGroupRuleArgs(), MakeResourceOptions(options, ""))
        {
        }

        private SecurityGroupRule(string name, Input<string> id, CustomResourceOptions? options = null)
            : base("cape:network:SecurityGroupRule", name, null, MakeResourceOptions(options, id))
        {
        }

        private static CustomResourceOptions MakeResourceOptions(CustomResourceOptions? options, Input<string>? id)
        {
            var defaultOptions = new CustomResourceOptions
            {
                Version = Utilities.Version,
            };
            var merged = CustomResourceOptions.Merge(defaultOptions, options);
            // Override the ID if one was specified for consistency with other language SDKs.
            merged.Id = id ?? merged.Id;
            return merged;
        }
        /// <summary>
        /// Get an existing SecurityGroupRule resource's state with the given name, ID, and optional extra
        /// properties used to qualify the lookup.
        /// </summary>
        ///
        /// <param name="name">The unique name of the resulting resource.</param>
        /// <param name="id">The unique provider ID of the resource to lookup.</param>
        /// <param name="options">A bag of options that control this resource's behavior</param>
        public static SecurityGroupRule Get(string name, Input<string> id, CustomResourceOptions? options = null)
        {
            return new SecurityGroupRule(name, id, options);
        }
    }

    public sealed class SecurityGroupRuleArgs : global::Pulumi.ResourceArgs
    {
        [Input("annotations")]
        private InputMap<string>? _annotations;

        /// <summary>
        /// User-defined key/value pairs that are mutable and can be used to add annotations. The number of annotations is eventually limited by the CSP.
        /// </summary>
        public InputMap<string> Annotations
        {
            get => _annotations ?? (_annotations = new InputMap<string>());
            set => _annotations = value;
        }

        [Input("extensions")]
        private InputMap<string>? _extensions;

        /// <summary>
        /// User-defined key/value pairs that are mutable and can be used to add extensions. Extensions are subject to validation by the CSP, and any value that is not accepted will be rejected during admission.
        /// </summary>
        public InputMap<string> Extensions
        {
            get => _extensions ?? (_extensions = new InputMap<string>());
            set => _extensions = value;
        }

        [Input("labels")]
        private InputMap<string>? _labels;

        /// <summary>
        /// User-defined key/value pairs that are mutable and can be used to organize and categorize resources. They can be used to filter resources. The number of labels is eventually limited by the CSP.
        /// </summary>
        public InputMap<string> Labels
        {
            get => _labels ?? (_labels = new InputMap<string>());
            set => _labels = value;
        }

        /// <summary>
        /// Specification of a security group rule defining network access permissions. If no version is specified, any IP version will be allowed. If no protocol is specified, any network protocol will be allowed.
        /// </summary>
        [Input("spec", required: true)]
        public Input<Pulumi.Cape.Schemas.Inputs.SecurityGroupRuleSpecArgs> Spec { get; set; } = null!;

        /// <summary>
        /// The tenant for the resource. If omitted, the provider default is used.
        /// </summary>
        [Input("tenant")]
        public Input<string>? Tenant { get; set; }

        /// <summary>
        /// The workspace for the resource. If omitted, the provider default is used. Must be configured by either means.
        /// </summary>
        [Input("workspace")]
        public Input<string>? Workspace { get; set; }

        public SecurityGroupRuleArgs()
        {
        }
        public static new SecurityGroupRuleArgs Empty => new SecurityGroupRuleArgs();
    }
}
