// *** WARNING: this file was generated by pulumi-language-java. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

package com.pulumi.cape.storage;

import com.pulumi.cape.Utilities;
import com.pulumi.cape.schemas.outputs.ImageSpec;
import com.pulumi.cape.schemas.outputs.ImageStatus;
import com.pulumi.cape.schemas.outputs.RegionalResourceMetadata;
import com.pulumi.cape.storage.ImageArgs;
import com.pulumi.core.Output;
import com.pulumi.core.annotations.Export;
import com.pulumi.core.annotations.ResourceType;
import com.pulumi.core.internal.Codegen;
import java.lang.String;
import java.util.Map;
import java.util.Optional;
import javax.annotation.Nullable;

/**
 * Represents an Image resource that can be used to create a virtual machine.
 * 
 */
@ResourceType(type="cape:storage:Image")
public class Image extends com.pulumi.resources.CustomResource {
    /**
     * User-defined key/value pairs that are mutable and can be used to add annotations. The number of annotations is eventually limited by the CSP.
     * 
     */
    @Export(name="annotations", refs={Map.class,String.class}, tree="[0,1,1]")
    private Output</* @Nullable */ Map<String,String>> annotations;

    /**
     * @return User-defined key/value pairs that are mutable and can be used to add annotations. The number of annotations is eventually limited by the CSP.
     * 
     */
    public Output<Optional<Map<String,String>>> annotations() {
        return Codegen.optional(this.annotations);
    }
    /**
     * User-defined key/value pairs that are mutable and can be used to add extensions. Extensions are subject to validation by the CSP, and any value that is not accepted will be rejected during admission.
     * 
     */
    @Export(name="extensions", refs={Map.class,String.class}, tree="[0,1,1]")
    private Output</* @Nullable */ Map<String,String>> extensions;

    /**
     * @return User-defined key/value pairs that are mutable and can be used to add extensions. Extensions are subject to validation by the CSP, and any value that is not accepted will be rejected during admission.
     * 
     */
    public Output<Optional<Map<String,String>>> extensions() {
        return Codegen.optional(this.extensions);
    }
    /**
     * User-defined key/value pairs that are mutable and can be used to organize and categorize resources. They can be used to filter resources. The number of labels is eventually limited by the CSP.
     * 
     */
    @Export(name="labels", refs={Map.class,String.class}, tree="[0,1,1]")
    private Output</* @Nullable */ Map<String,String>> labels;

    /**
     * @return User-defined key/value pairs that are mutable and can be used to organize and categorize resources. They can be used to filter resources. The number of labels is eventually limited by the CSP.
     * 
     */
    public Output<Optional<Map<String,String>>> labels() {
        return Codegen.optional(this.labels);
    }
    /**
     * Metadata for regional resources with name, permission, modification, type, tenant and region information.
     * 
     */
    @Export(name="metadata", refs={RegionalResourceMetadata.class}, tree="[0]")
    private Output<RegionalResourceMetadata> metadata;

    /**
     * @return Metadata for regional resources with name, permission, modification, type, tenant and region information.
     * 
     */
    public Output<RegionalResourceMetadata> metadata() {
        return this.metadata;
    }
    /**
     * Detailed specification of the Image resource. The Image is derived from a block storage resource identified by `blockStorageRef` and serves as a template for creating compute instances. For additional information, refer to the [Image Handling](/docs/content/Other/image-handling) section.
     * 
     */
    @Export(name="spec", refs={ImageSpec.class}, tree="[0]")
    private Output<ImageSpec> spec;

    /**
     * @return Detailed specification of the Image resource. The Image is derived from a block storage resource identified by `blockStorageRef` and serves as a template for creating compute instances. For additional information, refer to the [Image Handling](/docs/content/Other/image-handling) section.
     * 
     */
    public Output<ImageSpec> spec() {
        return this.spec;
    }
    /**
     * Status of the Image, including the size of the Image in MB.
     * 
     */
    @Export(name="status", refs={ImageStatus.class}, tree="[0]")
    private Output<ImageStatus> status;

    /**
     * @return Status of the Image, including the size of the Image in MB.
     * 
     */
    public Output<ImageStatus> status() {
        return this.status;
    }
    /**
     * The tenant for the resource. If omitted, the provider default is used.
     * 
     */
    @Export(name="tenant", refs={String.class}, tree="[0]")
    private Output</* @Nullable */ String> tenant;

    /**
     * @return The tenant for the resource. If omitted, the provider default is used.
     * 
     */
    public Output<Optional<String>> tenant() {
        return Codegen.optional(this.tenant);
    }

    /**
     *
     * @param name The _unique_ name of the resulting resource.
     */
    public Image(java.lang.String name) {
        this(name, ImageArgs.Empty);
    }
    /**
     *
     * @param name The _unique_ name of the resulting resource.
     * @param args The arguments to use to populate this resource's properties.
     */
    public Image(java.lang.String name, ImageArgs args) {
        this(name, args, null);
    }
    /**
     *
     * @param name The _unique_ name of the resulting resource.
     * @param args The arguments to use to populate this resource's properties.
     * @param options A bag of options that control this resource's behavior.
     */
    public Image(java.lang.String name, ImageArgs args, @Nullable com.pulumi.resources.CustomResourceOptions options) {
        super("cape:storage:Image", name, makeArgs(args, options), makeResourceOptions(options, Codegen.empty()), false);
    }

    private Image(java.lang.String name, Output<java.lang.String> id, @Nullable com.pulumi.resources.CustomResourceOptions options) {
        super("cape:storage:Image", name, null, makeResourceOptions(options, id), false);
    }

    private static ImageArgs makeArgs(ImageArgs args, @Nullable com.pulumi.resources.CustomResourceOptions options) {
        if (options != null && options.getUrn().isPresent()) {
            return null;
        }
        return args == null ? ImageArgs.Empty : args;
    }

    private static com.pulumi.resources.CustomResourceOptions makeResourceOptions(@Nullable com.pulumi.resources.CustomResourceOptions options, @Nullable Output<java.lang.String> id) {
        var defaultOptions = com.pulumi.resources.CustomResourceOptions.builder()
            .version(Utilities.getVersion())
            .build();
        return com.pulumi.resources.CustomResourceOptions.merge(defaultOptions, options, id);
    }

    /**
     * Get an existing Host resource's state with the given name, ID, and optional extra
     * properties used to qualify the lookup.
     *
     * @param name The _unique_ name of the resulting resource.
     * @param id The _unique_ provider ID of the resource to lookup.
     * @param options Optional settings to control the behavior of the CustomResource.
     */
    public static Image get(java.lang.String name, Output<java.lang.String> id, @Nullable com.pulumi.resources.CustomResourceOptions options) {
        return new Image(name, id, options);
    }
}
