// *** WARNING: this file was generated by pulumi-language-java. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

package com.pulumi.cape;

import com.pulumi.core.internal.Codegen;
import java.lang.String;
import java.util.Optional;

public final class Config {

    private static final com.pulumi.Config config = com.pulumi.Config.of("cape");
/**
 * AuthToken is the bearer token that is attached to API calls.
 * 
 */
    public Optional<String> authToken() {
        return Codegen.stringProp("authToken").config(config).get();
    }
/**
 * BaseURL defines the server url for API communication.
 * 
 */
    public String baseURL() {
        return Codegen.stringProp("baseURL").config(config).require();
    }
/**
 * Provider prefix URL for Compute v1
 * 
 */
    public Optional<String> computeProviderPrefix() {
        return Codegen.stringProp("computeProviderPrefix").config(config).def("/providers/seca.compute").get();
    }
/**
 * Provider prefix URL for Storage v1
 * 
 */
    public Optional<String> storageProviderPrefix() {
        return Codegen.stringProp("storageProviderPrefix").config(config).def("/providers/seca.storage").get();
    }
/**
 * Tenant defines the default tenant used for all API calls. May be overwritten in specific calls.
 * 
 */
    public String tenant() {
        return Codegen.stringProp("tenant").config(config).require();
    }
/**
 * Workspace defines a default workspace for all API calls. Can be omitted and given to all objects, or specifically overwritten for calls.
 * 
 */
    public Optional<String> workspace() {
        return Codegen.stringProp("workspace").config(config).get();
    }
/**
 * Provider prefix URL for Workspace v1
 * 
 */
    public Optional<String> workspaceProviderPrefix() {
        return Codegen.stringProp("workspaceProviderPrefix").config(config).def("/providers/seca.workspace").get();
    }
}
