// *** WARNING: this file was generated by pulumi-language-nodejs. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from "@pulumi/pulumi";
import * as inputs from "../types/input";
import * as outputs from "../types/output";
import * as utilities from "../utilities";

/**
 * Role represents a set of permissions that can be assigned to users.
 */
export class Role extends pulumi.CustomResource {
    /**
     * Get an existing Role resource's state with the given name, ID, and optional extra
     * properties used to qualify the lookup.
     *
     * @param name The _unique_ name of the resulting resource.
     * @param id The _unique_ provider ID of the resource to lookup.
     * @param opts Optional settings to control the behavior of the CustomResource.
     */
    public static get(name: string, id: pulumi.Input<pulumi.ID>, opts?: pulumi.CustomResourceOptions): Role {
        return new Role(name, undefined as any, { ...opts, id: id });
    }

    /** @internal */
    public static readonly __pulumiType = 'cape:authorization:Role';

    /**
     * Returns true if the given object is an instance of Role.  This is designed to work even
     * when multiple copies of the Pulumi SDK have been loaded into the same process.
     */
    public static isInstance(obj: any): obj is Role {
        if (obj === undefined || obj === null) {
            return false;
        }
        return obj['__pulumiType'] === Role.__pulumiType;
    }

    /**
     * User-defined key/value pairs that are mutable and can be used to add annotations. The number of annotations is eventually limited by the CSP.
     */
    declare public readonly annotations: pulumi.Output<{[key: string]: string} | undefined>;
    /**
     * User-defined key/value pairs that are mutable and can be used to add extensions. Extensions are subject to validation by the CSP, and any value that is not accepted will be rejected during admission.
     */
    declare public readonly extensions: pulumi.Output<{[key: string]: string} | undefined>;
    /**
     * User-defined key/value pairs that are mutable and can be used to organize and categorize resources. They can be used to filter resources. The number of labels is eventually limited by the CSP.
     */
    declare public readonly labels: pulumi.Output<{[key: string]: string} | undefined>;
    /**
     * Metadata for global resources with name, permission, modification, type, and tenant information.
     */
    declare public /*out*/ readonly metadata: pulumi.Output<outputs.schemas.GlobalTenantResourceMetadata>;
    /**
     * Role specification defined as a list of permissions. Roles are used to define access control policies for a user account using a role assignment.
     */
    declare public readonly spec: pulumi.Output<outputs.schemas.RoleSpec>;
    /**
     * Current status of the resource
     */
    declare public /*out*/ readonly status: pulumi.Output<outputs.schemas.RoleStatus>;
    /**
     * The tenant for the resource. If omitted, the provider default is used.
     */
    declare public readonly tenant: pulumi.Output<string | undefined>;

    /**
     * Create a Role resource with the given unique name, arguments, and options.
     *
     * @param name The _unique_ name of the resource.
     * @param args The arguments to use to populate this resource's properties.
     * @param opts A bag of options that control this resource's behavior.
     */
    constructor(name: string, args: RoleArgs, opts?: pulumi.CustomResourceOptions) {
        let resourceInputs: pulumi.Inputs = {};
        opts = opts || {};
        if (!opts.id) {
            if (args?.spec === undefined && !opts.urn) {
                throw new Error("Missing required property 'spec'");
            }
            resourceInputs["annotations"] = args?.annotations;
            resourceInputs["extensions"] = args?.extensions;
            resourceInputs["labels"] = args?.labels;
            resourceInputs["spec"] = args?.spec;
            resourceInputs["tenant"] = args?.tenant;
            resourceInputs["metadata"] = undefined /*out*/;
            resourceInputs["status"] = undefined /*out*/;
        } else {
            resourceInputs["annotations"] = undefined /*out*/;
            resourceInputs["extensions"] = undefined /*out*/;
            resourceInputs["labels"] = undefined /*out*/;
            resourceInputs["metadata"] = undefined /*out*/;
            resourceInputs["spec"] = undefined /*out*/;
            resourceInputs["status"] = undefined /*out*/;
            resourceInputs["tenant"] = undefined /*out*/;
        }
        opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts);
        super(Role.__pulumiType, name, resourceInputs, opts);
    }
}

/**
 * The set of arguments for constructing a Role resource.
 */
export interface RoleArgs {
    /**
     * User-defined key/value pairs that are mutable and can be used to add annotations. The number of annotations is eventually limited by the CSP.
     */
    annotations?: pulumi.Input<{[key: string]: pulumi.Input<string>} | undefined>;
    /**
     * User-defined key/value pairs that are mutable and can be used to add extensions. Extensions are subject to validation by the CSP, and any value that is not accepted will be rejected during admission.
     */
    extensions?: pulumi.Input<{[key: string]: pulumi.Input<string>} | undefined>;
    /**
     * User-defined key/value pairs that are mutable and can be used to organize and categorize resources. They can be used to filter resources. The number of labels is eventually limited by the CSP.
     */
    labels?: pulumi.Input<{[key: string]: pulumi.Input<string>} | undefined>;
    /**
     * Role specification defined as a list of permissions. Roles are used to define access control policies for a user account using a role assignment.
     */
    spec: pulumi.Input<inputs.schemas.RoleSpecArgs>;
    /**
     * The tenant for the resource. If omitted, the provider default is used.
     */
    tenant?: pulumi.Input<string | undefined>;
}
