// Code generated by pulumi-language-go DO NOT EDIT.
// *** WARNING: Do not edit by hand unless you're certain you know what you are doing! ***

package loadbalancer

import (
	"context"
	"reflect"

	"errors"
	"github.com/pulumi/cape/sdk/go/cape/internal"
	"github.com/pulumi/cape/sdk/go/cape/schemas"
	"github.com/pulumi/pulumi/sdk/v3/go/pulumi"
)

// Represents a Network Load Balancer resource. It is used to distribute incoming network traffic across multiple backend instances based on the specified frontend configuration.
type NetworkLoadBalancer struct {
	pulumi.CustomResourceState

	// User-defined key/value pairs that are mutable and can be used to add annotations. The number of annotations is eventually limited by the CSP.
	Annotations pulumi.StringMapOutput `pulumi:"annotations"`
	// User-defined key/value pairs that are mutable and can be used to add extensions. Extensions are subject to validation by the CSP, and any value that is not accepted will be rejected during admission.
	Extensions pulumi.StringMapOutput `pulumi:"extensions"`
	// User-defined key/value pairs that are mutable and can be used to organize and categorize resources. They can be used to filter resources. The number of labels is eventually limited by the CSP.
	Labels pulumi.StringMapOutput `pulumi:"labels"`
	// Metadata for regional resources with name, permission, modification, type, tenant and workspace and region information.
	Metadata schemas.RegionalWorkspaceResourceMetadataOutput `pulumi:"metadata"`
	// Defines the specification for a Network Load Balancer. A Load Balancer can have multiple frontends, where each frontend may target multiple backend instances. Frontend ports and protocols must be unique to ensure proper routing. The NIC associated with the proxy determines whether the Load Balancer is internal or external.
	Spec schemas.NetworkLoadBalancerSpecOutput `pulumi:"spec"`
	// Represents the status of the Network Load Balancer. It provides information about the health of the backend instances and their readiness to handle traffic.
	Status schemas.NetworkLoadBalancerStatusOutput `pulumi:"status"`
	// The tenant for the resource. If omitted, the provider default is used.
	Tenant pulumi.StringPtrOutput `pulumi:"tenant"`
	// The workspace for the resource. If omitted, the provider default is used. Must be configured by either means.
	Workspace pulumi.StringPtrOutput `pulumi:"workspace"`
}

// NewNetworkLoadBalancer registers a new resource with the given unique name, arguments, and options.
func NewNetworkLoadBalancer(ctx *pulumi.Context,
	name string, args *NetworkLoadBalancerArgs, opts ...pulumi.ResourceOption) (*NetworkLoadBalancer, error) {
	if args == nil {
		return nil, errors.New("missing one or more required arguments")
	}

	if args.Spec == nil {
		return nil, errors.New("invalid value for required argument 'Spec'")
	}
	opts = internal.PkgResourceDefaultOpts(opts)
	var resource NetworkLoadBalancer
	err := ctx.RegisterResource("cape:loadbalancer:NetworkLoadBalancer", name, args, &resource, opts...)
	if err != nil {
		return nil, err
	}
	return &resource, nil
}

// GetNetworkLoadBalancer gets an existing NetworkLoadBalancer resource's state with the given name, ID, and optional
// state properties that are used to uniquely qualify the lookup (nil if not required).
func GetNetworkLoadBalancer(ctx *pulumi.Context,
	name string, id pulumi.IDInput, state *NetworkLoadBalancerState, opts ...pulumi.ResourceOption) (*NetworkLoadBalancer, error) {
	var resource NetworkLoadBalancer
	err := ctx.ReadResource("cape:loadbalancer:NetworkLoadBalancer", name, id, state, &resource, opts...)
	if err != nil {
		return nil, err
	}
	return &resource, nil
}

// Input properties used for looking up and filtering NetworkLoadBalancer resources.
type networkLoadBalancerState struct {
}

type NetworkLoadBalancerState struct {
}

func (NetworkLoadBalancerState) ElementType() reflect.Type {
	return reflect.TypeOf((*networkLoadBalancerState)(nil)).Elem()
}

type networkLoadBalancerArgs struct {
	// User-defined key/value pairs that are mutable and can be used to add annotations. The number of annotations is eventually limited by the CSP.
	Annotations map[string]string `pulumi:"annotations"`
	// User-defined key/value pairs that are mutable and can be used to add extensions. Extensions are subject to validation by the CSP, and any value that is not accepted will be rejected during admission.
	Extensions map[string]string `pulumi:"extensions"`
	// User-defined key/value pairs that are mutable and can be used to organize and categorize resources. They can be used to filter resources. The number of labels is eventually limited by the CSP.
	Labels map[string]string `pulumi:"labels"`
	// Defines the specification for a Network Load Balancer. A Load Balancer can have multiple frontends, where each frontend may target multiple backend instances. Frontend ports and protocols must be unique to ensure proper routing. The NIC associated with the proxy determines whether the Load Balancer is internal or external.
	Spec schemas.NetworkLoadBalancerSpec `pulumi:"spec"`
	// The tenant for the resource. If omitted, the provider default is used.
	Tenant *string `pulumi:"tenant"`
	// The workspace for the resource. If omitted, the provider default is used. Must be configured by either means.
	Workspace *string `pulumi:"workspace"`
}

// The set of arguments for constructing a NetworkLoadBalancer resource.
type NetworkLoadBalancerArgs struct {
	// User-defined key/value pairs that are mutable and can be used to add annotations. The number of annotations is eventually limited by the CSP.
	Annotations pulumi.StringMapInput
	// User-defined key/value pairs that are mutable and can be used to add extensions. Extensions are subject to validation by the CSP, and any value that is not accepted will be rejected during admission.
	Extensions pulumi.StringMapInput
	// User-defined key/value pairs that are mutable and can be used to organize and categorize resources. They can be used to filter resources. The number of labels is eventually limited by the CSP.
	Labels pulumi.StringMapInput
	// Defines the specification for a Network Load Balancer. A Load Balancer can have multiple frontends, where each frontend may target multiple backend instances. Frontend ports and protocols must be unique to ensure proper routing. The NIC associated with the proxy determines whether the Load Balancer is internal or external.
	Spec schemas.NetworkLoadBalancerSpecInput
	// The tenant for the resource. If omitted, the provider default is used.
	Tenant pulumi.StringPtrInput
	// The workspace for the resource. If omitted, the provider default is used. Must be configured by either means.
	Workspace pulumi.StringPtrInput
}

func (NetworkLoadBalancerArgs) ElementType() reflect.Type {
	return reflect.TypeOf((*networkLoadBalancerArgs)(nil)).Elem()
}

type NetworkLoadBalancerInput interface {
	pulumi.Input

	ToNetworkLoadBalancerOutput() NetworkLoadBalancerOutput
	ToNetworkLoadBalancerOutputWithContext(ctx context.Context) NetworkLoadBalancerOutput
}

func (*NetworkLoadBalancer) ElementType() reflect.Type {
	return reflect.TypeOf((**NetworkLoadBalancer)(nil)).Elem()
}

func (i *NetworkLoadBalancer) ToNetworkLoadBalancerOutput() NetworkLoadBalancerOutput {
	return i.ToNetworkLoadBalancerOutputWithContext(context.Background())
}

func (i *NetworkLoadBalancer) ToNetworkLoadBalancerOutputWithContext(ctx context.Context) NetworkLoadBalancerOutput {
	return pulumi.ToOutputWithContext(ctx, i).(NetworkLoadBalancerOutput)
}

// NetworkLoadBalancerArrayInput is an input type that accepts NetworkLoadBalancerArray and NetworkLoadBalancerArrayOutput values.
// You can construct a concrete instance of `NetworkLoadBalancerArrayInput` via:
//
//	NetworkLoadBalancerArray{ NetworkLoadBalancerArgs{...} }
type NetworkLoadBalancerArrayInput interface {
	pulumi.Input

	ToNetworkLoadBalancerArrayOutput() NetworkLoadBalancerArrayOutput
	ToNetworkLoadBalancerArrayOutputWithContext(context.Context) NetworkLoadBalancerArrayOutput
}

type NetworkLoadBalancerArray []NetworkLoadBalancerInput

func (NetworkLoadBalancerArray) ElementType() reflect.Type {
	return reflect.TypeOf((*[]*NetworkLoadBalancer)(nil)).Elem()
}

func (i NetworkLoadBalancerArray) ToNetworkLoadBalancerArrayOutput() NetworkLoadBalancerArrayOutput {
	return i.ToNetworkLoadBalancerArrayOutputWithContext(context.Background())
}

func (i NetworkLoadBalancerArray) ToNetworkLoadBalancerArrayOutputWithContext(ctx context.Context) NetworkLoadBalancerArrayOutput {
	return pulumi.ToOutputWithContext(ctx, i).(NetworkLoadBalancerArrayOutput)
}

// NetworkLoadBalancerMapInput is an input type that accepts NetworkLoadBalancerMap and NetworkLoadBalancerMapOutput values.
// You can construct a concrete instance of `NetworkLoadBalancerMapInput` via:
//
//	NetworkLoadBalancerMap{ "key": NetworkLoadBalancerArgs{...} }
type NetworkLoadBalancerMapInput interface {
	pulumi.Input

	ToNetworkLoadBalancerMapOutput() NetworkLoadBalancerMapOutput
	ToNetworkLoadBalancerMapOutputWithContext(context.Context) NetworkLoadBalancerMapOutput
}

type NetworkLoadBalancerMap map[string]NetworkLoadBalancerInput

func (NetworkLoadBalancerMap) ElementType() reflect.Type {
	return reflect.TypeOf((*map[string]*NetworkLoadBalancer)(nil)).Elem()
}

func (i NetworkLoadBalancerMap) ToNetworkLoadBalancerMapOutput() NetworkLoadBalancerMapOutput {
	return i.ToNetworkLoadBalancerMapOutputWithContext(context.Background())
}

func (i NetworkLoadBalancerMap) ToNetworkLoadBalancerMapOutputWithContext(ctx context.Context) NetworkLoadBalancerMapOutput {
	return pulumi.ToOutputWithContext(ctx, i).(NetworkLoadBalancerMapOutput)
}

type NetworkLoadBalancerOutput struct{ *pulumi.OutputState }

func (NetworkLoadBalancerOutput) ElementType() reflect.Type {
	return reflect.TypeOf((**NetworkLoadBalancer)(nil)).Elem()
}

func (o NetworkLoadBalancerOutput) ToNetworkLoadBalancerOutput() NetworkLoadBalancerOutput {
	return o
}

func (o NetworkLoadBalancerOutput) ToNetworkLoadBalancerOutputWithContext(ctx context.Context) NetworkLoadBalancerOutput {
	return o
}

// User-defined key/value pairs that are mutable and can be used to add annotations. The number of annotations is eventually limited by the CSP.
func (o NetworkLoadBalancerOutput) Annotations() pulumi.StringMapOutput {
	return o.ApplyT(func(v *NetworkLoadBalancer) pulumi.StringMapOutput { return v.Annotations }).(pulumi.StringMapOutput)
}

// User-defined key/value pairs that are mutable and can be used to add extensions. Extensions are subject to validation by the CSP, and any value that is not accepted will be rejected during admission.
func (o NetworkLoadBalancerOutput) Extensions() pulumi.StringMapOutput {
	return o.ApplyT(func(v *NetworkLoadBalancer) pulumi.StringMapOutput { return v.Extensions }).(pulumi.StringMapOutput)
}

// User-defined key/value pairs that are mutable and can be used to organize and categorize resources. They can be used to filter resources. The number of labels is eventually limited by the CSP.
func (o NetworkLoadBalancerOutput) Labels() pulumi.StringMapOutput {
	return o.ApplyT(func(v *NetworkLoadBalancer) pulumi.StringMapOutput { return v.Labels }).(pulumi.StringMapOutput)
}

// Metadata for regional resources with name, permission, modification, type, tenant and workspace and region information.
func (o NetworkLoadBalancerOutput) Metadata() schemas.RegionalWorkspaceResourceMetadataOutput {
	return o.ApplyT(func(v *NetworkLoadBalancer) schemas.RegionalWorkspaceResourceMetadataOutput { return v.Metadata }).(schemas.RegionalWorkspaceResourceMetadataOutput)
}

// Defines the specification for a Network Load Balancer. A Load Balancer can have multiple frontends, where each frontend may target multiple backend instances. Frontend ports and protocols must be unique to ensure proper routing. The NIC associated with the proxy determines whether the Load Balancer is internal or external.
func (o NetworkLoadBalancerOutput) Spec() schemas.NetworkLoadBalancerSpecOutput {
	return o.ApplyT(func(v *NetworkLoadBalancer) schemas.NetworkLoadBalancerSpecOutput { return v.Spec }).(schemas.NetworkLoadBalancerSpecOutput)
}

// Represents the status of the Network Load Balancer. It provides information about the health of the backend instances and their readiness to handle traffic.
func (o NetworkLoadBalancerOutput) Status() schemas.NetworkLoadBalancerStatusOutput {
	return o.ApplyT(func(v *NetworkLoadBalancer) schemas.NetworkLoadBalancerStatusOutput { return v.Status }).(schemas.NetworkLoadBalancerStatusOutput)
}

// The tenant for the resource. If omitted, the provider default is used.
func (o NetworkLoadBalancerOutput) Tenant() pulumi.StringPtrOutput {
	return o.ApplyT(func(v *NetworkLoadBalancer) pulumi.StringPtrOutput { return v.Tenant }).(pulumi.StringPtrOutput)
}

// The workspace for the resource. If omitted, the provider default is used. Must be configured by either means.
func (o NetworkLoadBalancerOutput) Workspace() pulumi.StringPtrOutput {
	return o.ApplyT(func(v *NetworkLoadBalancer) pulumi.StringPtrOutput { return v.Workspace }).(pulumi.StringPtrOutput)
}

type NetworkLoadBalancerArrayOutput struct{ *pulumi.OutputState }

func (NetworkLoadBalancerArrayOutput) ElementType() reflect.Type {
	return reflect.TypeOf((*[]*NetworkLoadBalancer)(nil)).Elem()
}

func (o NetworkLoadBalancerArrayOutput) ToNetworkLoadBalancerArrayOutput() NetworkLoadBalancerArrayOutput {
	return o
}

func (o NetworkLoadBalancerArrayOutput) ToNetworkLoadBalancerArrayOutputWithContext(ctx context.Context) NetworkLoadBalancerArrayOutput {
	return o
}

func (o NetworkLoadBalancerArrayOutput) Index(i pulumi.IntInput) NetworkLoadBalancerOutput {
	return pulumi.All(o, i).ApplyT(func(vs []interface{}) *NetworkLoadBalancer {
		return vs[0].([]*NetworkLoadBalancer)[vs[1].(int)]
	}).(NetworkLoadBalancerOutput)
}

type NetworkLoadBalancerMapOutput struct{ *pulumi.OutputState }

func (NetworkLoadBalancerMapOutput) ElementType() reflect.Type {
	return reflect.TypeOf((*map[string]*NetworkLoadBalancer)(nil)).Elem()
}

func (o NetworkLoadBalancerMapOutput) ToNetworkLoadBalancerMapOutput() NetworkLoadBalancerMapOutput {
	return o
}

func (o NetworkLoadBalancerMapOutput) ToNetworkLoadBalancerMapOutputWithContext(ctx context.Context) NetworkLoadBalancerMapOutput {
	return o
}

func (o NetworkLoadBalancerMapOutput) MapIndex(k pulumi.StringInput) NetworkLoadBalancerOutput {
	return pulumi.All(o, k).ApplyT(func(vs []interface{}) *NetworkLoadBalancer {
		return vs[0].(map[string]*NetworkLoadBalancer)[vs[1].(string)]
	}).(NetworkLoadBalancerOutput)
}

func init() {
	pulumi.RegisterInputType(reflect.TypeOf((*NetworkLoadBalancerInput)(nil)).Elem(), &NetworkLoadBalancer{})
	pulumi.RegisterInputType(reflect.TypeOf((*NetworkLoadBalancerArrayInput)(nil)).Elem(), NetworkLoadBalancerArray{})
	pulumi.RegisterInputType(reflect.TypeOf((*NetworkLoadBalancerMapInput)(nil)).Elem(), NetworkLoadBalancerMap{})
	pulumi.RegisterOutputType(NetworkLoadBalancerOutput{})
	pulumi.RegisterOutputType(NetworkLoadBalancerArrayOutput{})
	pulumi.RegisterOutputType(NetworkLoadBalancerMapOutput{})
}
