// Code generated by pulumi-language-go DO NOT EDIT.
// *** WARNING: Do not edit by hand unless you're certain you know what you are doing! ***

package natgateway

import (
	"context"
	"reflect"

	"errors"
	"github.com/pulumi/cape/sdk/go/cape/internal"
	"github.com/pulumi/cape/sdk/go/cape/schemas"
	"github.com/pulumi/pulumi/sdk/v3/go/pulumi"
)

// An InternetNatGatewayInstance is a resource that provides internet access to a subnet by mangling the source IP address of outgoing packets. This allows instances in the subnet to access the internet while keeping their private IP addresses hidden. The InternetNatGatewayInstance is used in conjunction with a RouteTable to enable internet connectivity.
type InternetNatGatewayInstance struct {
	pulumi.CustomResourceState

	// User-defined key/value pairs that are mutable and can be used to add annotations. The number of annotations is eventually limited by the CSP.
	Annotations pulumi.StringMapOutput `pulumi:"annotations"`
	// User-defined key/value pairs that are mutable and can be used to add extensions. Extensions are subject to validation by the CSP, and any value that is not accepted will be rejected during admission.
	Extensions pulumi.StringMapOutput `pulumi:"extensions"`
	// User-defined key/value pairs that are mutable and can be used to organize and categorize resources. They can be used to filter resources. The number of labels is eventually limited by the CSP.
	Labels pulumi.StringMapOutput `pulumi:"labels"`
	// Metadata for regional resources with name, permission, modification, type, tenant and workspace and region information.
	Metadata schemas.RegionalWorkspaceResourceMetadataOutput `pulumi:"metadata"`
	// The internet gateway will allocate a public IPv4 address. The NAT Gateway instance will be created in the specified zone using the specified public IP address and network interface. This implies the NAT Gateway instance will inherit the availability of the zone and not scale beyond the capability of a compute instance. The NIC needs to be in the same zone as the NAT Gateway instance. If the NIC has a public IP address, the NAT Gateway instance will report this as an error.
	Spec schemas.InternetNatGatewayInstanceSpecOutput `pulumi:"spec"`
	// Current status of the resource
	Status schemas.InternetNatGatewayInstanceStatusOutput `pulumi:"status"`
	// The tenant for the resource. If omitted, the provider default is used.
	Tenant pulumi.StringPtrOutput `pulumi:"tenant"`
	// The workspace for the resource. If omitted, the provider default is used. Must be configured by either means.
	Workspace pulumi.StringPtrOutput `pulumi:"workspace"`
}

// NewInternetNatGatewayInstance registers a new resource with the given unique name, arguments, and options.
func NewInternetNatGatewayInstance(ctx *pulumi.Context,
	name string, args *InternetNatGatewayInstanceArgs, opts ...pulumi.ResourceOption) (*InternetNatGatewayInstance, error) {
	if args == nil {
		return nil, errors.New("missing one or more required arguments")
	}

	if args.Spec == nil {
		return nil, errors.New("invalid value for required argument 'Spec'")
	}
	opts = internal.PkgResourceDefaultOpts(opts)
	var resource InternetNatGatewayInstance
	err := ctx.RegisterResource("cape:natgateway:InternetNatGatewayInstance", name, args, &resource, opts...)
	if err != nil {
		return nil, err
	}
	return &resource, nil
}

// GetInternetNatGatewayInstance gets an existing InternetNatGatewayInstance resource's state with the given name, ID, and optional
// state properties that are used to uniquely qualify the lookup (nil if not required).
func GetInternetNatGatewayInstance(ctx *pulumi.Context,
	name string, id pulumi.IDInput, state *InternetNatGatewayInstanceState, opts ...pulumi.ResourceOption) (*InternetNatGatewayInstance, error) {
	var resource InternetNatGatewayInstance
	err := ctx.ReadResource("cape:natgateway:InternetNatGatewayInstance", name, id, state, &resource, opts...)
	if err != nil {
		return nil, err
	}
	return &resource, nil
}

// Input properties used for looking up and filtering InternetNatGatewayInstance resources.
type internetNatGatewayInstanceState struct {
}

type InternetNatGatewayInstanceState struct {
}

func (InternetNatGatewayInstanceState) ElementType() reflect.Type {
	return reflect.TypeOf((*internetNatGatewayInstanceState)(nil)).Elem()
}

type internetNatGatewayInstanceArgs struct {
	// User-defined key/value pairs that are mutable and can be used to add annotations. The number of annotations is eventually limited by the CSP.
	Annotations map[string]string `pulumi:"annotations"`
	// User-defined key/value pairs that are mutable and can be used to add extensions. Extensions are subject to validation by the CSP, and any value that is not accepted will be rejected during admission.
	Extensions map[string]string `pulumi:"extensions"`
	// User-defined key/value pairs that are mutable and can be used to organize and categorize resources. They can be used to filter resources. The number of labels is eventually limited by the CSP.
	Labels map[string]string `pulumi:"labels"`
	// The internet gateway will allocate a public IPv4 address. The NAT Gateway instance will be created in the specified zone using the specified public IP address and network interface. This implies the NAT Gateway instance will inherit the availability of the zone and not scale beyond the capability of a compute instance. The NIC needs to be in the same zone as the NAT Gateway instance. If the NIC has a public IP address, the NAT Gateway instance will report this as an error.
	Spec schemas.InternetNatGatewayInstanceSpec `pulumi:"spec"`
	// The tenant for the resource. If omitted, the provider default is used.
	Tenant *string `pulumi:"tenant"`
	// The workspace for the resource. If omitted, the provider default is used. Must be configured by either means.
	Workspace *string `pulumi:"workspace"`
}

// The set of arguments for constructing a InternetNatGatewayInstance resource.
type InternetNatGatewayInstanceArgs struct {
	// User-defined key/value pairs that are mutable and can be used to add annotations. The number of annotations is eventually limited by the CSP.
	Annotations pulumi.StringMapInput
	// User-defined key/value pairs that are mutable and can be used to add extensions. Extensions are subject to validation by the CSP, and any value that is not accepted will be rejected during admission.
	Extensions pulumi.StringMapInput
	// User-defined key/value pairs that are mutable and can be used to organize and categorize resources. They can be used to filter resources. The number of labels is eventually limited by the CSP.
	Labels pulumi.StringMapInput
	// The internet gateway will allocate a public IPv4 address. The NAT Gateway instance will be created in the specified zone using the specified public IP address and network interface. This implies the NAT Gateway instance will inherit the availability of the zone and not scale beyond the capability of a compute instance. The NIC needs to be in the same zone as the NAT Gateway instance. If the NIC has a public IP address, the NAT Gateway instance will report this as an error.
	Spec schemas.InternetNatGatewayInstanceSpecInput
	// The tenant for the resource. If omitted, the provider default is used.
	Tenant pulumi.StringPtrInput
	// The workspace for the resource. If omitted, the provider default is used. Must be configured by either means.
	Workspace pulumi.StringPtrInput
}

func (InternetNatGatewayInstanceArgs) ElementType() reflect.Type {
	return reflect.TypeOf((*internetNatGatewayInstanceArgs)(nil)).Elem()
}

type InternetNatGatewayInstanceInput interface {
	pulumi.Input

	ToInternetNatGatewayInstanceOutput() InternetNatGatewayInstanceOutput
	ToInternetNatGatewayInstanceOutputWithContext(ctx context.Context) InternetNatGatewayInstanceOutput
}

func (*InternetNatGatewayInstance) ElementType() reflect.Type {
	return reflect.TypeOf((**InternetNatGatewayInstance)(nil)).Elem()
}

func (i *InternetNatGatewayInstance) ToInternetNatGatewayInstanceOutput() InternetNatGatewayInstanceOutput {
	return i.ToInternetNatGatewayInstanceOutputWithContext(context.Background())
}

func (i *InternetNatGatewayInstance) ToInternetNatGatewayInstanceOutputWithContext(ctx context.Context) InternetNatGatewayInstanceOutput {
	return pulumi.ToOutputWithContext(ctx, i).(InternetNatGatewayInstanceOutput)
}

// InternetNatGatewayInstanceArrayInput is an input type that accepts InternetNatGatewayInstanceArray and InternetNatGatewayInstanceArrayOutput values.
// You can construct a concrete instance of `InternetNatGatewayInstanceArrayInput` via:
//
//	InternetNatGatewayInstanceArray{ InternetNatGatewayInstanceArgs{...} }
type InternetNatGatewayInstanceArrayInput interface {
	pulumi.Input

	ToInternetNatGatewayInstanceArrayOutput() InternetNatGatewayInstanceArrayOutput
	ToInternetNatGatewayInstanceArrayOutputWithContext(context.Context) InternetNatGatewayInstanceArrayOutput
}

type InternetNatGatewayInstanceArray []InternetNatGatewayInstanceInput

func (InternetNatGatewayInstanceArray) ElementType() reflect.Type {
	return reflect.TypeOf((*[]*InternetNatGatewayInstance)(nil)).Elem()
}

func (i InternetNatGatewayInstanceArray) ToInternetNatGatewayInstanceArrayOutput() InternetNatGatewayInstanceArrayOutput {
	return i.ToInternetNatGatewayInstanceArrayOutputWithContext(context.Background())
}

func (i InternetNatGatewayInstanceArray) ToInternetNatGatewayInstanceArrayOutputWithContext(ctx context.Context) InternetNatGatewayInstanceArrayOutput {
	return pulumi.ToOutputWithContext(ctx, i).(InternetNatGatewayInstanceArrayOutput)
}

// InternetNatGatewayInstanceMapInput is an input type that accepts InternetNatGatewayInstanceMap and InternetNatGatewayInstanceMapOutput values.
// You can construct a concrete instance of `InternetNatGatewayInstanceMapInput` via:
//
//	InternetNatGatewayInstanceMap{ "key": InternetNatGatewayInstanceArgs{...} }
type InternetNatGatewayInstanceMapInput interface {
	pulumi.Input

	ToInternetNatGatewayInstanceMapOutput() InternetNatGatewayInstanceMapOutput
	ToInternetNatGatewayInstanceMapOutputWithContext(context.Context) InternetNatGatewayInstanceMapOutput
}

type InternetNatGatewayInstanceMap map[string]InternetNatGatewayInstanceInput

func (InternetNatGatewayInstanceMap) ElementType() reflect.Type {
	return reflect.TypeOf((*map[string]*InternetNatGatewayInstance)(nil)).Elem()
}

func (i InternetNatGatewayInstanceMap) ToInternetNatGatewayInstanceMapOutput() InternetNatGatewayInstanceMapOutput {
	return i.ToInternetNatGatewayInstanceMapOutputWithContext(context.Background())
}

func (i InternetNatGatewayInstanceMap) ToInternetNatGatewayInstanceMapOutputWithContext(ctx context.Context) InternetNatGatewayInstanceMapOutput {
	return pulumi.ToOutputWithContext(ctx, i).(InternetNatGatewayInstanceMapOutput)
}

type InternetNatGatewayInstanceOutput struct{ *pulumi.OutputState }

func (InternetNatGatewayInstanceOutput) ElementType() reflect.Type {
	return reflect.TypeOf((**InternetNatGatewayInstance)(nil)).Elem()
}

func (o InternetNatGatewayInstanceOutput) ToInternetNatGatewayInstanceOutput() InternetNatGatewayInstanceOutput {
	return o
}

func (o InternetNatGatewayInstanceOutput) ToInternetNatGatewayInstanceOutputWithContext(ctx context.Context) InternetNatGatewayInstanceOutput {
	return o
}

// User-defined key/value pairs that are mutable and can be used to add annotations. The number of annotations is eventually limited by the CSP.
func (o InternetNatGatewayInstanceOutput) Annotations() pulumi.StringMapOutput {
	return o.ApplyT(func(v *InternetNatGatewayInstance) pulumi.StringMapOutput { return v.Annotations }).(pulumi.StringMapOutput)
}

// User-defined key/value pairs that are mutable and can be used to add extensions. Extensions are subject to validation by the CSP, and any value that is not accepted will be rejected during admission.
func (o InternetNatGatewayInstanceOutput) Extensions() pulumi.StringMapOutput {
	return o.ApplyT(func(v *InternetNatGatewayInstance) pulumi.StringMapOutput { return v.Extensions }).(pulumi.StringMapOutput)
}

// User-defined key/value pairs that are mutable and can be used to organize and categorize resources. They can be used to filter resources. The number of labels is eventually limited by the CSP.
func (o InternetNatGatewayInstanceOutput) Labels() pulumi.StringMapOutput {
	return o.ApplyT(func(v *InternetNatGatewayInstance) pulumi.StringMapOutput { return v.Labels }).(pulumi.StringMapOutput)
}

// Metadata for regional resources with name, permission, modification, type, tenant and workspace and region information.
func (o InternetNatGatewayInstanceOutput) Metadata() schemas.RegionalWorkspaceResourceMetadataOutput {
	return o.ApplyT(func(v *InternetNatGatewayInstance) schemas.RegionalWorkspaceResourceMetadataOutput { return v.Metadata }).(schemas.RegionalWorkspaceResourceMetadataOutput)
}

// The internet gateway will allocate a public IPv4 address. The NAT Gateway instance will be created in the specified zone using the specified public IP address and network interface. This implies the NAT Gateway instance will inherit the availability of the zone and not scale beyond the capability of a compute instance. The NIC needs to be in the same zone as the NAT Gateway instance. If the NIC has a public IP address, the NAT Gateway instance will report this as an error.
func (o InternetNatGatewayInstanceOutput) Spec() schemas.InternetNatGatewayInstanceSpecOutput {
	return o.ApplyT(func(v *InternetNatGatewayInstance) schemas.InternetNatGatewayInstanceSpecOutput { return v.Spec }).(schemas.InternetNatGatewayInstanceSpecOutput)
}

// Current status of the resource
func (o InternetNatGatewayInstanceOutput) Status() schemas.InternetNatGatewayInstanceStatusOutput {
	return o.ApplyT(func(v *InternetNatGatewayInstance) schemas.InternetNatGatewayInstanceStatusOutput { return v.Status }).(schemas.InternetNatGatewayInstanceStatusOutput)
}

// The tenant for the resource. If omitted, the provider default is used.
func (o InternetNatGatewayInstanceOutput) Tenant() pulumi.StringPtrOutput {
	return o.ApplyT(func(v *InternetNatGatewayInstance) pulumi.StringPtrOutput { return v.Tenant }).(pulumi.StringPtrOutput)
}

// The workspace for the resource. If omitted, the provider default is used. Must be configured by either means.
func (o InternetNatGatewayInstanceOutput) Workspace() pulumi.StringPtrOutput {
	return o.ApplyT(func(v *InternetNatGatewayInstance) pulumi.StringPtrOutput { return v.Workspace }).(pulumi.StringPtrOutput)
}

type InternetNatGatewayInstanceArrayOutput struct{ *pulumi.OutputState }

func (InternetNatGatewayInstanceArrayOutput) ElementType() reflect.Type {
	return reflect.TypeOf((*[]*InternetNatGatewayInstance)(nil)).Elem()
}

func (o InternetNatGatewayInstanceArrayOutput) ToInternetNatGatewayInstanceArrayOutput() InternetNatGatewayInstanceArrayOutput {
	return o
}

func (o InternetNatGatewayInstanceArrayOutput) ToInternetNatGatewayInstanceArrayOutputWithContext(ctx context.Context) InternetNatGatewayInstanceArrayOutput {
	return o
}

func (o InternetNatGatewayInstanceArrayOutput) Index(i pulumi.IntInput) InternetNatGatewayInstanceOutput {
	return pulumi.All(o, i).ApplyT(func(vs []interface{}) *InternetNatGatewayInstance {
		return vs[0].([]*InternetNatGatewayInstance)[vs[1].(int)]
	}).(InternetNatGatewayInstanceOutput)
}

type InternetNatGatewayInstanceMapOutput struct{ *pulumi.OutputState }

func (InternetNatGatewayInstanceMapOutput) ElementType() reflect.Type {
	return reflect.TypeOf((*map[string]*InternetNatGatewayInstance)(nil)).Elem()
}

func (o InternetNatGatewayInstanceMapOutput) ToInternetNatGatewayInstanceMapOutput() InternetNatGatewayInstanceMapOutput {
	return o
}

func (o InternetNatGatewayInstanceMapOutput) ToInternetNatGatewayInstanceMapOutputWithContext(ctx context.Context) InternetNatGatewayInstanceMapOutput {
	return o
}

func (o InternetNatGatewayInstanceMapOutput) MapIndex(k pulumi.StringInput) InternetNatGatewayInstanceOutput {
	return pulumi.All(o, k).ApplyT(func(vs []interface{}) *InternetNatGatewayInstance {
		return vs[0].(map[string]*InternetNatGatewayInstance)[vs[1].(string)]
	}).(InternetNatGatewayInstanceOutput)
}

func init() {
	pulumi.RegisterInputType(reflect.TypeOf((*InternetNatGatewayInstanceInput)(nil)).Elem(), &InternetNatGatewayInstance{})
	pulumi.RegisterInputType(reflect.TypeOf((*InternetNatGatewayInstanceArrayInput)(nil)).Elem(), InternetNatGatewayInstanceArray{})
	pulumi.RegisterInputType(reflect.TypeOf((*InternetNatGatewayInstanceMapInput)(nil)).Elem(), InternetNatGatewayInstanceMap{})
	pulumi.RegisterOutputType(InternetNatGatewayInstanceOutput{})
	pulumi.RegisterOutputType(InternetNatGatewayInstanceArrayOutput{})
	pulumi.RegisterOutputType(InternetNatGatewayInstanceMapOutput{})
}
