// *** WARNING: this file was generated by pulumi-language-java. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

package com.pulumi.cape.objectstorage;

import com.pulumi.cape.Utilities;
import com.pulumi.cape.objectstorage.ObjectStorageAccountArgs;
import com.pulumi.cape.schemas.outputs.GlobalTenantResourceMetadata;
import com.pulumi.cape.schemas.outputs.ObjectStorageAccountStatus;
import com.pulumi.core.Output;
import com.pulumi.core.annotations.Export;
import com.pulumi.core.annotations.ResourceType;
import com.pulumi.core.internal.Codegen;
import java.lang.Object;
import java.lang.String;
import java.util.Map;
import java.util.Optional;
import javax.annotation.Nullable;

/**
 * An object storage account resource, which includes metadata, specification, and status.
 * 
 */
@ResourceType(type="cape:objectstorage:ObjectStorageAccount")
public class ObjectStorageAccount extends com.pulumi.resources.CustomResource {
    /**
     * User-defined key/value pairs that are mutable and can be used to add annotations. The number of annotations is eventually limited by the CSP.
     * 
     */
    @Export(name="annotations", refs={Map.class,String.class}, tree="[0,1,1]")
    private Output</* @Nullable */ Map<String,String>> annotations;

    /**
     * @return User-defined key/value pairs that are mutable and can be used to add annotations. The number of annotations is eventually limited by the CSP.
     * 
     */
    public Output<Optional<Map<String,String>>> annotations() {
        return Codegen.optional(this.annotations);
    }
    /**
     * User-defined key/value pairs that are mutable and can be used to add extensions. Extensions are subject to validation by the CSP, and any value that is not accepted will be rejected during admission.
     * 
     */
    @Export(name="extensions", refs={Map.class,String.class}, tree="[0,1,1]")
    private Output</* @Nullable */ Map<String,String>> extensions;

    /**
     * @return User-defined key/value pairs that are mutable and can be used to add extensions. Extensions are subject to validation by the CSP, and any value that is not accepted will be rejected during admission.
     * 
     */
    public Output<Optional<Map<String,String>>> extensions() {
        return Codegen.optional(this.extensions);
    }
    /**
     * User-defined key/value pairs that are mutable and can be used to organize and categorize resources. They can be used to filter resources. The number of labels is eventually limited by the CSP.
     * 
     */
    @Export(name="labels", refs={Map.class,String.class}, tree="[0,1,1]")
    private Output</* @Nullable */ Map<String,String>> labels;

    /**
     * @return User-defined key/value pairs that are mutable and can be used to organize and categorize resources. They can be used to filter resources. The number of labels is eventually limited by the CSP.
     * 
     */
    public Output<Optional<Map<String,String>>> labels() {
        return Codegen.optional(this.labels);
    }
    /**
     * Metadata for global resources with name, permission, modification, type, and tenant information.
     * 
     */
    @Export(name="metadata", refs={GlobalTenantResourceMetadata.class}, tree="[0]")
    private Output<GlobalTenantResourceMetadata> metadata;

    /**
     * @return Metadata for global resources with name, permission, modification, type, and tenant information.
     * 
     */
    public Output<GlobalTenantResourceMetadata> metadata() {
        return this.metadata;
    }
    /**
     * The specification of an object storage account, including the region and zone.
     * 
     */
    @Export(name="spec", refs={Map.class,String.class,Object.class}, tree="[0,1,2]")
    private Output<Map<String,Object>> spec;

    /**
     * @return The specification of an object storage account, including the region and zone.
     * 
     */
    public Output<Map<String,Object>> spec() {
        return this.spec;
    }
    /**
     * The status of an object storage account, including the access key, secret key, and canonical user ID.
     * 
     */
    @Export(name="status", refs={ObjectStorageAccountStatus.class}, tree="[0]")
    private Output<ObjectStorageAccountStatus> status;

    /**
     * @return The status of an object storage account, including the access key, secret key, and canonical user ID.
     * 
     */
    public Output<ObjectStorageAccountStatus> status() {
        return this.status;
    }
    /**
     * The tenant for the resource. If omitted, the provider default is used.
     * 
     */
    @Export(name="tenant", refs={String.class}, tree="[0]")
    private Output</* @Nullable */ String> tenant;

    /**
     * @return The tenant for the resource. If omitted, the provider default is used.
     * 
     */
    public Output<Optional<String>> tenant() {
        return Codegen.optional(this.tenant);
    }

    /**
     *
     * @param name The _unique_ name of the resulting resource.
     */
    public ObjectStorageAccount(java.lang.String name) {
        this(name, ObjectStorageAccountArgs.Empty);
    }
    /**
     *
     * @param name The _unique_ name of the resulting resource.
     * @param args The arguments to use to populate this resource's properties.
     */
    public ObjectStorageAccount(java.lang.String name, ObjectStorageAccountArgs args) {
        this(name, args, null);
    }
    /**
     *
     * @param name The _unique_ name of the resulting resource.
     * @param args The arguments to use to populate this resource's properties.
     * @param options A bag of options that control this resource's behavior.
     */
    public ObjectStorageAccount(java.lang.String name, ObjectStorageAccountArgs args, @Nullable com.pulumi.resources.CustomResourceOptions options) {
        super("cape:objectstorage:ObjectStorageAccount", name, makeArgs(args, options), makeResourceOptions(options, Codegen.empty()), false);
    }

    private ObjectStorageAccount(java.lang.String name, Output<java.lang.String> id, @Nullable com.pulumi.resources.CustomResourceOptions options) {
        super("cape:objectstorage:ObjectStorageAccount", name, null, makeResourceOptions(options, id), false);
    }

    private static ObjectStorageAccountArgs makeArgs(ObjectStorageAccountArgs args, @Nullable com.pulumi.resources.CustomResourceOptions options) {
        if (options != null && options.getUrn().isPresent()) {
            return null;
        }
        return args == null ? ObjectStorageAccountArgs.Empty : args;
    }

    private static com.pulumi.resources.CustomResourceOptions makeResourceOptions(@Nullable com.pulumi.resources.CustomResourceOptions options, @Nullable Output<java.lang.String> id) {
        var defaultOptions = com.pulumi.resources.CustomResourceOptions.builder()
            .version(Utilities.getVersion())
            .build();
        return com.pulumi.resources.CustomResourceOptions.merge(defaultOptions, options, id);
    }

    /**
     * Get an existing Host resource's state with the given name, ID, and optional extra
     * properties used to qualify the lookup.
     *
     * @param name The _unique_ name of the resulting resource.
     * @param id The _unique_ provider ID of the resource to lookup.
     * @param options Optional settings to control the behavior of the CustomResource.
     */
    public static ObjectStorageAccount get(java.lang.String name, Output<java.lang.String> id, @Nullable com.pulumi.resources.CustomResourceOptions options) {
        return new ObjectStorageAccount(name, id, options);
    }
}
