// *** WARNING: this file was generated by pulumi-language-nodejs. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from "@pulumi/pulumi";
import * as inputs from "../types/input";
import * as outputs from "../types/output";
import * as utilities from "../utilities";

/**
 * Instance resource representing a virtual machine in the cloud provider's infrastructure. This resource is used to manage the lifecycle of the instance, including its creation, updates, and deletion.
 */
export class Instance extends pulumi.CustomResource {
    /**
     * Get an existing Instance resource's state with the given name, ID, and optional extra
     * properties used to qualify the lookup.
     *
     * @param name The _unique_ name of the resulting resource.
     * @param id The _unique_ provider ID of the resource to lookup.
     * @param opts Optional settings to control the behavior of the CustomResource.
     */
    public static get(name: string, id: pulumi.Input<pulumi.ID>, opts?: pulumi.CustomResourceOptions): Instance {
        return new Instance(name, undefined as any, { ...opts, id: id });
    }

    /** @internal */
    public static readonly __pulumiType = 'cape:compute:Instance';

    /**
     * Returns true if the given object is an instance of Instance.  This is designed to work even
     * when multiple copies of the Pulumi SDK have been loaded into the same process.
     */
    public static isInstance(obj: any): obj is Instance {
        if (obj === undefined || obj === null) {
            return false;
        }
        return obj['__pulumiType'] === Instance.__pulumiType;
    }

    /**
     * User-defined key/value pairs that are mutable and can be used to add annotations. The number of annotations is eventually limited by the CSP.
     */
    declare public readonly annotations: pulumi.Output<{[key: string]: string} | undefined>;
    /**
     * User-defined key/value pairs that are mutable and can be used to add extensions. Extensions are subject to validation by the CSP, and any value that is not accepted will be rejected during admission.
     */
    declare public readonly extensions: pulumi.Output<{[key: string]: string} | undefined>;
    /**
     * User-defined key/value pairs that are mutable and can be used to organize and categorize resources. They can be used to filter resources. The number of labels is eventually limited by the CSP.
     */
    declare public readonly labels: pulumi.Output<{[key: string]: string} | undefined>;
    /**
     * Metadata for regional resources with name, permission, modification, type, tenant and workspace and region information.
     */
    declare public /*out*/ readonly metadata: pulumi.Output<outputs.schemas.RegionalWorkspaceResourceMetadata>;
    /**
     * Specification of the instance, including its SKU, network configuration, and storage options.
     */
    declare public readonly spec: pulumi.Output<outputs.schemas.InstanceSpec>;
    /**
     * Current status of the instance.
     */
    declare public /*out*/ readonly status: pulumi.Output<outputs.schemas.InstanceStatus>;
    /**
     * The tenant for the resource. If omitted, the provider default is used.
     */
    declare public readonly tenant: pulumi.Output<string | undefined>;
    /**
     * The workspace for the resource. If omitted, the provider default is used. Must be configured by either means.
     */
    declare public readonly workspace: pulumi.Output<string | undefined>;

    /**
     * Create a Instance resource with the given unique name, arguments, and options.
     *
     * @param name The _unique_ name of the resource.
     * @param args The arguments to use to populate this resource's properties.
     * @param opts A bag of options that control this resource's behavior.
     */
    constructor(name: string, args: InstanceArgs, opts?: pulumi.CustomResourceOptions) {
        let resourceInputs: pulumi.Inputs = {};
        opts = opts || {};
        if (!opts.id) {
            if (args?.spec === undefined && !opts.urn) {
                throw new Error("Missing required property 'spec'");
            }
            resourceInputs["annotations"] = args?.annotations;
            resourceInputs["extensions"] = args?.extensions;
            resourceInputs["labels"] = args?.labels;
            resourceInputs["spec"] = args ? (args.spec ? pulumi.output(args.spec).apply(inputs.schemas.instanceSpecArgsProvideDefaults) : undefined) : undefined;
            resourceInputs["tenant"] = args?.tenant;
            resourceInputs["workspace"] = args?.workspace;
            resourceInputs["metadata"] = undefined /*out*/;
            resourceInputs["status"] = undefined /*out*/;
        } else {
            resourceInputs["annotations"] = undefined /*out*/;
            resourceInputs["extensions"] = undefined /*out*/;
            resourceInputs["labels"] = undefined /*out*/;
            resourceInputs["metadata"] = undefined /*out*/;
            resourceInputs["spec"] = undefined /*out*/;
            resourceInputs["status"] = undefined /*out*/;
            resourceInputs["tenant"] = undefined /*out*/;
            resourceInputs["workspace"] = undefined /*out*/;
        }
        opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts);
        super(Instance.__pulumiType, name, resourceInputs, opts);
    }
}

/**
 * The set of arguments for constructing a Instance resource.
 */
export interface InstanceArgs {
    /**
     * User-defined key/value pairs that are mutable and can be used to add annotations. The number of annotations is eventually limited by the CSP.
     */
    annotations?: pulumi.Input<{[key: string]: pulumi.Input<string>}>;
    /**
     * User-defined key/value pairs that are mutable and can be used to add extensions. Extensions are subject to validation by the CSP, and any value that is not accepted will be rejected during admission.
     */
    extensions?: pulumi.Input<{[key: string]: pulumi.Input<string>}>;
    /**
     * User-defined key/value pairs that are mutable and can be used to organize and categorize resources. They can be used to filter resources. The number of labels is eventually limited by the CSP.
     */
    labels?: pulumi.Input<{[key: string]: pulumi.Input<string>}>;
    /**
     * Specification of the instance, including its SKU, network configuration, and storage options.
     */
    spec: pulumi.Input<inputs.schemas.InstanceSpecArgs>;
    /**
     * The tenant for the resource. If omitted, the provider default is used.
     */
    tenant?: pulumi.Input<string>;
    /**
     * The workspace for the resource. If omitted, the provider default is used. Must be configured by either means.
     */
    workspace?: pulumi.Input<string>;
}
